/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import ErgodicTheory.Entropy.CondChainRule
import ErgodicTheory.Entropy.Generator

/-!
# The additive-over-cells conditional entropy is the σ-algebra conditional entropy

This module proves the **W2 bridge lemma** of issue #13 §5b: for a finite measurable partition
`B` of a standard-Borel probability space, the additive-over-cells conditional entropy
`H(Q | B) = ∑ᵢ μ(Bᵢ) · H(Q | Bᵢ)` (the `condEntropyGivenPartition` of `CondChainRule`, the
`𝒜 = ⊥` form) coincides with the σ-algebra conditional entropy `H(Q | σ(B))` (the `condEntropy`
of `CondPartition`, conditioning on the σ-algebra `σ(B) = generatedSigmaAlgebra μ B` generated by
the cells of `B`):
`condEntropyGivenPartition μ B.cells t = condEntropy μ (generatedSigmaAlgebra μ B) t`.

This identifies the elementary, finite-sum definition of conditional entropy used in the
Abramov–Rokhlin chain rule with the kernel/disintegration definition `H(· | σ(B))`, and is a
prerequisite for the W3 sub-piece.

## Proof outline

The crux is the **atom-agreement** kernel identity: for `μ`-a.e. `ω` lying in the cell `Bᵢ`,
the regular conditional probability of `tⱼ` given `σ(B)` is the cell-conditional value
`μ(Bᵢ ∩ tⱼ) / μ(Bᵢ)`. Concretely we prove that the piecewise-constant candidate
`gⱼ(ω) = ∑ᵢ (μ(Bᵢ ∩ tⱼ)/μ(Bᵢ)) · 𝟙_{Bᵢ}(ω)` (`condCandidate`) is a version of the conditional
expectation `μ⟦tⱼ | σ(B)⟧`, via `ae_eq_condExp_of_forall_setIntegral_eq`. Its set-integral
hypothesis — `∫ x in s, gⱼ x ∂μ = μ(s ∩ tⱼ).toReal` for every `σ(B)`-measurable `s` — rests on the
**atom property** of `σ(B)` (`generatedSigmaAlgebra_atom`): every `σ(B)`-measurable set is, modulo
`μ`-null sets, a union of cells (proved by induction on the `generateFrom` structure, the
countable-union step closing for *arbitrary*, not just disjoint, unions). On each cell `s` is then
all-or-nothing, so the indicator term `(μ(Bᵢ ∩ tⱼ)/μ(Bᵢ)) · μ(s ∩ Bᵢ)` equals `μ(s ∩ Bᵢ ∩ tⱼ)`
(`condCandidate_cell_scaling`), and summing over the covering cells gives `μ(s ∩ tⱼ)` via the
marginal identity `MeasurePartition.measure_eq_sum_inter`.

Bridging the kernel to `condExp` (`condExpKernel_ae_eq_condExp`) and splitting the defining
integral of `condEntropy` over the a.e.-disjoint covering cells (`integral_iUnion_ae`) — on each of
which the integrand is the constant `condEntropyOnCell μ Bᵢ t` — then yields the claim.

## Main results

* `ErgodicTheory.Entropy.condEntropyGivenPartition_eq_condEntropy_generated`: the bridge lemma
  `H(Q | B) = H(Q | σ(B))`.
-/

open MeasureTheory Function Filter ProbabilityTheory MeasurableSpace
open scoped ENNReal

namespace ErgodicTheory.Entropy

variable {α : Type*} {ι κ : Type*} [mα : MeasurableSpace α] [StandardBorelSpace α]

section Bridge

variable [Fintype ι]

-- None of the bridge helpers (atom property, candidate, set-integrals, conditional expectation)
-- use the standard-Borel structure; that is only needed for the regular conditional kernel in the
-- main theorem (a separate section). Omit it section-wide to satisfy the unused-variable linter.
omit [StandardBorelSpace α]

/-- A cell `B.cells i` of a finite partition is measurable for the generated σ-algebra
`σ(B) = generateFrom (range B.cells)`. -/
lemma measurableSet_generatedSigmaAlgebra_cell {μ : Measure α} (B : MeasurePartition μ ι)
    (i : ι) : MeasurableSet[generatedSigmaAlgebra μ B] (B.cells i) :=
  measurableSet_generateFrom ⟨i, rfl⟩

/-- The generated σ-algebra `σ(B)` is below the ambient σ-algebra `mα` (every cell is
`mα`-measurable). -/
lemma generatedSigmaAlgebra_le {μ : Measure α} (B : MeasurePartition μ ι) :
    generatedSigmaAlgebra μ B ≤ mα :=
  generateFrom_le <| by rintro s ⟨i, rfl⟩; exact B.measurable i

/-- **Atom property of the generated σ-algebra.** Every `σ(B)`-measurable set is, modulo `μ`-null
sets, a union of cells: on each cell `Bᵢ` it is all-or-nothing. Either `Bᵢ` meets the set in a
null set, or `Bᵢ` is contained in the set up to a null set.

Proved by induction on the `generateFrom` structure: a cell is all-or-nothing on every cell
(distinct cells are `μ`-a.e. disjoint; a cell against itself); complementation swaps the two
alternatives; and a countable union is null on `Bᵢ` if every piece is, else contains `Bᵢ` up to a
null set as soon as one piece does. -/
lemma generatedSigmaAlgebra_atom {μ : Measure α} (B : MeasurePartition μ ι)
    {s : Set α} (hs : MeasurableSet[generatedSigmaAlgebra μ B] s) (i : ι) :
    μ (B.cells i ∩ s) = 0 ∨ μ (B.cells i \ s) = 0 := by
  rw [generatedSigmaAlgebra] at hs
  induction s, hs using MeasurableSpace.generateFrom_induction with
  | hC t ht _ =>
    obtain ⟨k, rfl⟩ := ht
    rcases eq_or_ne i k with rfl | hik
    · exact Or.inr (by simp)
    · exact Or.inl (B.aedisjoint hik)
  | empty => exact Or.inl (by simp)
  | compl t ht ih =>
    -- `Bᵢ ∩ tᶜ = Bᵢ \ t` and `Bᵢ \ tᶜ = Bᵢ ∩ t`, so the two alternatives just swap.
    rw [← Set.diff_eq, Set.diff_compl]
    exact ih.symm
  | iUnion f hf ih =>
    by_cases hall : ∀ n, μ (B.cells i ∩ f n) = 0
    · refine Or.inl (measure_mono_null ?_ (measure_iUnion_null hall))
      rw [Set.inter_iUnion]
    · rw [not_forall] at hall
      obtain ⟨n, hn⟩ := hall
      refine Or.inr (measure_mono_null ?_ ((ih n).resolve_left hn))
      intro x hx; exact ⟨hx.1, fun hxU => hx.2 (Set.mem_iUnion.2 ⟨n, hxU⟩)⟩

/-- The piecewise-constant candidate for the conditional expectation `μ⟦t j | σ(B)⟧`: the function
taking the cell-conditional value `μ(Bᵢ ∩ t j) / μ(Bᵢ)` on each cell `Bᵢ`. Written as a finite sum
of indicators of the cells, it is `σ(B)`-strongly measurable. -/
noncomputable def condCandidate {μ : Measure α} (B : MeasurePartition μ ι) (tj : Set α)
    (ω : α) : ℝ :=
  ∑ i, (B.cells i).indicator (fun _ => (μ (B.cells i ∩ tj)).toReal / (μ (B.cells i)).toReal) ω

/-- The candidate is `σ(B)`-strongly measurable: a finite sum of indicators of cells (which are
`σ(B)`-measurable) scaled by constants. -/
lemma stronglyMeasurable_condCandidate {μ : Measure α} (B : MeasurePartition μ ι) (tj : Set α) :
    StronglyMeasurable[generatedSigmaAlgebra μ B] (condCandidate B tj) := by
  refine Finset.stronglyMeasurable_fun_sum _ (fun i _ => ?_)
  exact stronglyMeasurable_const.indicator (measurableSet_generatedSigmaAlgebra_cell B i)

/-- **Per-cell scaling identity.** For a `σ(B)`-measurable set `s` and a measurable `tⱼ`, the
cell-conditional value `μ(Bᵢ ∩ tⱼ)/μ(Bᵢ)` scaled by `μ(s ∩ Bᵢ)` equals `μ(s ∩ Bᵢ ∩ tⱼ)`. This is
where the atom property enters: on the cell `Bᵢ`, `s` is all-or-nothing (mod null), so the
proportion `μ(Bᵢ ∩ tⱼ)/μ(Bᵢ)` of the cell that lies in `tⱼ` is exactly the proportion of `s ∩ Bᵢ`
that lies in `tⱼ`. -/
lemma condCandidate_cell_scaling {μ : Measure α} [IsFiniteMeasure μ] (B : MeasurePartition μ ι)
    {tj : Set α} {s : Set α} (hs : MeasurableSet[generatedSigmaAlgebra μ B] s) (i : ι) :
    (μ (B.cells i ∩ tj)).toReal / (μ (B.cells i)).toReal * (μ (s ∩ B.cells i)).toReal
      = (μ (s ∩ B.cells i ∩ tj)).toReal := by
  rcases generatedSigmaAlgebra_atom B hs i with hatom | hatom
  · -- `μ (Bᵢ ∩ s) = 0`: both `μ (s ∩ Bᵢ)` and `μ (s ∩ Bᵢ ∩ tⱼ)` vanish.
    have h1 : μ (s ∩ B.cells i) = 0 := by rwa [Set.inter_comm] at hatom
    have h2 : μ (s ∩ B.cells i ∩ tj) = 0 := measure_mono_null Set.inter_subset_left h1
    simp [h1, h2]
  · -- `μ (Bᵢ \ s) = 0`: `s` swallows `Bᵢ` (mod null), so `s ∩ Bᵢ =ᵐ Bᵢ`.
    have heq1 : μ (s ∩ B.cells i) = μ (B.cells i) := by
      apply le_antisymm (measure_mono Set.inter_subset_right)
      have : B.cells i ⊆ (s ∩ B.cells i) ∪ (B.cells i \ s) := by
        intro x hx; by_cases hxs : x ∈ s
        · exact Or.inl ⟨hxs, hx⟩
        · exact Or.inr ⟨hx, hxs⟩
      calc μ (B.cells i) ≤ μ ((s ∩ B.cells i) ∪ (B.cells i \ s)) := measure_mono this
        _ ≤ μ (s ∩ B.cells i) + μ (B.cells i \ s) := measure_union_le _ _
        _ = μ (s ∩ B.cells i) := by rw [hatom, add_zero]
    have heq2 : μ (s ∩ B.cells i ∩ tj) = μ (B.cells i ∩ tj) := by
      apply le_antisymm (measure_mono (Set.inter_subset_inter_left _ Set.inter_subset_right))
      have hsub : B.cells i ∩ tj ⊆ (s ∩ B.cells i ∩ tj) ∪ (B.cells i \ s) := by
        intro x hx; by_cases hxs : x ∈ s
        · exact Or.inl ⟨⟨hxs, hx.1⟩, hx.2⟩
        · exact Or.inr ⟨hx.1, hxs⟩
      calc μ (B.cells i ∩ tj) ≤ μ ((s ∩ B.cells i ∩ tj) ∪ (B.cells i \ s)) := measure_mono hsub
        _ ≤ μ (s ∩ B.cells i ∩ tj) + μ (B.cells i \ s) := measure_union_le _ _
        _ = μ (s ∩ B.cells i ∩ tj) := by rw [hatom, add_zero]
    rw [heq1, heq2]
    rcases eq_or_ne (μ (B.cells i)) 0 with hzero | hzero
    · have : μ (B.cells i ∩ tj) = 0 := measure_mono_null Set.inter_subset_left hzero
      rw [hzero, this, ENNReal.toReal_zero, mul_zero]
    · have hne : (μ (B.cells i)).toReal ≠ 0 := by
        rw [ne_eq, ENNReal.toReal_eq_zero_iff, not_or]
        exact ⟨hzero, measure_ne_top μ _⟩
      rw [div_mul_cancel₀ _ hne]

/-- **Set-integral of the candidate.** For every `σ(B)`-measurable set `s`,
`∫ x in s, condCandidate B tⱼ x ∂μ = μ(s ∩ tⱼ).toReal`.

The integral distributes over the finite indicator sum; the `i`-th term is
`(μ(Bᵢ ∩ tⱼ)/μ(Bᵢ)) · μ(s ∩ Bᵢ).toReal`, which equals `μ(s ∩ Bᵢ ∩ tⱼ).toReal` by the per-cell
scaling identity; summing these over the a.e.-disjoint covering cells recovers `μ(s ∩ tⱼ).toReal`
via the marginal identity `MeasurePartition.measure_eq_sum_inter`. -/
lemma setIntegral_condCandidate {μ : Measure α} [IsFiniteMeasure μ] (B : MeasurePartition μ ι)
    {tj : Set α} (htj : MeasurableSet tj) {s : Set α}
    (hs : MeasurableSet[generatedSigmaAlgebra μ B] s) :
    ∫ x in s, condCandidate B tj x ∂μ = (μ (s ∩ tj)).toReal := by
  have hsm : MeasurableSet s := (generatedSigmaAlgebra_le B) s hs
  simp only [condCandidate]
  -- Interchange the finite sum with the (set) integral.
  rw [integral_finsetSum]
  swap
  · intro i _
    exact (integrable_const _).indicator (B.measurable i) |>.restrict
  -- Evaluate each indicator integral as `μ.real (s ∩ Bᵢ) • cᵢ`.
  have hterm : ∀ i, ∫ x in s,
      (B.cells i).indicator
        (fun _ => (μ (B.cells i ∩ tj)).toReal / (μ (B.cells i)).toReal) x ∂μ
      = (μ (B.cells i ∩ tj)).toReal / (μ (B.cells i)).toReal * (μ (s ∩ B.cells i)).toReal := by
    intro i
    rw [setIntegral_indicator (B.measurable i), setIntegral_const, smul_eq_mul,
      measureReal_def, mul_comm]
  simp_rw [hterm]
  -- Apply the per-cell scaling identity and the marginal identity over the covering cells.
  rw [show (∑ i, (μ (B.cells i ∩ tj)).toReal / (μ (B.cells i)).toReal
        * (μ (s ∩ B.cells i)).toReal)
      = ∑ i, (μ (s ∩ B.cells i ∩ tj)).toReal from
    Finset.sum_congr rfl fun i _ => condCandidate_cell_scaling B hs i]
  rw [← ENNReal.toReal_sum (fun i _ => measure_ne_top μ _)]
  congr 1
  rw [B.measure_eq_sum_inter (hsm.inter htj)]
  exact Finset.sum_congr rfl fun i _ => by rw [Set.inter_right_comm]

/-- **The candidate is a version of the conditional expectation.** For a finite measure and a
measurable `tⱼ`, the piecewise-constant `condCandidate B tⱼ` equals the conditional expectation
`μ⟦tⱼ | σ(B)⟧` almost everywhere. Verified via `ae_eq_condExp_of_forall_setIntegral_eq`: the
candidate is `σ(B)`-strongly measurable (`stronglyMeasurable_condCandidate`) and matches the
set-integrals of the indicator `𝟙_{tⱼ}` on every `σ(B)`-measurable set
(`setIntegral_condCandidate`). -/
lemma condCandidate_ae_eq_condExp {μ : Measure α} [IsFiniteMeasure μ] (B : MeasurePartition μ ι)
    {tj : Set α} (htj : MeasurableSet tj) :
    condCandidate B tj =ᵐ[μ] μ⟦tj | generatedSigmaAlgebra μ B⟧ := by
  have hm : generatedSigmaAlgebra μ B ≤ mα := generatedSigmaAlgebra_le B
  have hsf : SigmaFinite (μ.trim hm) := inferInstance
  have hf : Integrable (tj.indicator (fun _ => (1 : ℝ))) μ :=
    (integrable_const (1 : ℝ)).indicator htj
  -- The candidate is bounded, hence integrable on every finite-measure piece.
  have hgint : ∀ s, MeasurableSet[generatedSigmaAlgebra μ B] s → μ s < ∞ →
      IntegrableOn (condCandidate B tj) s μ := by
    intro s hs _
    refine Integrable.integrableOn ?_
    refine integrable_finsetSum _ (fun i _ => ?_)
    exact (integrable_const _).indicator (B.measurable i)
  have hgeq : ∀ s, MeasurableSet[generatedSigmaAlgebra μ B] s → μ s < ∞ →
      ∫ x in s, condCandidate B tj x ∂μ = ∫ x in s, tj.indicator (fun _ => (1 : ℝ)) x ∂μ := by
    intro s hs _
    rw [setIntegral_condCandidate B htj hs, setIntegral_indicator htj, setIntegral_const,
      smul_eq_mul, mul_one, measureReal_def]
  exact ae_eq_condExp_of_forall_setIntegral_eq hm hf hgint hgeq
    (stronglyMeasurable_condCandidate B tj).aestronglyMeasurable

/-- **The candidate is constant on each cell, a.e.** For `μ`-a.e. `ω ∈ Bᵢ`, the value of
`condCandidate B tⱼ ω` is the cell-conditional value `μ(Bᵢ ∩ tⱼ)/μ(Bᵢ)`: only the `i`-th indicator
of the defining sum is nonzero, since the set of points of `Bᵢ` that also lie in another cell is
`μ`-null (the cells are a.e. disjoint). -/
lemma condCandidate_ae_eq_on_cell {μ : Measure α} (B : MeasurePartition μ ι) (tj : Set α)
    (i : ι) :
    (fun ω => condCandidate B tj ω)
      =ᵐ[μ.restrict (B.cells i)]
      fun _ => (μ (B.cells i ∩ tj)).toReal / (μ (B.cells i)).toReal := by
  -- The points of `Bᵢ` lying in some other cell form a null set; off it, only the `i`-th term
  -- of the indicator sum survives.
  have hnull : ∀ k, k ≠ i → ∀ᵐ ω ∂μ.restrict (B.cells i), ω ∉ B.cells k := by
    intro k hki
    rw [ae_restrict_iff' (B.measurable i)]
    have hnk : μ (B.cells i ∩ B.cells k) = 0 := B.aedisjoint (Ne.symm hki)
    have hae : ∀ᵐ ω ∂μ, ω ∉ B.cells i ∩ B.cells k := by rw [ae_iff]; simpa using hnk
    filter_upwards [hae] with ω hω hωi
    simp only [Set.mem_inter_iff, not_and] at hω
    exact hω hωi
  have hnull' : ∀ᵐ ω ∂μ.restrict (B.cells i), ∀ k, k ≠ i → ω ∉ B.cells k := by
    rw [ae_all_iff]; intro k
    by_cases hki : k = i
    · subst hki; exact Eventually.of_forall fun ω hk => absurd rfl hk
    · filter_upwards [hnull k hki] with ω hω _ using hω
  have hself : ∀ᵐ ω ∂μ.restrict (B.cells i), ω ∈ B.cells i := by
    rw [ae_restrict_iff' (B.measurable i)]; exact Eventually.of_forall (fun ω h => h)
  filter_upwards [hnull', hself] with ω hω hωi
  rw [condCandidate, Finset.sum_eq_single i]
  · rw [Set.indicator_of_mem hωi]
  · intro k _ hki
    rw [Set.indicator_of_notMem (hω k hki)]
  · intro h; exact absurd (Finset.mem_univ i) h

end Bridge

section Main

variable [Fintype ι] [Fintype κ]

/-- **W2 bridge lemma.** The additive-over-cells conditional entropy `H(Q | B)` of a finite family
`t` given a finite measurable partition `B` equals the σ-algebra conditional entropy `H(Q | σ(B))`
obtained by conditioning on the σ-algebra `σ(B) = generatedSigmaAlgebra μ B` generated by the cells
of `B`:
`condEntropyGivenPartition μ B.cells t = condEntropy μ (generatedSigmaAlgebra μ B) t`.

This identifies the elementary finite-sum definition of conditional entropy used in the
Abramov–Rokhlin chain rule (`CondChainRule`) with the kernel/disintegration definition
(`CondPartition`). The crux is the atom-agreement kernel identity: for `μ`-a.e. `ω ∈ Bᵢ`, the
regular conditional probability `condExpKernel μ (σ(B)) ω (tⱼ)` equals the cell-conditional value
`μ(Bᵢ ∩ tⱼ)/μ(Bᵢ)`, established by identifying the piecewise-constant candidate with the
conditional expectation (`condCandidate_ae_eq_condExp`) and bridging the kernel to `condExp`
(`condExpKernel_ae_eq_condExp`). The defining integral of `condEntropy` then splits over the
a.e.-disjoint covering cells (`integral_iUnion_ae`), and on each cell the integrand is the constant
`condEntropyOnCell μ Bᵢ t`, summing to `condEntropyGivenPartition`. -/
theorem condEntropyGivenPartition_eq_condEntropy_generated {μ : Measure α}
    [IsProbabilityMeasure μ] (B : MeasurePartition μ ι) (t : κ → Set α)
    (ht : ∀ j, MeasurableSet (t j)) :
    condEntropyGivenPartition μ B.cells t = condEntropy μ (generatedSigmaAlgebra μ B) t := by
  have hm : generatedSigmaAlgebra μ B ≤ mα := generatedSigmaAlgebra_le B
  -- The `condEntropy` integrand `F` and the candidate-built integrand `G`.
  let F : α → ℝ := fun ω =>
    ∑ j, Real.negMulLog (@condExpKernel α mα _ μ _ (generatedSigmaAlgebra μ B) ω (t j)).toReal
  let G : α → ℝ := fun ω => ∑ j, Real.negMulLog (condCandidate B (t j) ω)
  -- Step 1: `F =ᵐ G`. For each `j`, the kernel probability is a.e. the candidate value.
  have hFG : F =ᵐ[μ] G := by
    have hcell : ∀ j,
        (fun ω => (@condExpKernel α mα _ μ _ (generatedSigmaAlgebra μ B) ω (t j)).toReal)
          =ᵐ[μ] fun ω => condCandidate B (t j) ω := by
      intro j
      have h1 := condExpKernel_ae_eq_condExp (μ := μ) (m := generatedSigmaAlgebra μ B) hm (ht j)
      have h2 := (condCandidate_ae_eq_condExp B (ht j)).symm
      filter_upwards [h1, h2] with ω hω1 hω2
      rw [measureReal_def] at hω1
      rw [hω1, ← hω2]
    filter_upwards [ae_all_iff.2 hcell] with ω hω
    exact Finset.sum_congr rfl fun j _ => by rw [hω j]
  -- Step 2: rewrite `condEntropy` as `∫ G`.
  rw [condEntropy_def]
  rw [show (∫ ω, (∑ j,
        Real.negMulLog (@condExpKernel α mα _ μ _ (generatedSigmaAlgebra μ B) ω (t j)).toReal) ∂μ)
      = ∫ ω, F ω ∂μ from rfl, integral_congr_ae hFG]
  -- Step 3: split `∫ G` over the a.e.-disjoint covering cells.
  -- `G` is integrable, being a.e. equal to the (integrable) `condEntropy` integrand `F`.
  have hFint : Integrable F μ := integrable_condEntropy_integrand hm t ht
  have hGint : Integrable G μ := hFint.congr hFG
  -- `∫ G = ∫_univ G = ∑ᵢ ∫_{Bᵢ} G`, using the a.e.-disjoint cover by the cells.
  have hcover : (⋃ i, B.cells i) = Set.univ := B.cover
  have hsplit : ∫ ω, G ω ∂μ = ∑ i, ∫ ω in B.cells i, G ω ∂μ := by
    rw [← setIntegral_univ (μ := μ), ← hcover,
      integral_iUnion_ae (fun i => (B.measurable i).nullMeasurableSet) B.aedisjoint
        (by rw [hcover]; exact hGint.integrableOn),
      tsum_fintype]
  rw [hsplit, condEntropyGivenPartition]
  -- On each cell `Bᵢ`, `G` is a.e. the constant `condEntropyOnCell μ Bᵢ t`.
  refine Finset.sum_congr rfl fun i _ => ?_
  have hGcell : (fun ω => G ω)
      =ᵐ[μ.restrict (B.cells i)] fun _ => condEntropyOnCell μ (B.cells i) t := by
    have hcand : ∀ j, (fun ω => condCandidate B (t j) ω)
        =ᵐ[μ.restrict (B.cells i)]
        fun _ => (μ (B.cells i ∩ t j)).toReal / (μ (B.cells i)).toReal :=
      fun j => condCandidate_ae_eq_on_cell B (t j) i
    filter_upwards [ae_all_iff.2 hcand] with ω hω
    simp only [G, condEntropyOnCell]
    exact Finset.sum_congr rfl fun j _ => by rw [hω j]
  rw [show (∫ ω in B.cells i, G ω ∂μ)
      = ∫ _ω in B.cells i, condEntropyOnCell μ (B.cells i) t ∂μ from
    setIntegral_congr_ae (B.measurable i) (ae_imp_of_ae_restrict hGcell),
    setIntegral_const, smul_eq_mul, measureReal_def, mul_comm]

end Main

end ErgodicTheory.Entropy
