/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import ErgodicTheory.Entropy.KSEntropySystem

/-!
# Generating partitions and the supplied-generator entropy interface

A finite measurable partition `P` of a measure-preserving system `(α, T, μ)` is a **generator**
(or *generating partition*) when the dynamics, refined under the forward iterates of `T`, recovers
the whole measurable structure: the smallest `T`-pullback-stable σ-algebra containing the σ-algebra
`σ(P)` generated by the cells of `P` is the ambient σ-algebra `mα`.

The classical **Kolmogorov–Sinai theorem** then asserts the entropy reduction
`h(T) = h(P, T)` for any generator `P`: the supremum defining the entropy of the system is already
attained on a single generating partition. Proving that theorem is a substantial undertaking; this
file deliberately does **not** prove it. Following the verified design plan for the
Abramov–Rokhlin assembly (issue #13), the M6 conditional-entropy layer ships under *supplied*
generator-reduction equalities rather than a generator theorem. Accordingly this file provides the
`IsGenerating` **predicate**, stated in the honest exact-equality σ-algebra form, together with
its unfolded restatement (`IsGenerating.le`). The generator-reduction equality `h(T) = h(P, T)`
itself is supplied by `ErgodicTheory.Entropy.ksEntropy_eq_ksEntropyPartition_of_generating`
(`ErgodicTheory.Entropy.GeneratorTheorem`).

## Design note: which σ-algebra equation?

The generated invariant σ-algebra is taken as `⨆ n, comap (T^[n]) σ(P)`, the supremum over the
*forward* iterates `T^[n]` of the pulled-back generating σ-algebra `σ(P) = generateFrom (range
P.cells)`. This is the standard one-sided generator condition for a (possibly non-invertible)
endomorphism: a point's whole `μ`-essential coordinates are recovered from the observable `P` and
its forward time-translates. The exact equality with `mα` is clean to state and is the form used by
the Kolmogorov–Sinai theorem; a `≤ mα` direction always holds (`IsGenerating` is then the reverse
saturation), so the predicate is genuinely a hypothesis, not a triviality.

## Main definitions

* `ErgodicTheory.Entropy.IsGenerating`: `P` generates the dynamics — the smallest
  forward-`T`-invariant
  σ-algebra containing `σ(P)` is the ambient σ-algebra.

## Main results

* `ErgodicTheory.Entropy.IsGenerating.le`: a generating partition's forward-saturated σ-algebra is
  the
  ambient σ-algebra (unfolded form).

## References

* François Le Maître, *Notes on the Kolmogorov–Sinai theorem* (2017), §2 (the Kolmogorov–Sinai
  generator theorem).
* Peter Walters, *An Introduction to Ergodic Theory*, GTM **79**, Springer (1982), Ch. 4.
-/

open MeasureTheory Function MeasurableSpace

namespace ErgodicTheory.Entropy

variable {α : Type*} {ι : Type*} [mα : MeasurableSpace α] [Fintype ι]

/-- The σ-algebra `σ(P) = generateFrom (range P.cells)` generated by the cells of a finite
partition `P`. This is the static observable σ-algebra: the smallest σ-algebra making membership in
each cell of `P` measurable. Marked `@[reducible]` since its value is a `MeasurableSpace` (a class
type), so it must unfold for instance resolution and definitional rewriting. -/
@[reducible]
def generatedSigmaAlgebra (μ : Measure α) (P : MeasurePartition μ ι) : MeasurableSpace α :=
  MeasurableSpace.generateFrom (Set.range P.cells)

/-- **Reindexing leaves the generated σ-algebra unchanged.** The cell family is merely permuted, so
its range — and hence the σ-algebra it generates — is the same. -/
lemma generatedSigmaAlgebra_reindex {κ : Type*} [Fintype κ] {μ : Measure α}
    (P : MeasurePartition μ ι) (e : κ ≃ ι) :
    generatedSigmaAlgebra μ (P.reindex e) = generatedSigmaAlgebra μ P := by
  have hr : Set.range (P.reindex e).cells = Set.range P.cells :=
    e.surjective.range_comp P.cells
  unfold generatedSigmaAlgebra
  rw [hr]

/-- `P` is a **generating partition** (a *generator*) for the measure-preserving system `(α, T, μ)`
when the smallest forward-`T`-pullback-stable σ-algebra containing the generated σ-algebra `σ(P)`
is the ambient measurable structure `mα`:
`⨆ n, comap (T^[n]) σ(P) = mα`.

This is the standard one-sided generator condition for a (possibly non-invertible) endomorphism:
the whole measurable structure is recovered from the observable `P` together with its forward
time-translates `T^[n]`. The Kolmogorov–Sinai theorem then gives the entropy reduction
`h(T) = h(P, T)`; that theorem is *not* proved here — this predicate is the hypothesis the
supplied-generator entropy interface (issue #13, Abramov–Rokhlin) consumes. -/
def IsGenerating (μ : Measure α) (T : α → α) (P : MeasurePartition μ ι) : Prop :=
  (⨆ n : ℕ, MeasurableSpace.comap (T^[n]) (generatedSigmaAlgebra μ P)) = mα

/-- Unfolded form of `IsGenerating`: a generating partition's forward-saturated σ-algebra equals
the ambient measurable structure. This is just the definition, named for convenient consumption by
the Abramov–Rokhlin assembly. -/
lemma IsGenerating.le {μ : Measure α} {T : α → α}
    {P : MeasurePartition μ ι} (h : IsGenerating μ T P) :
    (⨆ n : ℕ, MeasurableSpace.comap (T^[n]) (generatedSigmaAlgebra μ P)) = mα :=
  h

end ErgodicTheory.Entropy
