/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Mathlib.MeasureTheory.Group.FundamentalDomain
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.Dynamics.BirkhoffSum.Basic

/-!
# The suspension (mapping-torus) of a measure-preserving map

This module builds the *suspension* (also called the *mapping torus* or *flow under a roof
function*) of a measure-preserving base map `T : X ≃ᵐ X` with a strictly positive roof function
`τ : X → ℝ`. The suspension carries the natural one-parameter flow `[x, s] ↦ [x, s + t]`, and it
is the standard device for transferring the discrete-time Oseledets multiplicative ergodic theorem
to the continuous-flow setting (Ambrose–Kakutani; Bessa–Varandas).

Following the *quotient* model, the suspension space is

`Xᵗ := Quotient (AddAction.orbitRel ℤ (X × ℝ))`,

where the `ℤ`-action is generated by the measurable automorphism

`G (x, s) = (T x, s − τ x)`

identifying `(x, s)` with `(T x, s − τ x)`. The half-open *box under the roof*

`suspensionDomain τ = {p : X × ℝ | 0 ≤ p.2 ∧ p.2 < τ p.1}`

is a fundamental domain for this action with respect to `μ.prod volume`, and that is the keystone
result of this file: `ErgodicTheory.isAddFundamentalDomain_suspensionDomain`. It is the
Ambrose–Kakutani cross-section structure from which the suspension's invariant probability measure
`(μ × Leb)|_box / ∫ τ` and the per-time measure-preservation of the flow are subsequently obtained.

## Main definitions

* `ErgodicTheory.suspensionGen`: the generating measurable automorphism `G (x, s) = (T x, s − τ x)`.
* `ErgodicTheory.suspensionVAdd`: the `AddAction ℤ (X × ℝ)` generated by `suspensionGen`, defined as
  the `zpow` of the underlying permutation.
* `ErgodicTheory.roofSum`: the signed (integer-indexed) Birkhoff sum `τ⁽ⁿ⁾` of the roof function along
  `T`, defined as the drop in the `ℝ`-coordinate under the `n`-th power of the generator.
* `ErgodicTheory.suspensionDomain`: the half-open box `{p | 0 ≤ p.2 ∧ p.2 < τ p.1}`.

## Main results

* `ErgodicTheory.roofSum_add`: the integer roof-cocycle identity, read off from
  `G ^ (m + n) = G ^ m * G ^ n`.
* `ErgodicTheory.exists_unique_lt_of_strictMono`: a pure real-analysis fact — a strictly monotone
  `ℤ`-indexed sequence tending to `±∞` partitions `ℝ` into half-open intervals.
* `ErgodicTheory.suspension_exists_unique_vadd_mem`: every orbit meets the box exactly once.
* `ErgodicTheory.isAddFundamentalDomain_suspensionDomain`: the box is a fundamental domain for the
  `ℤ`-action with respect to `μ.prod volume`.

## What is *not* in this file

The downstream construction — the invariant probability measure `μ̂` on `Xᵗ`, the
per-time measure-preservation of the suspension flow `ζ_t`, the packaging as a
`MeasurePreservingFlow`, and the exponent-transfer identity `λ_flow = λ_base / ∫ τ` — is left to
follow-up modules. Establishing those requires the `ℤ`-invariance of `μ.prod volume` (the
"shear preserves the product measure" lemma) and the descent of the `ℝ`-translation through the
quotient, neither of which is included here. This file deliberately stops at the
fundamental-domain keystone, which is self-contained and sorry-free.
-/

open MeasureTheory Filter Set
open scoped Topology

namespace ErgodicTheory

variable {X : Type*} [MeasurableSpace X]

/-- The generating measurable automorphism of the suspension `ℤ`-action:
`G (x, s) = (T x, s − τ x)`. Its inverse is `(x, s) ↦ (T⁻¹ x, s + τ (T⁻¹ x))`. -/
def suspensionGen (T : X ≃ᵐ X) {τ : X → ℝ} (hτ : Measurable τ) : (X × ℝ) ≃ᵐ (X × ℝ) where
  toFun p := (T p.1, p.2 - τ p.1)
  invFun p := (T.symm p.1, p.2 + τ (T.symm p.1))
  left_inv p := by simp
  right_inv p := by simp
  measurable_toFun :=
    (T.measurable.comp measurable_fst).prodMk
      (measurable_snd.sub (hτ.comp measurable_fst))
  measurable_invFun :=
    (T.symm.measurable.comp measurable_fst).prodMk
      (measurable_snd.add (hτ.comp (T.symm.measurable.comp measurable_fst)))

@[simp] theorem suspensionGen_apply (T : X ≃ᵐ X) {τ : X → ℝ} (hτ : Measurable τ) (p : X × ℝ) :
    suspensionGen T hτ p = (T p.1, p.2 - τ p.1) := rfl

@[simp] theorem suspensionGen_symm_apply (T : X ≃ᵐ X) {τ : X → ℝ} (hτ : Measurable τ)
    (p : X × ℝ) :
    (suspensionGen T hτ).symm p = (T.symm p.1, p.2 + τ (T.symm p.1)) := rfl

/-- The `ℤ`-action on `X × ℝ` generated by the suspension automorphism `suspensionGen`,
defined as `n +ᵥ p = ((suspensionGen) ^ n) p` via the `zpow` of the underlying permutation.
This is the suspension orbit relation: `(x, s)` is identified with `(T x, s − τ x)`.
The action laws `zero_vadd` and `add_vadd` are read off from `zpow_zero` and `zpow_add` in the
permutation group.

This is bundled as a `def` rather than a global `instance` because it depends on the data
`T` and `hτ`; it is activated locally (via `letI`) in the statements and proofs that use it.
The bundled `VAdd` is available as `(suspensionAddAction T hτ).toVAdd`. -/
@[reducible] def suspensionAddAction (T : X ≃ᵐ X) {τ : X → ℝ} (hτ : Measurable τ) :
    AddAction ℤ (X × ℝ) where
  vadd n p := ((suspensionGen T hτ).toEquiv ^ n) p
  zero_vadd p := by
    change ((suspensionGen T hτ).toEquiv ^ (0 : ℤ)) p = p
    rw [zpow_zero]; rfl
  add_vadd m n p := by
    change ((suspensionGen T hτ).toEquiv ^ (m + n)) p
      = ((suspensionGen T hτ).toEquiv ^ m) (((suspensionGen T hτ).toEquiv ^ n) p)
    rw [zpow_add]; rfl

section Action

variable (T : X ≃ᵐ X) {τ : X → ℝ} (hτ : Measurable τ)

/-- The underlying function of the suspension `ℤ`-action, written without typeclass notation:
`suspensionAct T hτ n p = ((suspensionGen) ^ n) p`. This agrees with the `+ᵥ` of
`suspensionAddAction` (see `suspension_vadd_eq_act`). Using a plain function lets the structural
lemmas be stated without activating the data-dependent `AddAction` instance. -/
def suspensionAct (n : ℤ) (p : X × ℝ) : X × ℝ := ((suspensionGen T hτ).toEquiv ^ n) p

theorem suspension_vadd_eq_act (n : ℤ) (p : X × ℝ) :
    (suspensionAddAction T hτ).toVAdd.vadd n p = suspensionAct T hτ n p := rfl

@[simp] theorem suspensionAct_zero (p : X × ℝ) : suspensionAct T hτ 0 p = p := by
  rw [suspensionAct, zpow_zero]; rfl

theorem suspensionAct_add (m n : ℤ) (p : X × ℝ) :
    suspensionAct T hτ (m + n) p = suspensionAct T hτ m (suspensionAct T hτ n p) := by
  rw [suspensionAct, suspensionAct, suspensionAct, zpow_add]; rfl

@[simp] theorem suspensionAct_one (p : X × ℝ) :
    suspensionAct T hτ 1 p = suspensionGen T hτ p := by
  rw [suspensionAct, zpow_one]; rfl

@[simp] theorem suspensionAct_neg_one (p : X × ℝ) :
    suspensionAct T hτ (-1) p = (suspensionGen T hτ).symm p := by
  rw [suspensionAct, zpow_neg_one]; rfl

/-- The signed (integer-indexed) Birkhoff sum `τ⁽ⁿ⁾` of the roof function `τ` along `T`,
defined as the *drop* in the `ℝ`-coordinate produced by `suspensionAct n`. For `n ≥ 0` this is
the ordinary Birkhoff sum `τ x + τ (T x) + … + τ (Tⁿ⁻¹ x)`; for `n < 0` it is its backward
counterpart with a sign. -/
def roofSum (n : ℤ) (x : X) : ℝ := -(suspensionAct T hτ n (x, (0 : ℝ))).2

/-- The first coordinate of `suspensionAct n (x, s)`, i.e. the `n`-th `ℤ`-iterate of `T` applied
to `x`. It is independent of the `ℝ`-coordinate `s`. -/
def baseIter (n : ℤ) (x : X) : X := (suspensionAct T hτ n (x, (0 : ℝ))).1

/-- Structural form of the action: `suspensionAct n (x, s) = (baseIter n x, s − roofSum n x)`.
The action translates the `ℝ`-coordinate by `−roofSum n x`, a quantity independent of `s`, and
moves the `X`-coordinate by the `ℤ`-iterate of `T`. -/
theorem suspensionAct_eq (n : ℤ) (x : X) (s : ℝ) :
    suspensionAct T hτ n (x, s) = (baseIter T hτ n x, s - roofSum T hτ n x) := by
  induction n using Int.induction_on with
  | zero => simp [baseIter, roofSum]
  | succ k ih =>
    have hadd : suspensionAct T hτ ((k : ℤ) + 1) (x, s)
        = suspensionAct T hτ 1 (suspensionAct T hτ (k : ℤ) (x, s)) := by
      rw [add_comm, suspensionAct_add]
    have hadd0 : suspensionAct T hτ ((k : ℤ) + 1) (x, (0 : ℝ))
        = suspensionAct T hτ 1 (suspensionAct T hτ (k : ℤ) (x, (0 : ℝ))) := by
      rw [add_comm, suspensionAct_add]
    rw [hadd, ih, suspensionAct_one, suspensionGen_apply]
    simp only [baseIter, roofSum, hadd0, suspensionAct_one, suspensionGen_apply]
    ring_nf
  | pred k ih =>
    have hadd : suspensionAct T hτ (-(k : ℤ) - 1) (x, s)
        = suspensionAct T hτ (-1) (suspensionAct T hτ (-(k : ℤ)) (x, s)) := by
      rw [sub_eq_add_neg, add_comm, suspensionAct_add]
    have hadd0 : suspensionAct T hτ (-(k : ℤ) - 1) (x, (0 : ℝ))
        = suspensionAct T hτ (-1) (suspensionAct T hτ (-(k : ℤ)) (x, (0 : ℝ))) := by
      rw [sub_eq_add_neg, add_comm, suspensionAct_add]
    rw [hadd, ih, suspensionAct_neg_one, suspensionGen_symm_apply]
    simp only [baseIter, roofSum, hadd0, suspensionAct_neg_one, suspensionGen_symm_apply]
    ring_nf

theorem suspensionAct_snd (n : ℤ) (x : X) (s : ℝ) :
    (suspensionAct T hτ n (x, s)).2 = s - roofSum T hτ n x := by rw [suspensionAct_eq]

theorem suspensionAct_fst (n : ℤ) (x : X) (s : ℝ) :
    (suspensionAct T hτ n (x, s)).1 = baseIter T hτ n x := by rw [suspensionAct_eq]

@[simp] theorem roofSum_zero (x : X) : roofSum T hτ 0 x = 0 := by simp [roofSum]

/-- The roof-cocycle step: `τ⁽ⁿ⁺¹⁾ x = τ⁽ⁿ⁾ x + τ (Tⁿ x)`, where `Tⁿ x = baseIter n x`. -/
theorem roofSum_add_one (n : ℤ) (x : X) :
    roofSum T hτ (n + 1) x = roofSum T hτ n x + τ (baseIter T hτ n x) := by
  have h : suspensionAct T hτ (n + 1) (x, (0 : ℝ))
      = suspensionGen T hτ (suspensionAct T hτ n (x, (0 : ℝ))) := by
    rw [add_comm, suspensionAct_add, suspensionAct_one]
  simp only [roofSum, baseIter, h, suspensionGen_apply]
  ring

variable {c : ℝ}

/-- With `inf τ ≥ c > 0`, the roof sum strictly increases in the integer index. -/
theorem strictMono_roofSum (hc : ∀ x, c ≤ τ x) (hcpos : 0 < c) (x : X) :
    StrictMono (fun n : ℤ => roofSum T hτ n x) :=
  strictMono_int_of_lt_succ fun n => by
    rw [roofSum_add_one]
    have := hc (baseIter T hτ n x)
    linarith

/-- Telescoping lower bound: for `0 ≤ n`, the roof sum is at least `c * n`. -/
theorem roofSum_ge (hc : ∀ x, c ≤ τ x) (x : X) (n : ℕ) :
    c * n ≤ roofSum T hτ (n : ℤ) x := by
  induction n with
  | zero => simp
  | succ k ih =>
    have hstep := hc (baseIter T hτ (k : ℤ) x)
    have hrec : roofSum T hτ ((k : ℤ) + 1) x
        = roofSum T hτ (k : ℤ) x + τ (baseIter T hτ (k : ℤ) x) :=
      roofSum_add_one T hτ (k : ℤ) x
    rw [show ((k + 1 : ℕ) : ℤ) = (k : ℤ) + 1 by push_cast; ring, hrec]
    push_cast
    push_cast at ih
    linarith

/-- Telescoping upper bound: for `n ≤ 0`, the roof sum is at most `c * n` (a negative quantity). -/
theorem roofSum_le_of_nonpos (hc : ∀ x, c ≤ τ x) (x : X) (n : ℕ) :
    roofSum T hτ (-(n : ℤ)) x ≤ c * (-(n : ℤ)) := by
  induction n with
  | zero => simp
  | succ k ih =>
    have hstep := hc (baseIter T hτ (-((k : ℤ) + 1)) x)
    have hrec : roofSum T hτ (-(k : ℤ)) x
        = roofSum T hτ (-((k : ℤ) + 1)) x + τ (baseIter T hτ (-((k : ℤ) + 1)) x) := by
      have h := roofSum_add_one T hτ (-((k : ℤ) + 1)) x
      rw [show (-((k : ℤ) + 1) + 1) = -(k : ℤ) by ring] at h
      linarith
    rw [show (-(↑(k + 1) : ℤ)) = -((k : ℤ) + 1) by push_cast; ring]
    push_cast at ih ⊢
    linarith

theorem tendsto_roofSum_atTop (hc : ∀ x, c ≤ τ x) (hcpos : 0 < c) (x : X) :
    Tendsto (fun n : ℤ => roofSum T hτ n x) atTop atTop := by
  have hlin : Tendsto (fun n : ℤ => c * (n : ℝ)) atTop atTop :=
    Tendsto.const_mul_atTop hcpos tendsto_intCast_atTop_atTop
  apply tendsto_atTop_mono' atTop _ hlin
  filter_upwards [eventually_ge_atTop 0] with n hn
  lift n to ℕ using hn with m
  exact_mod_cast roofSum_ge T hτ hc x m

theorem tendsto_roofSum_atBot (hc : ∀ x, c ≤ τ x) (hcpos : 0 < c) (x : X) :
    Tendsto (fun n : ℤ => roofSum T hτ n x) atBot atBot := by
  have hlin : Tendsto (fun n : ℤ => c * (n : ℝ)) atBot atBot :=
    Tendsto.const_mul_atBot hcpos (tendsto_intCast_atBot_iff.2 tendsto_id)
  apply tendsto_atBot_mono' atBot _ hlin
  filter_upwards [eventually_le_atBot 0] with n hn
  lift -n to ℕ using (by omega : 0 ≤ -n) with m hm
  have := roofSum_le_of_nonpos T hτ hc x m
  rw [hm] at this
  simpa using this

end Action

section Partition

/-- A strictly monotone `ℤ`-indexed real sequence tending to `+∞` along `atTop` and to `−∞`
along `atBot` partitions `ℝ` into the half-open intervals `[a n, a (n+1))`: every real `s` lies
in exactly one of them. This is the pure real-analysis core of the suspension fundamental-domain
result. -/
theorem exists_unique_lt_of_strictMono {a : ℤ → ℝ} (hmono : StrictMono a)
    (htop : Tendsto a atTop atTop) (hbot : Tendsto a atBot atBot) (s : ℝ) :
    ∃! n : ℤ, a n ≤ s ∧ s < a (n + 1) := by
  -- The set of indices `n` with `a n ≤ s` is nonempty (as `a → -∞`) and bounded above
  -- (as `a → +∞`); its greatest element is the desired index.
  have hinh : ∃ z : ℤ, a z ≤ s := by
    obtain ⟨z, hz⟩ := (tendsto_atBot_atBot.1 hbot) s
    exact ⟨z, hz z le_rfl⟩
  have hbdd : ∃ b : ℤ, ∀ z : ℤ, a z ≤ s → z ≤ b := by
    obtain ⟨b, hb⟩ := (tendsto_atTop_atTop.1 htop) (s + 1)
    refine ⟨b, fun z hz => ?_⟩
    by_contra hzb
    push Not at hzb
    have : s + 1 ≤ a z := le_trans (hb b le_rfl) (hmono.monotone hzb.le)
    linarith
  obtain ⟨n, hn, hmax⟩ := Int.exists_greatest_of_bdd hbdd hinh
  refine ⟨n, ⟨hn, ?_⟩, ?_⟩
  · by_contra hlt
    push Not at hlt
    have : n + 1 ≤ n := hmax (n + 1) hlt
    omega
  · rintro m ⟨hm1, hm2⟩
    -- `m` also maximizes: `a m ≤ s` so `m ≤ n`; and `s < a (m+1)` with `a n ≤ s` forces `n ≤ m`.
    have hmn : m ≤ n := hmax m hm1
    have hnm : n ≤ m := by
      by_contra hnm
      push Not at hnm
      have hle : m + 1 ≤ n := by omega
      have : a (m + 1) ≤ a n := hmono.monotone hle
      linarith
    omega

end Partition

section FundamentalDomain

variable (T : X ≃ᵐ X) {τ : X → ℝ} (hτ : Measurable τ)

/-- The half-open *box under the roof*, `{p : X × ℝ | 0 ≤ p.2 ∧ p.2 < τ p.1}`. It is the
Ambrose–Kakutani cross-section of the suspension and a fundamental domain for the suspension
`ℤ`-action with respect to `μ × volume`. -/
def suspensionDomain (τ : X → ℝ) : Set (X × ℝ) := {p | 0 ≤ p.2 ∧ p.2 < τ p.1}

include hτ in
theorem measurableSet_suspensionDomain : MeasurableSet (suspensionDomain τ) := by
  have h1 : MeasurableSet {p : X × ℝ | 0 ≤ p.2} :=
    measurableSet_le measurable_const measurable_snd
  have h2 : MeasurableSet {p : X × ℝ | p.2 < τ p.1} :=
    measurableSet_lt measurable_snd (hτ.comp measurable_fst)
  exact h1.inter h2

/-- Membership of `suspensionAct n (x, s)` in the box is equivalent to the half-open interval
condition `roofSum n x ≤ s < roofSum (n+1) x`. -/
theorem suspensionAct_mem_domain_iff (n : ℤ) (x : X) (s : ℝ) :
    suspensionAct T hτ n (x, s) ∈ suspensionDomain τ
      ↔ roofSum T hτ n x ≤ s ∧ s < roofSum T hτ (n + 1) x := by
  rw [suspensionDomain, mem_setOf_eq, suspensionAct_snd, suspensionAct_fst,
    roofSum_add_one]
  constructor
  · rintro ⟨h1, h2⟩; exact ⟨by linarith, by linarith⟩
  · rintro ⟨h1, h2⟩; exact ⟨by linarith, by linarith⟩

/-- **Every orbit meets the box exactly once.** For each `(x, s)` there is a unique integer `n`
with `suspensionAct n (x, s)` in the half-open box. This is the heart of the fundamental-domain
property; it follows from the half-open-interval partition `exists_unique_lt_of_strictMono`
applied to the strictly increasing, two-sided-unbounded sequence `n ↦ roofSum n x`. -/
theorem suspension_exists_unique_act_mem {c : ℝ} (hc : ∀ x, c ≤ τ x) (hcpos : 0 < c)
    (x : X) (s : ℝ) :
    ∃! n : ℤ, suspensionAct T hτ n (x, s) ∈ suspensionDomain τ := by
  simp only [suspensionAct_mem_domain_iff]
  exact exists_unique_lt_of_strictMono (strictMono_roofSum T hτ hc hcpos x)
    (tendsto_roofSum_atTop T hτ hc hcpos x) (tendsto_roofSum_atBot T hτ hc hcpos x) s

/-- **The box is a fundamental domain.** With `inf τ ≥ c > 0` and `T` measure-preserving, the
half-open box `suspensionDomain τ` is a fundamental domain for the suspension `ℤ`-action on
`X × ℝ` with respect to `μ × volume`. This is the Ambrose–Kakutani cross-section structure of
the suspension.

The action is the locally-activated `suspensionAddAction T hτ`; the statement uses `letI` to
bring its `VAdd` instance into scope. The proof is `IsAddFundamentalDomain.mk'`, whose sole
content is the exactly-once meeting `suspension_exists_unique_act_mem`. -/
theorem isAddFundamentalDomain_suspensionDomain {μ : MeasureTheory.Measure X}
    {c : ℝ} (hc : ∀ x, c ≤ τ x) (hcpos : 0 < c) :
    letI := (suspensionAddAction T hτ).toVAdd
    IsAddFundamentalDomain ℤ (suspensionDomain τ) (μ.prod MeasureTheory.volume) := by
  letI := suspensionAddAction T hτ
  refine IsAddFundamentalDomain.mk' (measurableSet_suspensionDomain hτ).nullMeasurableSet ?_
  intro p
  obtain ⟨x, s⟩ := p
  simpa only [suspension_vadd_eq_act] using
    suspension_exists_unique_act_mem T hτ hc hcpos x s

end FundamentalDomain

end ErgodicTheory
