/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import ErgodicTheory.TwoSided.Invertible
import ErgodicTheory.Cocycle.FurstenbergKesten
import ErgodicTheory.Continuous.Suspension

/-!
# The two-sided ℤ-indexed linear cocycle over an invertible base

Over an **invertible** measure-preserving base `T : X ≃ᵐ X`, the one-sided iterated matrix cocycle
`ErgodicTheory.cocycle` (indexed by `ℕ`) extends to a genuine **two-sided ℤ-indexed cocycle**
`ErgodicTheory.cocycleZ`: for `n ≥ 0` it is the forward cocycle `cocycle A T n`, and for `n < 0`
it is the backward cocycle `cocycle (backwardGen A T) T.symm (-n)`, where `backwardGen A T x =
(A (T.symm x))⁻¹` is the generator of the inverse dynamics (`ErgodicTheory.TwoSided.Invertible`).

This is the discrete-time skeleton of the special (suspension) flow cocycle: the flow of the
mapping torus advances a continuous height coordinate, and reading off *how many base laps* have
been completed produces a signed integer count `⌊s + t⌋`, at which the matrix accumulated by the
flow is exactly `cocycleZ A T ⌊s + t⌋`. The uniform one-step recurrences `cocycleZ_add_one` /
`cocycleZ_sub_one` and the **keystone** two-sided cocycle identity `cocycleZ_add`
(`cocycleZ (m + n) x = cocycleZ m (baseIter n x) * cocycleZ n x`, with `baseIter` the ℤ-iterate of
the base from `ErgodicTheory.Continuous.Suspension`) are what let this discrete object assemble into
a continuous-time `FlowCocycle` on the constant-roof suspension
(`ErgodicTheory.Continuous.QuotientFlowCocycle`).

## Main definitions

* `ErgodicTheory.cocycleZ`: the two-sided ℤ-indexed matrix cocycle.

## Main results

* `ErgodicTheory.cocycleZ_natCast` / `cocycleZ_neg`: evaluation at `± (n : ℕ)`.
* `ErgodicTheory.cocycleZ_zero`: `cocycleZ 0 = 1`.
* `ErgodicTheory.cocycleZ_det_ne_zero`: every `cocycleZ` matrix is invertible (under `det A ≠ 0`).
* `ErgodicTheory.measurable_cocycleZ`: measurability of each time slice.
* `ErgodicTheory.cocycleZ_add_one` / `cocycleZ_sub_one`: the uniform one-step recurrences.
* `ErgodicTheory.cocycleZ_add`: the **keystone** two-sided cocycle identity.
-/

open MeasureTheory

namespace ErgodicTheory

variable {X : Type*} [MeasurableSpace X] {d : ℕ}

/-! ## The two-sided ℤ-cocycle `cocycleZ` -/

/-- The **two-sided ℤ-indexed cocycle** over an invertible base `T`: for `n ≥ 0` it is the forward
cocycle `cocycle A T n`, and for `n < 0` it is the backward cocycle
`cocycle (backwardGen A T) T.symm (-n)` generated by the inverse dynamics. -/
noncomputable def cocycleZ (A : X → Matrix (Fin d) (Fin d) ℝ) (T : X ≃ᵐ X) :
    ℤ → X → Matrix (Fin d) (Fin d) ℝ :=
  fun n x => if 0 ≤ n then cocycle A (⇑T) n.toNat x
    else cocycle (backwardGen A T) (⇑T.symm) (-n).toNat x

variable {A : X → Matrix (Fin d) (Fin d) ℝ} {T : X ≃ᵐ X}

/-- Evaluation at a natural index: `cocycleZ A T (n : ℤ) = cocycle A T n`. -/
theorem cocycleZ_natCast (n : ℕ) (x : X) :
    cocycleZ A T (n : ℤ) x = cocycle A (⇑T) n x := by
  unfold cocycleZ
  rw [if_pos (Int.natCast_nonneg n), Int.toNat_natCast]

/-- Evaluation at a negated natural index: `cocycleZ A T (-(n : ℤ)) = cocycle (backwardGen A T)
T.symm n`. -/
theorem cocycleZ_neg (n : ℕ) (x : X) :
    cocycleZ A T (-(n : ℤ)) x = cocycle (backwardGen A T) (⇑T.symm) n x := by
  rcases Nat.eq_zero_or_pos n with rfl | h
  · simp [cocycleZ]
  · have hlt : ¬ (0 : ℤ) ≤ -(n : ℤ) := by omega
    unfold cocycleZ
    rw [if_neg hlt, neg_neg, Int.toNat_natCast]

/-- `cocycleZ 0 = 1`. -/
theorem cocycleZ_zero (x : X) : cocycleZ A T 0 x = 1 := by
  have := cocycleZ_natCast (A := A) (T := T) 0 x
  simpa using this

/-- The determinant of every `cocycleZ` matrix is nonzero (under global base invertibility). -/
theorem cocycleZ_det_ne_zero (hA : ∀ x, (A x).det ≠ 0) (n : ℤ) (x : X) :
    (cocycleZ A T n x).det ≠ 0 := by
  unfold cocycleZ
  split_ifs with h
  · exact det_cocycle_ne_zero (T := ⇑T) hA n.toNat x
  · exact det_cocycle_ne_zero (T := ⇑T.symm) (backwardGen_det_ne_zero hA T) (-n).toNat x

/-- Measurability of each time slice `cocycleZ A T n`. -/
theorem measurable_cocycleZ (hmeas : Measurable A) (n : ℤ) :
    Measurable (cocycleZ A T n) := by
  unfold cocycleZ
  split_ifs with h
  · exact measurable_cocycle hmeas T.measurable n.toNat
  · exact measurable_cocycle (measurable_backwardGen hmeas T) T.symm.measurable (-n).toNat

/-! ### One-step recurrences (the engine of the keystone) -/

/-- Forward one-step recurrence, uniform in `n : ℤ` (newest factor on the left):
`cocycleZ (n + 1) x = cocycleZ n (T x) * A x`. -/
theorem cocycleZ_add_one (hA : ∀ x, (A x).det ≠ 0) (n : ℤ) (x : X) :
    cocycleZ A T (n + 1) x = cocycleZ A T n (T x) * A x := by
  by_cases h : 0 ≤ n
  · lift n to ℕ using h with k
    rw [show (k : ℤ) + 1 = ((k + 1 : ℕ) : ℤ) by push_cast; ring,
      cocycleZ_natCast, cocycleZ_natCast, cocycle_succ]
  · obtain ⟨m, hmn⟩ : ∃ m : ℕ, n = -((m : ℤ) + 1) := ⟨(-n).toNat - 1, by omega⟩
    subst hmn
    rw [show -((m : ℤ) + 1) + 1 = -((m : ℕ) : ℤ) by ring,
      show -((m : ℤ) + 1) = -(((m + 1 : ℕ)) : ℤ) by push_cast; ring,
      cocycleZ_neg, cocycleZ_neg, cocycle_succ]
    have hb : backwardGen A T ((⇑T) x) = (A x)⁻¹ := by
      rw [backwardGen, T.symm_apply_apply]
    rw [hb, T.symm_apply_apply, mul_assoc, Matrix.nonsing_inv_mul _ (Ne.isUnit (hA x)), mul_one]

/-- Backward one-step recurrence, uniform in `n : ℤ`:
`cocycleZ (n - 1) x = cocycleZ n (T.symm x) * (A (T.symm x))⁻¹`. -/
theorem cocycleZ_sub_one (hA : ∀ x, (A x).det ≠ 0) (n : ℤ) (x : X) :
    cocycleZ A T (n - 1) x = cocycleZ A T n (T.symm x) * (A (T.symm x))⁻¹ := by
  by_cases h : 1 ≤ n
  · obtain ⟨k, hk⟩ : ∃ k : ℕ, n = (k : ℤ) + 1 := ⟨(n - 1).toNat, by omega⟩
    subst hk
    rw [show (k : ℤ) + 1 - 1 = ((k : ℕ) : ℤ) by ring,
      show (k : ℤ) + 1 = ((k + 1 : ℕ) : ℤ) by push_cast; ring,
      cocycleZ_natCast, cocycleZ_natCast, cocycle_succ, T.apply_symm_apply, mul_assoc,
      Matrix.mul_nonsing_inv _ (Ne.isUnit (hA _)), mul_one]
  · obtain ⟨m, hmn⟩ : ∃ m : ℕ, n = -((m : ℤ)) := ⟨(-n).toNat, by omega⟩
    subst hmn
    rw [show -((m : ℤ)) - 1 = -(((m + 1 : ℕ)) : ℤ) by push_cast; ring,
      cocycleZ_neg, cocycleZ_neg, cocycle_succ]
    congr 1

/-! ### The base ℤ-iterate `baseIter` recurrences -/

variable {τ : X → ℝ} (hτ : Measurable τ)

/-- `baseIter 0 x = x`. -/
theorem baseIter_zero (x : X) : baseIter T hτ 0 x = x := by
  simp [baseIter]

/-- `baseIter (n + 1) x = baseIter n (T x)`. -/
theorem baseIter_succ' (n : ℤ) (x : X) :
    baseIter T hτ (n + 1) x = baseIter T hτ n (⇑T x) := by
  have h : suspensionAct T hτ (n + 1) (x, (0 : ℝ))
      = suspensionAct T hτ n (suspensionGen T hτ (x, (0 : ℝ))) := by
    rw [suspensionAct_add T hτ n 1, suspensionAct_one]
  unfold baseIter
  rw [h, suspensionGen_apply, suspensionAct_fst, suspensionAct_fst]

/-- `baseIter (n - 1) x = baseIter n (T.symm x)`. -/
theorem baseIter_pred' (n : ℤ) (x : X) :
    baseIter T hτ (n - 1) x = baseIter T hτ n (⇑T.symm x) := by
  have h : suspensionAct T hτ (n - 1) (x, (0 : ℝ))
      = suspensionAct T hτ n ((suspensionGen T hτ).symm (x, (0 : ℝ))) := by
    rw [sub_eq_add_neg, suspensionAct_add T hτ n (-1), suspensionAct_neg_one]
  unfold baseIter
  rw [h, suspensionGen_symm_apply, suspensionAct_fst, suspensionAct_fst]

/-! ### The keystone : the ℤ-cocycle identity -/

/-- **The two-sided cocycle identity**
`cocycleZ (m + n) x = cocycleZ m (baseIter n x) * cocycleZ n x`, with `baseIter` the ℤ-iterate of
the base map. Proved by `Int.induction_on` on `n` (generalizing `x`), using the one-step
recurrences `cocycleZ_add_one` / `cocycleZ_sub_one` and the base recurrences
`baseIter_succ'` / `baseIter_pred'`. -/
theorem cocycleZ_add (hA : ∀ x, (A x).det ≠ 0) (m n : ℤ) (x : X) :
    cocycleZ A T (m + n) x = cocycleZ A T m (baseIter T hτ n x) * cocycleZ A T n x := by
  induction n using Int.induction_on generalizing x with
  | zero => rw [add_zero, baseIter_zero, cocycleZ_zero, mul_one]
  | succ k ih =>
    have key : m + ((k : ℤ) + 1) = (m + (k : ℤ)) + 1 := by ring
    rw [key, cocycleZ_add_one hA, ih (T x), mul_assoc,
      ← cocycleZ_add_one hA, ← baseIter_succ' hτ (k : ℤ) x]
  | pred k ih =>
    have key : m + (-(k : ℤ) - 1) = (m + -(k : ℤ)) - 1 := by ring
    rw [key, cocycleZ_sub_one hA, ih (T.symm x), mul_assoc,
      ← cocycleZ_sub_one hA, ← baseIter_pred' hτ (-(k : ℤ)) x]

end ErgodicTheory
