/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import ErgodicTheory.OperatorEntropy.GrowingTower.Tower
import ErgodicTheory.OperatorEntropy.GrowingTower.ChainAlgebra
import ErgodicTheory.OperatorEntropy.GrowingTower.ChainState
import ErgodicTheory.OperatorEntropy.GrowingTower.ModularClock
import ErgodicTheory.OperatorEntropy.GrowingTower.SealLift
import ErgodicTheory.OperatorEntropy.GrowingTower.World

/-!
# The quantum Bernoulli shift on the growing qubit chain (issue #71, tier 2)

This module assembles the **quantum Bernoulli shift** of the one-sided qubit chain in the
*directed-local* (growing-finite) representation and extracts its honest **temporal entropy rate**.
The setting is the fixed hierarchy of finite marginals built in the sibling modules: the carriers
`Qbits n` (of cardinality `2 ^ n`, the local algebras `M_{2ⁿ}`), the tracial (maximally mixed)
state at every level, the commuting **inclusion** `appendQubit` (`x ↦ x ⊗ 1`, far-end site) and
**shift** `shiftAdjoinQubit` (`A ↦ 1 ⊗ A`, capacity enlargement) of `ChainAlgebra.lean`, and the
shift-invariance pairing of `ChainState.lean`.

## Contents

* `shiftIter` — the `k`-fold shift `A_n ↪ A_{n+k}`, together with its equation lemmas
  (`shiftIter_zero`, `shiftIter_succ`) and the unital `*`-homomorphism / injectivity laws
  (`shiftIter_one`, `shiftIter_mul`, `shiftIter_star`, `shiftIter_injective`).
* `shiftIter_pairing` — the **site-translation certificate**: the fixed tracial state, read
  through `k` shift-iterates of a level-`n` observable, returns the level-`n` marginal.  This is
  the temporal stationarity ("the past slides out") of the quantum Bernoulli shift.
* `windowEntropy`, `windowEntropy_tracial`, `tendsto_windowEntropy_div_tracial` — the **temporal
  rate along the shift-window filtration**: the length-`k` window of the chain is generated by the
  first `k` sites, and the rate equals `log 2`.
* `ChainSealed`, `chain_seal_dephase_faithful` — the **per-stage dephasing seal at the tracial
  blocks**: dephasing site `0` of the chain admits no faithful-ancilla Stinespring recovery, at
  every level.
* `QuantumBernoulliShift`, `quantumBernoulliShift_exists` — the **headline bundle**: the directed
  system (commuting inclusion and shift), the tracial state (inclusion- and shift-compatible), the
  temporal rate `log 2`, the per-stage seal, and the trivial tracial modular clock, packaged as one
  certificate together with a concrete witness.

## The reading: aliveness by forgetting on a fixed object

Where the spatial rate of `Tower.lean`/`World.lean` (issue #70) comes from *enlarging* the algebra
one qubit per step, the temporal rate here comes from **forgetting on a fixed hierarchy**: the
tracial marginals are held fixed and shift-invariant (`shiftIter_pairing`), and the window
filtration slides along the shift.  Numerically `windowEntropy = blockEntropy` (disclosure (b)
below); the temporal content is the *fixed* state hierarchy, its shift-invariance, and the window
filtration — not the number.  The modular clock is trivial at the tracial state (the type II₁
shadow, `modAut_maximallyMixed_Qbits_eq_id`) and provably nontrivial at a non-tracial product state
(`modAut_diagState_ne_id`, `ModularClock.lean`).

## Disclosures (honest scope)

(a) The completed C\*-algebra `⊗_{ℤ} M₂` and its GNS representation are **not** constructed:
Mathlib has no noncommutative inductive limit (`Ring.DirectLimit` is `CommRing`-only).  What is
formed is the directed system of finite levels with compatible tracial marginals and commuting
inclusion/shift — the issue's blessed "cheaper first cut".

(b) `windowEntropy` is numerically the block entropy of issue #70 (`windowEntropy_eq_blockEntropy`);
the temporal content is the fixed state hierarchy, its shift-invariance, and the window filtration,
not the numerical value.

(c) The rate `tendsto_windowEntropy_div_tracial` is the **site-window filtration rate**, a bespoke
CNT-style definition, **not** the full CNT entropy (a supremum over *all* finite subalgebras).

(d) Tomita–Takesaki uniqueness and the genuine type-III structure of the completed chain are not
formalized; the modular data here is the finite matrix-algebra shadow (`ModularClock.lean`).

## Sources

* Connes–Narnhofer–Thirring, *Dynamical entropy of C\* algebras and von Neumann algebras*,
  Comm. Math. Phys. **112** (1987) 691–719 (shift entropy `= log 2 =` entropy density);
* Bratteli–Robinson, *Operator Algebras and Quantum Statistical Mechanics II*, §5.3;
* Ohya–Petz, *Quantum Entropy and Its Use*, Springer;
* R. T. Powers, *Representations of uniformly hyperfinite algebras and their associated von Neumann
  rings*, Ann. of Math. **86** (1967).
-/

open Matrix Real
open scoped ComplexOrder Kronecker

noncomputable section

namespace ErgodicTheory.OperatorEntropy

/-! ## The iterated shift `A_n ↪ A_{n+k}` -/

/-- The **`k`-fold shift** `A_n ↪ A_{n+k}`, iterating the capacity-enlargement embedding
`shiftAdjoinQubit` (`A ↦ 1 ⊗ A`) `k` times.  The carrier `Qbits (n + (k+1))` is definitionally
`Fin 2 × Qbits (n + k)`, so the recursion typechecks without casts. -/
def shiftIter {n : ℕ} :
    (k : ℕ) → Matrix (Qbits n) (Qbits n) ℂ → Matrix (Qbits (n + k)) (Qbits (n + k)) ℂ
  | 0, M => M
  | (k + 1), M => shiftAdjoinQubit (shiftIter k M)

/-- Zero iterations of the shift is the identity map. -/
theorem shiftIter_zero {n : ℕ} (M : Matrix (Qbits n) (Qbits n) ℂ) : shiftIter 0 M = M := rfl

/-- The recursive step: `shiftIter (k+1) = shiftAdjoinQubit ∘ shiftIter k`. -/
theorem shiftIter_succ {n : ℕ} (k : ℕ) (M : Matrix (Qbits n) (Qbits n) ℂ) :
    shiftIter (k + 1) M = shiftAdjoinQubit (shiftIter k M) := rfl

/-- The iterated shift maps the identity to the identity. -/
theorem shiftIter_one {n : ℕ} (k : ℕ) :
    shiftIter k (1 : Matrix (Qbits n) (Qbits n) ℂ) = 1 := by
  induction k with
  | zero => rfl
  | succ j ih => rw [shiftIter_succ, ih, shiftAdjoinQubit_one]

/-- The iterated shift is multiplicative. -/
theorem shiftIter_mul {n : ℕ} (k : ℕ) (M N : Matrix (Qbits n) (Qbits n) ℂ) :
    shiftIter k (M * N) = shiftIter k M * shiftIter k N := by
  induction k with
  | zero => rfl
  | succ j ih =>
      rw [shiftIter_succ, ih, shiftAdjoinQubit_mul, ← shiftIter_succ, ← shiftIter_succ]

/-- The iterated shift commutes with the conjugate transpose. -/
theorem shiftIter_star {n : ℕ} (k : ℕ) (M : Matrix (Qbits n) (Qbits n) ℂ) :
    (shiftIter k M)ᴴ = shiftIter k Mᴴ := by
  induction k with
  | zero => rfl
  | succ j ih => rw [shiftIter_succ, shiftAdjoinQubit_star, ih, ← shiftIter_succ]

/-- The iterated shift is injective. -/
theorem shiftIter_injective {n : ℕ} (k : ℕ) :
    Function.Injective (shiftIter (n := n) k) := by
  induction k with
  | zero => exact fun M N h => h
  | succ j ih =>
      intro M N h
      rw [shiftIter_succ, shiftIter_succ] at h
      exact ih (shiftAdjoinQubit_injective _ h)

/-! ## The site-translation certificate (temporal stationarity) -/

/-- **The site-translation certificate.** The fixed state `rhoPow ρ`, read through `k`
shift-iterates of a level-`n` observable `x`, returns the level-`n` marginal:
`τ_{n+k}(shiftIter k x) = τ_n(x)`, where `τ_m(y) := trace ((rhoPow ρ m).val * y)`.  This is the
shift-invariance of the whole hierarchy — the temporal stationarity of the quantum Bernoulli shift
("the past slides out"): a level-`n` observable, however far the shift carries its window, is still
evaluated by the level-`n` state. -/
theorem shiftIter_pairing (ρ : DensityMatrix (Fin 2)) (n k : ℕ)
    (x : Matrix (Qbits n) (Qbits n) ℂ) :
    ((rhoPow ρ (n + k)).val * shiftIter k x).trace = ((rhoPow ρ n).val * x).trace := by
  induction k with
  | zero => rfl
  | succ j ih =>
      have key := rhoPow_shiftAdjoinQubit_pairing ρ (n + j) (shiftIter j x)
      exact key.trans ih

/-! ## The temporal rate along the shift-window filtration -/

/-- **The temporal window entropy.** The von Neumann entropy of the length-`k` window of the chain,
generated by the first `k` sites.  Numerically this is the block entropy of issue #70
(`windowEntropy_eq_blockEntropy`); the temporal content is the *reading* — the window of the shift
filtration on the fixed, shift-invariant state hierarchy (`shiftIter_pairing`), not the number. -/
noncomputable def windowEntropy (ρ : DensityMatrix (Fin 2)) (k : ℕ) : ℝ := blockEntropy ρ k

/-- The window entropy is, numerically, the block entropy of `Tower.lean` (issue #70): the temporal
content is the fixed state hierarchy and the shift-window filtration, not the value (disclosure
(b)). -/
theorem windowEntropy_eq_blockEntropy (ρ : DensityMatrix (Fin 2)) (k : ℕ) :
    windowEntropy ρ k = blockEntropy ρ k := rfl

/-- **The tracial window entropy.** At the tracial (maximally mixed) state the length-`k` window
carries entropy `k · log 2`. -/
theorem windowEntropy_tracial (k : ℕ) :
    windowEntropy DensityMatrix.maximallyMixed k = k * Real.log 2 := by
  rw [windowEntropy, blockEntropy_maximallyMixed]

/-- **The temporal entropy rate is `log 2`.** The per-window rate `windowEntropy k / k` is the
constant `log 2` for every `k ≥ 1`, hence converges to `log 2`.  This is the site-window rate of
the quantum Bernoulli shift at the tracial state (disclosure (c): a bespoke CNT-style window rate,
not the full CNT supremum). -/
theorem tendsto_windowEntropy_div_tracial :
    Filter.Tendsto (fun k => windowEntropy DensityMatrix.maximallyMixed k / k)
      Filter.atTop (nhds (Real.log 2)) := by
  refine Filter.Tendsto.congr' ?_ tendsto_const_nhds
  filter_upwards [Filter.eventually_ge_atTop 1] with k hk
  have hk0 : (k : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (by omega)
  rw [windowEntropy_tracial, mul_comm, mul_div_assoc, div_self hk0, mul_one]

/-! ## The per-stage dephasing seal at the tracial blocks -/

/-- **The per-stage dephasing-seal predicate at the tracial blocks.** For the faithful local state
`ρ_r` and diagonal reference `diagState s`: at every level `n`, the partial-dephasing channel
on `M₂ ⊗ M_{2ⁿ}` admits no faithful-ancilla Stinespring recovery that simultaneously inverts it on
the coherent state `ρ_r ⊗ mm` and on the reference `diagState s ⊗ mm`, where the block is the
tracial (maximally mixed) block state.  This is the chain-level, per-stage (channel-level) seal at
the
tracial blocks; it mirrors the caveats of `SealLift.lean` (single-step per stage, not a flow seal;
the recovery is quantified over all faithful-ancilla Stinespring dilations). -/
def ChainSealed (r : ℝ) (hr0 : 0 < r) (hr1 : r < 1) (s : ℝ) (hs0 : 0 < s) (hs1 : s < 1) :
    Prop :=
  ∀ (n : ℕ) {e : Type} [Fintype e] [DecidableEq e]
    (α : DensityMatrix e)
    (U : Matrix.unitaryGroup ((Fin 2 × Qbits n) × e) ℂ), α.val.PosDef →
    ((((dephaseKronId (Qbits n)).toDM ((rhoR r hr0 hr1).kron
          (DensityMatrix.maximallyMixed : DensityMatrix (Qbits n)))).kron α).conj
        U).partialTraceRight
      = (rhoR r hr0 hr1).kron (DensityMatrix.maximallyMixed : DensityMatrix (Qbits n)) →
    ((((dephaseKronId (Qbits n)).toDM ((diagState s hs0 hs1).kron
          (DensityMatrix.maximallyMixed : DensityMatrix (Qbits n)))).kron α).conj
        U).partialTraceRight
      = (diagState s hs0 hs1).kron (DensityMatrix.maximallyMixed : DensityMatrix (Qbits n)) →
    False

/-- **The chain seal at the tracial blocks holds at every level.**  This is
`quantum_seal_dephase_kron_faithful` instantiated with the tracial (maximally mixed) block state
`mm` on `Qbits n`, which is positive
definite (`DensityMatrix.maximallyMixed_posDef`): dephasing site `0` of the chain at the tracial
block admits no faithful-ancilla Stinespring recovery, at every level `n` of the chain. -/
theorem chain_seal_dephase_faithful (r : ℝ) (hr0 : 0 < r) (hr1 : r < 1)
    (s : ℝ) (hs0 : 0 < s) (hs1 : s < 1) :
    ChainSealed r hr0 hr1 s hs0 hs1 := by
  intro n e _ _ α U hα hsecρ hsecσ
  exact quantum_seal_dephase_kron_faithful r hr0 hr1 s hs0 hs1
    (DensityMatrix.maximallyMixed : DensityMatrix (Qbits n))
    (DensityMatrix.maximallyMixed_posDef (n := Qbits n)) α U hα hsecρ hsecσ

/-! ## The headline bundle -/

/-- **The quantum Bernoulli shift, directed-local representation.** A single certificate bundling
the fixed hierarchy of finite marginals of the one-sided qubit chain: the directed system with
commuting inclusion (`appendQubit`) and shift (`shiftAdjoinQubit`), the tracial (maximally mixed)
state that is both inclusion- and shift-compatible, the temporal entropy rate `log 2` along the
shift-window filtration, the per-stage dephasing seal at the tracial blocks, and the trivial tracial
modular clock.  The maps are definitionally the fixed `appendQubit` / `shiftAdjoinQubit`, so only
their laws (propositions) are recorded.  See the module docstring for scope and provenance. -/
structure QuantumBernoulliShift where
  /-- **Directed system.** The inclusion `appendQubit` and the shift `shiftAdjoinQubit` commute, so
  the finite levels form a genuine directed system carrying the shift endomorphism. -/
  incl_shift_comm : ∀ (n : ℕ) (M : Matrix (Qbits n) (Qbits n) ℂ),
    shiftAdjoinQubit (appendQubit M) = appendQubit (shiftAdjoinQubit M)
  /-- **Inclusion-compatibility of the tracial state.** Pairing the `(n+1)`-level tracial state
  against an inclusion `appendQubit x` reproduces the `n`-level pairing against `x`. -/
  state_incl_compat : ∀ (n : ℕ) (x : Matrix (Qbits n) (Qbits n) ℂ),
    ((DensityMatrix.maximallyMixed : DensityMatrix (Qbits (n + 1))).val * appendQubit x).trace
      = ((DensityMatrix.maximallyMixed : DensityMatrix (Qbits n)).val * x).trace
  /-- **Shift-invariance of the tracial state.** Pairing the `(n+1)`-level tracial state against a
  shifted observable `shiftAdjoinQubit x` reproduces the `n`-level pairing against `x`. -/
  state_shift_invariant : ∀ (n : ℕ) (x : Matrix (Qbits n) (Qbits n) ℂ),
    ((DensityMatrix.maximallyMixed : DensityMatrix (Qbits (n + 1))).val
        * shiftAdjoinQubit x).trace
      = ((DensityMatrix.maximallyMixed : DensityMatrix (Qbits n)).val * x).trace
  /-- **Temporal entropy rate.** The per-window entropy rate along the shift-window filtration
  converges to `log 2` (the CNT-style site-window rate at the tracial state). -/
  temporal_rate : Filter.Tendsto (fun k => windowEntropy DensityMatrix.maximallyMixed k / k)
    Filter.atTop (nhds (Real.log 2))
  /-- **Per-stage seal at the tracial blocks.** For some faithful reference parameters `r, s`, the
  chain admits no faithful-ancilla Stinespring recovery of the dephasing of site `0` at the tracial
  block, at every level (see `ChainSealed`). -/
  sealed : ∃ (r : ℝ) (hr0 : 0 < r) (hr1 : r < 1) (s : ℝ) (hs0 : 0 < s) (hs1 : s < 1),
    ChainSealed r hr0 hr1 s hs0 hs1
  /-- **Trivial tracial modular clock.** At the tracial (maximally mixed) state the modular
  automorphism group is trivial at every level — the type II₁ shadow (see `ModularClock.lean`;
  the clock is provably nontrivial at a non-tracial product state, `modAut_diagState_ne_id`). -/
  trivial_tracial_clock : ∀ (n : ℕ) (t : ℝ) (a : Matrix (Qbits n) (Qbits n) ℂ),
    modAut (DensityMatrix.maximallyMixed_posDef (n := Qbits n)) t a = a

/-- **A quantum Bernoulli shift exists.** The witness assembles the already-proved theorems: the
inclusion/shift commutation (`shiftAdjoinQubit_appendQubit`), the tracial inclusion- and
shift-compatibility (`partialTrace_appendQubit_maximallyMixed`,
`maximallyMixed_shiftAdjoinQubit_pairing`), the temporal rate `log 2`
(`tendsto_windowEntropy_div_tracial`), the per-stage seal at the balanced parameters
`r = s = 1/2` (`chain_seal_dephase_faithful`), and the trivial tracial clock
(`modAut_maximallyMixed_Qbits_eq_id`). -/
theorem quantumBernoulliShift_exists : Nonempty QuantumBernoulliShift := by
  have h0 : (0 : ℝ) < 1 / 2 := by norm_num
  have h1 : (1 : ℝ) / 2 < 1 := by norm_num
  exact ⟨{
    incl_shift_comm := fun _ M => shiftAdjoinQubit_appendQubit M
    state_incl_compat := fun n x => partialTrace_appendQubit_maximallyMixed n x
    state_shift_invariant := fun n x => maximallyMixed_shiftAdjoinQubit_pairing n x
    temporal_rate := tendsto_windowEntropy_div_tracial
    sealed := ⟨1 / 2, h0, h1, 1 / 2, h0, h1,
      chain_seal_dephase_faithful (1 / 2) h0 h1 (1 / 2) h0 h1⟩
    trivial_tracial_clock := fun n t a => modAut_maximallyMixed_Qbits_eq_id n t a }⟩

end ErgodicTheory.OperatorEntropy

end
