/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Multifractal.BernoulliTwoSided
import Mathlib.Probability.Independence.InfinitePi
import Mathlib.Probability.Independence.Basic
import Mathlib.MeasureTheory.Measure.MeasuredSets
import Mathlib.Dynamics.Ergodic.Ergodic

/-!
# Ergodicity of the two-sided Bernoulli shift (mixing via cylinder approximation)

This file proves that the invertible left shift `biShiftEquiv` on the two-sided full shift
`BiShift α₀` is *ergodic* with respect to the i.i.d. product (Bernoulli) measure
`bernZ ν = Measure.infinitePi (fun _ : ℤ => ν)`.

## Why not Kolmogorov 0–1?

The one-sided proof (`Oseledets/Multifractal/BernoulliErgodic.lean`) routes through Kolmogorov's
0–1 law on the *forward tail* `⨅_n ⨆_{i ≥ n} coordSigma i`. That argument relies on the iterate
`shiftMap^[n] x k = x (k + n)` with `k ∈ ℕ` reading only the coordinates `{k + n : k ≥ 0} = [n, ∞)`,
so an invariant set lands in the forward tail. For the **two-sided** shift the iterate
`biShiftEquiv^[n] x k = x (k + n)` with `k ∈ ℤ` reads `{k + n : k ∈ ℤ} = ℤ` — *all* coordinates — so
an invariant set is **not** tail-measurable and the 0–1-law-on-the-tail does not apply.

## The honest route: mixing by cylinder approximation

This is the standard textbook proof. Let `A` be a measurable `biShiftEquiv`-invariant set and write
`μ = bernZ ν`, `T = biShiftEquiv`.

* **Approximation.** Every measurable `A` is approximated in symmetric difference by a *finite-block
  cylinder* `C` (a set measurable with respect to the coordinates in a finite block `J ⊆ ℤ`):
  `∀ ε > 0, ∃ C ∈ blockAlg, μ (C ∆ A) < ε`. This is Mathlib's
  `MeasureTheory.exists_measure_symmDiff_lt_of_generateFrom_isSetRing`, applied to the ring
  `blockAlg` of finite-block sets, which generates the product σ-algebra and contains `univ`.
* **Independence of separated blocks.** For `n` large, the block `J` of `C` and the block `J + n` of
  `T^[n] ⁻¹' C` are disjoint, so the two sets are independent under the i.i.d. measure
  (`ProbabilityTheory.indep_iSup_of_disjoint` applied to the independent coordinate σ-algebras):
  `μ (C ∩ T^[n] ⁻¹' C) = μ C · μ (T^[n] ⁻¹' C) = (μ C)²` (the last step by measure preservation).
* **Pushing through.** `μ A = μ (A ∩ T^[n] ⁻¹' A)` by invariance, and intersections are stable in
  symmetric difference, so `μ A` and `(μ C)²` differ by `O(ε)`, while `μ A` and `μ C` differ by `ε`.
  Letting `ε → 0` gives `(μ A) = (μ A)²`, hence `μ A ∈ {0, 1}` ⟹ ergodicity.

## Main result

* `ergodic_biShiftEquiv_bernZ : Ergodic biShiftEquiv (bernZ ν)`.
-/

open MeasureTheory Filter Topology Function Set MeasurableSpace ProbabilityTheory
open scoped ENNReal NNReal symmDiff

namespace Oseledets.Multifractal

variable {α₀ : Type*} [Fintype α₀] [MeasurableSpace α₀] [MeasurableSingletonClass α₀]

/-! ### The integer-coordinate σ-algebras and their independence -/

/-- The σ-algebra generated by the `n`-th coordinate projection of the two-sided full shift. -/
@[reducible] def coordSigmaZ (n : ℤ) : MeasurableSpace (BiShift α₀) :=
  MeasurableSpace.comap (fun x : BiShift α₀ => x n) inferInstance

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Independence of coordinates.** Under the two-sided Bernoulli measure the coordinate
σ-algebras `coordSigmaZ` form an independent family. This is `iIndepFun_infinitePi` applied to the
identity coordinate projections, converted from `iIndepFun` to `iIndep` of the generated
σ-algebras. -/
theorem iIndep_coordSigmaZ_bernZ (ν : Measure α₀) [IsProbabilityMeasure ν] :
    iIndep (coordSigmaZ (α₀ := α₀)) (bernZ ν) := by
  have h : iIndepFun (fun (i : ℤ) (ω : BiShift α₀) => id (ω i)) (bernZ ν) :=
    iIndepFun_infinitePi (Ω := fun _ : ℤ => α₀) (X := fun _ => id) (fun _ => measurable_id)
  exact h.iIndep

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- Each integer-coordinate σ-algebra is below the ambient product σ-algebra. -/
theorem coordSigmaZ_le (n : ℤ) :
    coordSigmaZ (α₀ := α₀) n ≤ (inferInstance : MeasurableSpace (BiShift α₀)) :=
  (measurable_pi_apply n).comap_le

/-! ### The finite-block σ-algebra and the ring of cylinders -/

/-- The σ-algebra of events depending only on the coordinates in a finite block `J ⊆ ℤ`: the
supremum of the coordinate σ-algebras over `J`. -/
@[reducible] def piBlock (J : Finset ℤ) : MeasurableSpace (BiShift α₀) :=
  ⨆ i ∈ J, coordSigmaZ (α₀ := α₀) i

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- Each finite-block σ-algebra is below the ambient product σ-algebra. -/
theorem piBlock_le (J : Finset ℤ) :
    piBlock (α₀ := α₀) J ≤ (inferInstance : MeasurableSpace (BiShift α₀)) :=
  iSup₂_le fun i _ => coordSigmaZ_le i

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- Enlarging the block enlarges the block σ-algebra. -/
theorem piBlock_mono {J K : Finset ℤ} (h : J ⊆ K) :
    piBlock (α₀ := α₀) J ≤ piBlock (α₀ := α₀) K :=
  iSup₂_mono' fun i hi => ⟨i, h hi, le_rfl⟩

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- A single coordinate σ-algebra sits inside the block over the singleton block. -/
theorem coordSigmaZ_le_piBlock_singleton (i : ℤ) :
    coordSigmaZ (α₀ := α₀) i ≤ piBlock (α₀ := α₀) {i} :=
  le_iSup₂_of_le (f := fun j (_ : j ∈ ({i} : Finset ℤ)) => coordSigmaZ (α₀ := α₀) j)
    i (Finset.mem_singleton_self i) le_rfl

/-- The **ring of finite-block cylinders**: the sets that are measurable with respect to some
finite block of coordinates. This is the ring fed to the symmetric-difference approximation
lemma. -/
def blockAlg : Set (Set (BiShift α₀)) :=
  {s | ∃ J : Finset ℤ, MeasurableSet[piBlock (α₀ := α₀) J] s}

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- Membership unfolding for the finite-block ring. -/
theorem mem_blockAlg {s : Set (BiShift α₀)} :
    s ∈ blockAlg (α₀ := α₀) ↔ ∃ J : Finset ℤ, MeasurableSet[piBlock (α₀ := α₀) J] s :=
  Iff.rfl

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- A block-`J` measurable set is a member of the finite-block ring. -/
theorem mem_blockAlg_of_piBlock {J : Finset ℤ} {s : Set (BiShift α₀)}
    (hs : MeasurableSet[piBlock (α₀ := α₀) J] s) : s ∈ blockAlg (α₀ := α₀) :=
  ⟨J, hs⟩

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- The finite-block ring is a genuine ring of sets: it contains `∅` and is closed under union and
set difference. Two block-measurable sets are jointly measurable over the union of their blocks,
where a sub-σ-algebra is closed under all Boolean operations. -/
theorem isSetRing_blockAlg : IsSetRing (blockAlg (α₀ := α₀)) where
  empty_mem := ⟨∅, @MeasurableSet.empty _ (piBlock (α₀ := α₀) ∅)⟩
  union_mem := by
    intro s t hs ht
    obtain ⟨J, hsJ⟩ := hs
    obtain ⟨K, htK⟩ := ht
    refine ⟨J ∪ K, ?_⟩
    have h1 := piBlock_mono (α₀ := α₀) (Finset.subset_union_left (s₁ := J) (s₂ := K)) _ hsJ
    have h2 := piBlock_mono (α₀ := α₀) (Finset.subset_union_right (s₁ := J) (s₂ := K)) _ htK
    exact h1.union h2
  diff_mem := by
    intro s t hs ht
    obtain ⟨J, hsJ⟩ := hs
    obtain ⟨K, htK⟩ := ht
    refine ⟨J ∪ K, ?_⟩
    have h1 := piBlock_mono (α₀ := α₀) (Finset.subset_union_left (s₁ := J) (s₂ := K)) _ hsJ
    have h2 := piBlock_mono (α₀ := α₀) (Finset.subset_union_right (s₁ := J) (s₂ := K)) _ htK
    exact h1.diff h2

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- The ambient product σ-algebra is the supremum of the integer-coordinate σ-algebras. -/
theorem pi_eq_iSup_coordSigmaZ :
    (inferInstance : MeasurableSpace (BiShift α₀)) = ⨆ i : ℤ, coordSigmaZ (α₀ := α₀) i := rfl

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- The finite-block ring **generates** the ambient product σ-algebra. The product σ-algebra is the
supremum of the coordinate σ-algebras, each of which is generated by a singleton-block cylinder, so
the generated σ-algebra is exactly `MeasurableSpace.pi`. -/
theorem generateFrom_blockAlg :
    (inferInstance : MeasurableSpace (BiShift α₀)) = generateFrom (blockAlg (α₀ := α₀)) := by
  refine le_antisymm ?_ ?_
  · -- `pi = ⨆ i, coordSigmaZ i`, and each coordinate σ-algebra lands in the generated σ-algebra.
    rw [pi_eq_iSup_coordSigmaZ]
    refine iSup_le fun i => le_trans (coordSigmaZ_le_piBlock_singleton i) ?_
    -- the singleton block sits below the generated σ-algebra (each of its sets is in the ring).
    intro s hs
    exact measurableSet_generateFrom (mem_blockAlg_of_piBlock hs)
  · -- every generator is block-measurable, hence ambient-measurable.
    rw [← generateFrom_measurableSet (α := BiShift α₀)]
    refine generateFrom_mono ?_
    rintro s ⟨J, hsJ⟩
    exact piBlock_le J _ hsJ

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- The whole space is a finite-block cylinder (the empty block), so the ring covers the space — the
nondegeneracy hypothesis of the approximation lemma. -/
theorem univ_mem_blockAlg : Set.univ ∈ blockAlg (α₀ := α₀) :=
  ⟨∅, MeasurableSet.univ⟩

/-! ### Cylinder approximation of an arbitrary measurable set -/

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Cylinder approximation.** Any measurable set is approximated, in symmetric difference, by a
finite-block cylinder. This is Mathlib's `exists_measure_symmDiff_lt_of_generateFrom_isSetRing`
specialized to the finite-block ring (which contains `univ`, so the space is covered modulo `0`,
and which generates the product σ-algebra). -/
theorem exists_blockAlg_symmDiff_lt (ν : Measure α₀) [IsProbabilityMeasure ν]
    {A : Set (BiShift α₀)} (hA : MeasurableSet A) {ε : ℝ≥0∞} (hε : 0 < ε) :
    ∃ C ∈ blockAlg (α₀ := α₀), bernZ ν (C ∆ A) < ε := by
  refine exists_measure_symmDiff_lt_of_generateFrom_isSetRing isSetRing_blockAlg ?_
    generateFrom_blockAlg hA hε
  refine ⟨{Set.univ}, Set.countable_singleton _, ?_, ?_⟩
  · simpa using univ_mem_blockAlg (α₀ := α₀)
  · simp

/-! ### The shifted block of a cylinder under an iterate of the shift -/

omit [Fintype α₀] [MeasurableSpace α₀] [MeasurableSingletonClass α₀] in
/-- The `k`-th iterate of the two-sided shift advances every (integer) index by `k`:
`biShiftMap^[k] x i = x (i + k)`. (Local copy, to avoid importing the entropy module.) -/
theorem biShiftMap_iterate_apply' (k : ℕ) (x : BiShift α₀) (i : ℤ) :
    (biShiftMap^[k] x) i = x (i + k) := by
  induction k generalizing i with
  | zero => simp
  | succ k ih =>
    rw [Function.iterate_succ_apply', biShiftMap, ih]
    push_cast
    ring_nf

/-- The block-translation embedding `i ↦ i + k` of `ℤ` into itself, used to re-index a finite block
under the iterate `biShiftMap^[k]`. -/
def blockShiftEmb (k : ℕ) : ℤ ↪ ℤ :=
  ⟨fun i => i + (k : ℤ), fun a b h => by simpa using h⟩

@[simp]
theorem blockShiftEmb_apply (k : ℕ) (i : ℤ) : blockShiftEmb k i = i + (k : ℤ) := rfl

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- Pulling back the `i`-th coordinate σ-algebra along `biShiftMap^[k]` gives the `(i + k)`-th
coordinate σ-algebra: `eval i ∘ biShiftMap^[k] = eval (i + k)` since `biShiftMap^[k] x i = x (i+k)`.
-/
theorem comap_iterate_coordSigmaZ (k : ℕ) (i : ℤ) :
    (coordSigmaZ (α₀ := α₀) i).comap (biShiftMap^[k]) = coordSigmaZ (α₀ := α₀) (i + (k : ℤ)) := by
  rw [coordSigmaZ, MeasurableSpace.comap_comp]
  congr 1
  funext x
  exact biShiftMap_iterate_apply' k x i

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- Pulling back a single block-summand `⨆ (_ : i ∈ J), coordSigmaZ i` along `biShiftMap^[k]`
re-indexes the coordinate to `i + k`. -/
theorem comap_iterate_piBlock (k : ℕ) (J : Finset ℤ) :
    (piBlock (α₀ := α₀) J).comap (biShiftMap^[k])
      = piBlock (α₀ := α₀) (J.map (blockShiftEmb k)) := by
  -- Push the `comap` through both suprema, so the LHS is `⨆ i ∈ J, comap g (coordSigmaZ i)`.
  simp only [piBlock, MeasurableSpace.comap_iSup, comap_iterate_coordSigmaZ]
  -- Now both sides are `⨆`-over-a-block of `coordSigmaZ`; match termwise via the embedding.
  apply le_antisymm
  · refine iSup₂_le fun i hi => le_iSup₂_of_le (i + (k : ℤ)) ?_ le_rfl
    rw [Finset.mem_map]
    exact ⟨i, hi, rfl⟩
  · refine iSup₂_le fun j hj => ?_
    rw [Finset.mem_map] at hj
    obtain ⟨i, hi, rfl⟩ := hj
    exact le_iSup₂_of_le i hi le_rfl

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Shifted-cylinder measurability.** If `C` is a block-`J` cylinder, then its preimage under the
iterate `biShiftMap^[k]` is a block-`(J + k)` cylinder. -/
theorem measurableSet_preimage_iterate_piBlock (k : ℕ) {J : Finset ℤ} {C : Set (BiShift α₀)}
    (hC : MeasurableSet[piBlock (α₀ := α₀) J] C) :
    MeasurableSet[piBlock (α₀ := α₀) (J.map (blockShiftEmb k))] (biShiftMap^[k] ⁻¹' C) := by
  have hmeas : Measurable[piBlock (α₀ := α₀) (J.map (blockShiftEmb k)), piBlock (α₀ := α₀) J]
      (biShiftMap^[k]) :=
    measurable_iff_comap_le.mpr (le_of_eq (comap_iterate_piBlock k J))
  exact hmeas hC

/-! ### Independence of separated blocks -/

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- The finite-block σ-algebra over `J` is the supremum of the coordinate σ-algebras over `J` viewed
as a *set* of indices, the form consumed by `ProbabilityTheory.indep_iSup_of_disjoint`. -/
theorem piBlock_eq_iSup_coe (J : Finset ℤ) :
    piBlock (α₀ := α₀) J = ⨆ i ∈ (↑J : Set ℤ), coordSigmaZ (α₀ := α₀) i := by
  simp only [piBlock, Finset.mem_coe]

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Independence of disjoint blocks.** If the blocks `J` and `K` are disjoint, then a block-`J`
cylinder `C` and a block-`K` cylinder `D` are independent under the two-sided Bernoulli measure:
`bernZ ν (C ∩ D) = bernZ ν C · bernZ ν D`. This is the i.i.d. independence of the coordinate
σ-algebras (`iIndep_coordSigmaZ_bernZ`) grouped over the disjoint index blocks
(`indep_iSup_of_disjoint`). -/
theorem measure_inter_of_disjoint_blocks (ν : Measure α₀) [IsProbabilityMeasure ν]
    {J K : Finset ℤ} (hJK : Disjoint J K) {C D : Set (BiShift α₀)}
    (hC : MeasurableSet[piBlock (α₀ := α₀) J] C) (hD : MeasurableSet[piBlock (α₀ := α₀) K] D) :
    bernZ ν (C ∩ D) = bernZ ν C * bernZ ν D := by
  have hdisjoint : Disjoint (↑J : Set ℤ) (↑K : Set ℤ) := by
    simpa [Finset.disjoint_coe] using hJK
  have hind : Indep (⨆ i ∈ (↑J : Set ℤ), coordSigmaZ (α₀ := α₀) i)
      (⨆ i ∈ (↑K : Set ℤ), coordSigmaZ (α₀ := α₀) i) (bernZ ν) :=
    indep_iSup_of_disjoint coordSigmaZ_le (iIndep_coordSigmaZ_bernZ ν) hdisjoint
  rw [piBlock_eq_iSup_coe] at hC hD
  exact (hind.indepSet_of_measurableSet hC hD).measure_inter_eq_mul

/-- For any finite block `J`, all sufficiently large forward shifts of `J` are disjoint from `J`:
there is `N` so that `Disjoint J (J.map (blockShiftEmb k))` for every `k ≥ N`. Concretely, pick `N`
beyond the diameter of `J`. -/
theorem exists_disjoint_shifted_block (J : Finset ℤ) :
    ∃ N : ℕ, ∀ k : ℕ, N ≤ k → Disjoint J (J.map (blockShiftEmb k)) := by
  rcases J.eq_empty_or_nonempty with hJ | hJ
  · exact ⟨0, fun k _ => by simp [hJ]⟩
  -- `M = max J`, `m = min J`; beyond `M - m` the shifted block starts past `M`.
  obtain ⟨M, hM⟩ : ∃ M : ℤ, ∀ i ∈ J, i ≤ M := ⟨J.max' hJ, fun i hi => J.le_max' i hi⟩
  obtain ⟨m, hm⟩ : ∃ m : ℤ, ∀ i ∈ J, m ≤ i := ⟨J.min' hJ, fun i hi => J.min'_le i hi⟩
  refine ⟨(M - m).toNat + 1, fun k hk => ?_⟩
  rw [Finset.disjoint_left]
  intro a haJ haShift
  rw [Finset.mem_map] at haShift
  obtain ⟨b, hbJ, rfl⟩ := haShift
  rw [blockShiftEmb_apply] at haJ
  -- `b + k ∈ J` and `b ∈ J`, but `b + k ≥ m + k > M ≥ b + k` — contradiction.
  have h1 : b + (k : ℤ) ≤ M := hM _ haJ
  have h2 : m ≤ b := hm _ hbJ
  have h4 : (M : ℤ) - m < k := by
    have hle : (M - m) ≤ ((M - m).toNat : ℤ) := Int.self_le_toNat _
    have : ((M - m).toNat : ℤ) + 1 ≤ k := by exact_mod_cast hk
    omega
  omega

/-! ### The mixing squeeze and pre-ergodicity -/

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
omit [Fintype α₀] [MeasurableSpace α₀] [MeasurableSingletonClass α₀] in
/-- The symmetric difference of two intersections is contained in the union of the corresponding
symmetric differences: `(C ∩ D) ∆ (A ∩ B) ⊆ (C ∆ A) ∪ (D ∆ B)`. -/
theorem symmDiff_inter_subset (C D A B : Set (BiShift α₀)) :
    (C ∩ D) ∆ (A ∩ B) ⊆ (C ∆ A) ∪ (D ∆ B) := by
  intro x hx
  simp only [Set.mem_symmDiff, Set.mem_inter_iff, Set.mem_union] at hx ⊢
  tauto

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **The mixing squeeze.** For a measurable `biShiftEquiv`-invariant set `A`, the real measure
`a = bernZ ν A` satisfies `|a - a²| ≤ 4 ε` for every `ε > 0`, hence `a = a²`. The cylinder `C` that
`ε`-approximates `A` is independent of its own large forward shift (disjoint blocks), giving
`(bernZ ν C).real² = bernZ ν (C ∩ shift⁻¹ C)`, while invariance gives `a = bernZ ν (A ∩ shift⁻¹ A)`;
the two intersections differ by `2 ε` in measure and `C, A` differ by `ε`. -/
theorem measureReal_invariant_sq (ν : Measure α₀) [IsProbabilityMeasure ν]
    {A : Set (BiShift α₀)} (hA : MeasurableSet A) (hinv : biShiftEquiv ⁻¹' A = A) :
    (bernZ ν).real A * (bernZ ν).real A = (bernZ ν).real A := by
  set μ := bernZ ν with hμ
  set a := μ.real A with ha
  -- It suffices to bound `|a*a - a|` by `4 ε` for every positive real `ε`.
  have hsq : ∀ ε : ℝ, 0 < ε → |a * a - a| ≤ 4 * ε := by
    intro ε hε
    -- Approximate `A` by a finite-block cylinder `C` with `μ (C ∆ A) < ε`.
    obtain ⟨C, ⟨J, hCJ⟩, hCA⟩ :=
      exists_blockAlg_symmDiff_lt ν hA (ε := ENNReal.ofReal ε) (by positivity)
    have hCmeas : MeasurableSet C := piBlock_le J _ hCJ
    -- A large forward shift `k` makes the block of `C` disjoint from the block of `shift⁻¹ C`.
    obtain ⟨N, hN⟩ := exists_disjoint_shifted_block J
    set k := N with hk
    have hdisj : Disjoint J (J.map (blockShiftEmb k)) := hN k le_rfl
    set D := biShiftMap^[k] ⁻¹' C with hD
    have hDmeas : MeasurableSet D :=
      piBlock_le _ _ (measurableSet_preimage_iterate_piBlock k hCJ)
    -- `shift^[k]` preserves `μ`, and `biShiftEquiv^[k] = biShiftMap^[k]`.
    have hmp : MeasurePreserving ((biShiftMap (α₀ := α₀))^[k]) μ μ := by
      have h := (measurePreserving_biShiftEquiv_bernZ (α₀ := α₀) ν).iterate k
      rw [coe_biShiftEquiv, ← hμ] at h
      exact h
    -- `μ.real D = μ.real C`.
    have hDC : μ.real D = μ.real C := by
      rw [hD]; exact hmp.measureReal_preimage hCmeas.nullMeasurableSet
    -- Independence of disjoint blocks: `μ.real (C ∩ D) = μ.real C * μ.real C`.
    have hCD : μ.real (C ∩ D) = μ.real C * μ.real C := by
      have hmul := measure_inter_of_disjoint_blocks ν hdisj hCJ
        (measurableSet_preimage_iterate_piBlock k hCJ)
      rw [← hμ, ← hD] at hmul
      rw [Measure.real, hmul, ENNReal.toReal_mul, ← Measure.real, ← Measure.real, hDC]
    -- The shifted invariant set `B = shift^[k] ⁻¹' A` equals `A`.
    have hBA : biShiftMap^[k] ⁻¹' A = A := by
      have : (biShiftEquiv (α₀ := α₀))^[k] ⁻¹' A = A := IsFixedPt.preimage_iterate hinv k
      rwa [coe_biShiftEquiv] at this
    -- `μ.real (A ∩ B) = a` since `B = A`.
    have hAB : μ.real (A ∩ (biShiftMap^[k] ⁻¹' A)) = a := by rw [hBA, Set.inter_self]
    -- `μ.real (C ∆ A) < ε`.
    have hCAreal : μ.real (C ∆ A) < ε := by
      have hlt : (μ (C ∆ A)).toReal < (ENNReal.ofReal ε).toReal :=
        (ENNReal.toReal_lt_toReal (by finiteness) (by finiteness)).mpr hCA
      rwa [ENNReal.toReal_ofReal hε.le, ← Measure.real] at hlt
    -- `μ.real (D ∆ (shift^[k] ⁻¹' A)) = μ.real (C ∆ A)` by preservation.
    have hDB : μ.real (D ∆ (biShiftMap^[k] ⁻¹' A)) = μ.real (C ∆ A) := by
      rw [hD, ← Set.preimage_symmDiff]
      exact hmp.measureReal_preimage (hCmeas.symmDiff hA).nullMeasurableSet
    -- The two intersections are close: `|μ.real (C ∩ D) - μ.real (A ∩ B)| ≤ 2 ε`.
    have hclose : |μ.real (C ∩ D) - μ.real (A ∩ (biShiftMap^[k] ⁻¹' A))| ≤ 2 * ε := by
      have hABmeas : MeasurableSet (A ∩ (biShiftMap^[k] ⁻¹' A)) :=
        hA.inter (hA.preimage hmp.measurable)
      have htri := abs_measureReal_sub_le_measureReal_symmDiff (μ := μ)
        (hCmeas.inter hDmeas).nullMeasurableSet hABmeas.nullMeasurableSet
      refine htri.trans ?_
      have hsub : μ.real ((C ∩ D) ∆ (A ∩ (biShiftMap^[k] ⁻¹' A)))
          ≤ μ.real ((C ∆ A) ∪ (D ∆ (biShiftMap^[k] ⁻¹' A))) :=
        measureReal_mono (symmDiff_inter_subset _ _ _ _) (by finiteness)
      refine hsub.trans ?_
      refine (measureReal_union_le _ _).trans ?_
      rw [hDB]
      have := hCAreal.le
      linarith
    -- `|μ.real C - a| ≤ ε`.
    have hca : |μ.real C - a| ≤ ε := by
      have := abs_measureReal_sub_le_measureReal_symmDiff (μ := μ)
        hCmeas.nullMeasurableSet hA.nullMeasurableSet
      calc |μ.real C - a| = |μ.real C - μ.real A| := by rw [ha]
        _ ≤ μ.real (C ∆ A) := this
        _ ≤ ε := hCAreal.le
    -- Bounds on the masses (probabilities lie in `[0,1]`).
    have ha01 : a ≤ 1 := by rw [ha]; exact measureReal_le_one
    have hc01 : μ.real C ≤ 1 := measureReal_le_one
    have ha0 : 0 ≤ a := measureReal_nonneg
    have hc0 : 0 ≤ μ.real C := measureReal_nonneg
    -- `|c² - a| ≤ 2 ε` from `hclose`, `hCD`, `hAB`.
    have hc2a : |μ.real C * μ.real C - a| ≤ 2 * ε := by
      rw [← hCD, ← hAB]; exact hclose
    -- Combine: `|a*a - a| ≤ |a*a - c²| + |c² - a| ≤ |a-c|*(a+c) + 2 ε ≤ 2 ε + 2 ε`.
    have hac : |a - μ.real C| ≤ ε := by rw [abs_sub_comm]; exact hca
    have hquad : |a * a - μ.real C * μ.real C| ≤ 2 * ε := by
      have hfac : a * a - μ.real C * μ.real C = (a - μ.real C) * (a + μ.real C) := by ring
      rw [hfac, abs_mul]
      have h1 : |a - μ.real C| ≤ ε := hac
      have h2 : |a + μ.real C| ≤ 2 := by
        rw [abs_of_nonneg (by linarith)]; linarith
      calc |a - μ.real C| * |a + μ.real C| ≤ ε * 2 :=
            mul_le_mul h1 h2 (abs_nonneg _) hε.le
        _ = 2 * ε := by ring
    calc |a * a - a| ≤ |a * a - μ.real C * μ.real C| + |μ.real C * μ.real C - a| := by
          have := abs_sub_le (a * a) (μ.real C * μ.real C) a; linarith [this]
      _ ≤ 2 * ε + 2 * ε := add_le_add hquad hc2a
      _ = 4 * ε := by ring
  -- From `|a*a - a| ≤ 4 ε` for all `ε > 0` conclude `a*a = a`.
  have : a * a - a = 0 := by
    by_contra h
    have hpos : 0 < |a * a - a| := abs_pos.mpr h
    have := hsq (|a * a - a| / 8) (by positivity)
    rw [show (4 : ℝ) * (|a * a - a| / 8) = |a * a - a| / 2 by ring] at this
    linarith
  linarith

/-! ### Pre-ergodicity and the main result -/

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Pre-ergodicity via mixing.** Any measurable `biShiftEquiv`-invariant set has `bernZ ν`-measure
`0` or `1`. The real measure `a` satisfies `a² = a` (the mixing squeeze), so `a ∈ {0, 1}`; lifting
back to `ENNReal` gives `bernZ ν A ∈ {0, 1}`. -/
theorem measure_invariant_eq_zero_or_one_bernZ (ν : Measure α₀) [IsProbabilityMeasure ν]
    {A : Set (BiShift α₀)} (hA : MeasurableSet A) (hinv : biShiftEquiv ⁻¹' A = A) :
    bernZ ν A = 0 ∨ bernZ ν A = 1 := by
  have hsq := measureReal_invariant_sq ν hA hinv
  -- `a * a = a` with `a = (bernZ ν A).real ∈ [0,1]` forces `a = 0` or `a = 1`.
  have ha01 : (bernZ ν).real A ≤ 1 := measureReal_le_one
  have ha0 : 0 ≤ (bernZ ν).real A := measureReal_nonneg
  have hzo : (bernZ ν).real A = 0 ∨ (bernZ ν).real A = 1 := by
    have hfac : (bernZ ν).real A * ((bernZ ν).real A - 1) = 0 := by nlinarith [hsq]
    rcases mul_eq_zero.mp hfac with h | h
    · exact Or.inl h
    · exact Or.inr (by linarith [h])
  -- Lift the real equality back to the `ENNReal`-valued measure.
  rcases hzo with h | h
  · left
    have : ENNReal.ofReal ((bernZ ν).real A) = ENNReal.ofReal 0 := by rw [h]
    rwa [ofReal_measureReal (by finiteness), ENNReal.ofReal_zero] at this
  · right
    have : ENNReal.ofReal ((bernZ ν).real A) = ENNReal.ofReal 1 := by rw [h]
    rwa [ofReal_measureReal (by finiteness), ENNReal.ofReal_one] at this

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Ergodicity of the two-sided Bernoulli shift.** The invertible left shift `biShiftEquiv` is
ergodic with respect to the i.i.d. product (Bernoulli) measure `bernZ ν`. The measure-preserving
half is `measurePreserving_biShiftEquiv_bernZ`; pre-ergodicity is the mixing argument
(`measure_invariant_eq_zero_or_one_bernZ`) — the honest, textbook route via cylinder approximation,
since
the two-sided shift's invariant sets are *not* tail-measurable and Kolmogorov's 0–1 law does not
apply. -/
theorem ergodic_biShiftEquiv_bernZ (ν : Measure α₀) [IsProbabilityMeasure ν] :
    Ergodic (biShiftEquiv (α₀ := α₀)) (bernZ ν) where
  toMeasurePreserving := measurePreserving_biShiftEquiv_bernZ ν
  aeconst_set s hs hinv := by
    rw [eventuallyConst_set']
    -- `hinv : biShiftEquiv ⁻¹' s = s` is the strict preimage equality the mixing argument consumes.
    rcases measure_invariant_eq_zero_or_one_bernZ ν hs hinv with h0 | h1
    · exact Or.inl (ae_eq_empty.mpr h0)
    · refine Or.inr (ae_eq_univ.mpr ?_)
      have : bernZ ν sᶜ = 1 - bernZ ν s := by
        rw [measure_compl hs (measure_ne_top _ _), measure_univ]
      rw [this, h1, tsub_self]

end Oseledets.Multifractal
