/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Multifractal.SymbolicDimensionBernoulli
import Mathlib.Probability.Independence.InfinitePi
import Mathlib.Probability.Independence.ZeroOne
import Mathlib.Dynamics.Ergodic.Ergodic

/-!
# Ergodicity of the one-sided Bernoulli shift (Kolmogorov 0–1 law)

This file proves node **N3** of the Bernoulli witness: the left shift `shiftMap` on the one-sided
full shift `Shift α₀` is *ergodic* with respect to the i.i.d. product (Bernoulli) measure
`bern ν = Measure.infinitePi (fun _ => ν)`.

The proof is the classical route through **Kolmogorov's 0–1 law**, not mixing.

* `Ergodic = MeasurePreserving ∧ PreErgodic`. The measure-preserving half is the on-`main`
  `measurePreserving_shiftMap_bern`.
* For `PreErgodic` we must show that any measurable `shiftMap`-invariant set has `bern ν`-measure
  `0` or `1`.
* **Independence of coordinates.** The coordinate σ-algebras
  `coordSigma n := MeasurableSpace.comap (fun x => x n) inferInstance` are independent under
  `bern ν` (`ProbabilityTheory.iIndepFun_infinitePi` on the coordinate projections, then
  `ProbabilityTheory.iIndepFun.iIndep`).
* **Tail-bridge (the in-repo work).** A `shiftMap`-invariant measurable set `s` satisfies
  `s = (shiftMap^[n]) ⁻¹' s` for every `n`. Since `shiftMap^[n]` reads output coordinate `k` from
  input coordinate `k + n ≥ n`, it is measurable for the σ-algebra `⨆ i ≥ n, coordSigma i`; hence
  `s` is measurable for that σ-algebra for every `n`, i.e. for the tail
  `Filter.limsup coordSigma Filter.atTop = ⨅ n, ⨆ i ≥ n, coordSigma i`.
* **0–1 law.** `ProbabilityTheory.measure_zero_or_one_of_measurableSet_limsup_atTop` then forces
  `bern ν s ∈ {0, 1}`.

This discharges the standing `Ergodic shiftMap μ` conditional of the headline
`dimH_eq_ksEntropy_div_log_two`.

## Main result

* `ergodic_shiftMap_bern : Ergodic shiftMap (bern ν)`.
-/

open MeasureTheory Filter Topology Function Set MeasurableSpace ProbabilityTheory
open scoped ENNReal NNReal

namespace Oseledets.Multifractal

variable {α₀ : Type*} [Fintype α₀] [MeasurableSpace α₀] [MeasurableSingletonClass α₀]

/-! ### N3 — the coordinate σ-algebras and the tail bridge -/

/-- The σ-algebra generated by the `n`-th coordinate projection of the one-sided full shift. -/
@[reducible] def coordSigma (n : ℕ) : MeasurableSpace (Shift α₀) :=
  MeasurableSpace.comap (fun x : Shift α₀ => x n) inferInstance

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Independence of coordinates.** Under the Bernoulli measure the coordinate σ-algebras
`coordSigma` form an independent family. This is `iIndepFun_infinitePi` applied to the identity
coordinate projections, converted from `iIndepFun` to `iIndep` of the generated σ-algebras. -/
theorem iIndep_coordSigma_bern (ν : Measure α₀) [IsProbabilityMeasure ν] :
    iIndep (coordSigma (α₀ := α₀)) (bern ν) := by
  have h : iIndepFun (fun (i : ℕ) (ω : Shift α₀) => id (ω i)) (bern ν) :=
    iIndepFun_infinitePi (Ω := fun _ : ℕ => α₀) (X := fun _ => id) (fun _ => measurable_id)
  exact h.iIndep

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- Each coordinate σ-algebra is below the ambient σ-algebra on the full shift. -/
theorem coordSigma_le (n : ℕ) :
    coordSigma (α₀ := α₀) n ≤ (inferInstance : MeasurableSpace (Shift α₀)) :=
  (measurable_pi_apply n).comap_le

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- The `n`-th shift iterate is measurable when the domain carries the σ-algebra generated by the
coordinates `≥ n`: its `k`-th output coordinate is the input coordinate `k + n ≥ n`. -/
theorem measurable_shiftMap_iterate_tail (n : ℕ) :
    Measurable[⨆ i ≥ n, coordSigma (α₀ := α₀) i] (shiftMap^[n]) := by
  -- It suffices to bound the pulled-back ambient σ-algebra by `⨆ i ≥ n, coordSigma i`.
  refine Measurable.of_comap_le ?_
  -- The ambient σ-algebra on `Shift α₀` is `⨆ k, comap (eval k) _`; pulling back along
  -- `shiftMap^[n]` reindexes coordinate `k ↦ k + n`.
  show (MeasurableSpace.pi).comap ((shiftMap (α₀ := α₀))^[n]) ≤ ⨆ i ≥ n, coordSigma (α₀ := α₀) i
  rw [MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  refine iSup_le fun k => ?_
  -- `comap (eval k) ∘ comap (shiftMap^[n]) = comap (eval (k+n))`.
  rw [MeasurableSpace.comap_comp]
  have hcomp : (fun x : Shift α₀ => x k) ∘ (shiftMap^[n]) = fun x : Shift α₀ => x (k + n) := by
    funext x; exact shiftMap_iterate_apply n x k
  rw [hcomp]
  -- `comap (eval (k+n)) _ = coordSigma (k+n) ≤ ⨆ i ≥ n, coordSigma i` since `k + n ≥ n`.
  exact le_iSup₂ (f := fun i (_ : n ≤ i) => coordSigma (α₀ := α₀) i) (k + n) (Nat.le_add_left n k)

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Tail-measurability of an invariant set.** A measurable `shiftMap`-invariant set is measurable
with respect to the tail σ-algebra `Filter.limsup coordSigma Filter.atTop`. -/
theorem measurableSet_limsup_of_invariant {s : Set (Shift α₀)} (hs : MeasurableSet s)
    (hinv : shiftMap ⁻¹' s = s) :
    MeasurableSet[limsup (coordSigma (α₀ := α₀)) atTop] s := by
  rw [limsup_eq_iInf_iSup_of_nat, measurableSet_iInf]
  intro n
  -- `s = (shiftMap^[n]) ⁻¹' s` by iterating the invariance, then preimage is tail-measurable.
  have hiter : (shiftMap^[n]) ⁻¹' s = s := IsFixedPt.preimage_iterate hinv n
  rw [← hiter]
  exact (measurable_shiftMap_iterate_tail n) hs

/-! ### N3 — the 0–1 law and ergodicity -/

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **Pre-ergodicity via the 0–1 law.** Any measurable `shiftMap`-invariant set has `bern ν`-measure
`0` or `1`: it is tail-measurable, and the Bernoulli coordinates are independent. -/
theorem measure_invariant_eq_zero_or_one (ν : Measure α₀) [IsProbabilityMeasure ν]
    {s : Set (Shift α₀)} (hs : MeasurableSet s) (hinv : shiftMap ⁻¹' s = s) :
    bern ν s = 0 ∨ bern ν s = 1 :=
  measure_zero_or_one_of_measurableSet_limsup_atTop
    (s := coordSigma (α₀ := α₀)) coordSigma_le (iIndep_coordSigma_bern ν)
    (measurableSet_limsup_of_invariant hs hinv)

omit [Fintype α₀] [MeasurableSingletonClass α₀] in
/-- **N3 (ergodicity of the Bernoulli shift).** The left shift `shiftMap` is ergodic with respect
to the i.i.d. product measure `bern ν`. The measure-preserving half is
`measurePreserving_shiftMap_bern`; pre-ergodicity is Kolmogorov's 0–1 law applied to the
tail-measurable invariant sets. -/
theorem ergodic_shiftMap_bern (ν : Measure α₀) [IsProbabilityMeasure ν] :
    Ergodic (shiftMap (α₀ := α₀)) (bern ν) where
  toMeasurePreserving := measurePreserving_shiftMap_bern ν
  aeconst_set s hs hinv := by
    rw [eventuallyConst_set']
    rcases measure_invariant_eq_zero_or_one ν hs hinv with h0 | h1
    · exact Or.inl (ae_eq_empty.mpr h0)
    · refine Or.inr (ae_eq_univ.mpr ?_)
      have : bern ν sᶜ = 1 - bern ν s := by
        rw [measure_compl hs (measure_ne_top _ _), measure_univ]
      rw [this, h1, tsub_self]

end Oseledets.Multifractal

