/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Lyapunov.Extensions.Spectrum

/-!
# Lyapunov exponents of a constant cocycle

For a **constant** generator `A ≡ M` the iterated cocycle is just the matrix power,
`cocycle (fun _ => M) T n x = Mⁿ`, and the whole Oseledets apparatus collapses to ordinary
linear algebra. This module records that collapse and, for a **symmetric** (real Hermitian)
generator `M`, identifies the Lyapunov spectrum with the log-moduli of the eigenvalues of `M`.

The geometric content is the polar/singular-value picture of a symmetric matrix: the Oseledets
limit `Λ x = lim_n (Qₙ)^{1/(2n)}` of the constant cocycle is, for every `x`, the **absolute
value** `|M| = cfc |·| M`, whose sorted eigenvalues are the moduli `|λᵢ(M)|` sorted in
non-increasing order. Feeding this through the eigenvalue tie
`Oseledets.exp_exponents_eq_eigenvalues₀_oseledetsLimit` gives `exp (exponents … i) = |M|`'s
`i`-th sorted eigenvalue, hence `exponents … i = log` of the `i`-th largest modulus.

## Main definitions

* `Oseledets.absMatrix` — the absolute value `|M| = cfc |·| M` of a (real) matrix, the Oseledets
  limit of the constant symmetric cocycle.

## Main results

* `Oseledets.cocycle_const` — `cocycle (fun _ => M) T n x = Mⁿ` for an arbitrary generator `M`.
* `Oseledets.gram_const`, `Oseledets.qpow_const`, `Oseledets.oseledetsLimit_const` — for symmetric
  `M`, the Gram matrix is `M^{2n}`, the approximant `qpow` is `|M|` for every `n ≥ 1`, and the
  Oseledets limit is `|M|`.
* `Oseledets.exp_exponents_const_eq_eigenvalues₀_absMatrix` — for symmetric invertible `M`,
  `exp (exponents (fun _ => M) … i) = |M|`'s `i`-th sorted eigenvalue.
* `Oseledets.exponents_const` — for symmetric invertible `M`,
  `exponents (fun _ => M) … i = Real.log (|M|.eigenvalues₀ i)`, i.e. the log of the `i`-th largest
  modulus of an eigenvalue of `M`.

## References

* M. Viana, *Lectures on Lyapunov Exponents*, Cambridge Studies in Adv. Math. **145** (2014).
-/

open MeasureTheory Filter Topology
open scoped Matrix

namespace Oseledets

variable {X : Type*} [MeasurableSpace X] {d : ℕ}

/-! ## The constant cocycle is the matrix power -/

set_option linter.unusedSectionVars false in
/-- **The constant cocycle is the matrix power.** For a constant generator `A ≡ M`, the iterated
cocycle is `cocycle (fun _ => M) T n x = Mⁿ`, independent of the base point and the dynamics. -/
theorem cocycle_const (M : Matrix (Fin d) (Fin d) ℝ) (T : X → X) (n : ℕ) (x : X) :
    cocycle (fun _ => M) T n x = M ^ n := by
  induction n generalizing x with
  | zero => simp
  | succ n ih => rw [cocycle_succ, ih (T x), pow_succ]

/-! ## The Gram matrix and `qpow` of a symmetric constant cocycle -/

/-- For a **symmetric** constant generator `M` (`hM : Mᵀ = M`), the Gram matrix of the constant
cocycle is the even power `gram (fun _ => M) T n x = M^{2n}`: indeed
`(Mⁿ)ᵀ Mⁿ = (Mᵀ)ⁿ Mⁿ = Mⁿ Mⁿ = M^{n+n}`. -/
theorem gram_const {M : Matrix (Fin d) (Fin d) ℝ} (hM : Mᵀ = M) (T : X → X) (n : ℕ) (x : X) :
    gram (fun _ => M) T n x = M ^ (2 * n) := by
  rw [gram, cocycle_const, Matrix.transpose_pow, hM, ← pow_add, two_mul]

/-- The **absolute value of a real matrix**, `|M| = cfc |·| M`, defined through the continuous
functional calculus. For a symmetric `M` it is positive semidefinite with eigenvalues the moduli
`|λᵢ(M)|`, and it is the Oseledets limit of the constant cocycle generated by `M`
(`oseledetsLimit_const`). -/
noncomputable def absMatrix (M : Matrix (Fin d) (Fin d) ℝ) : Matrix (Fin d) (Fin d) ℝ :=
  cfc (fun t : ℝ => |t|) M

/-- `|M| = cfc |·| M` is self-adjoint (a real-valued continuous functional calculus is always
self-adjoint), hence Hermitian. -/
theorem absMatrix_isSelfAdjoint (M : Matrix (Fin d) (Fin d) ℝ) :
    IsSelfAdjoint (absMatrix M) :=
  cfc_predicate _ _

/-- `|M| = cfc |·| M` is Hermitian. -/
theorem absMatrix_isHermitian (M : Matrix (Fin d) (Fin d) ℝ) :
    (absMatrix M).IsHermitian :=
  (absMatrix_isSelfAdjoint M).isHermitian

/-- For a **symmetric** generator `M` and every `n ≥ 1`, the Oseledets approximant of the constant
cocycle is the absolute value `qpow (fun _ => M) T n x = |M|`.

The Gram matrix is `M^{2n}` (`gram_const`), so `qpow = cfc (·^{1/(2n)}) (M^{2n})`. Pulling the
`(2n)`-th power inside the calculus (`cfc_comp_pow`) turns this into
`cfc (fun t => (t^{2n})^{1/(2n)}) M`, and `(t^{2n})^{1/(2n)} = |t|` for every real `t` (even power,
then `rpow` cancellation), so the calculus reduces to `cfc |·| M = |M|`. -/
theorem qpow_const {M : Matrix (Fin d) (Fin d) ℝ} (hM : Mᵀ = M) (T : X → X) {n : ℕ} (hn : 1 ≤ n)
    (x : X) : qpow (fun _ => M) T n x = absMatrix M := by
  have hherm : M.IsHermitian := by
    change Mᴴ = M
    rw [Matrix.conjTranspose_eq_transpose_of_trivial]; exact hM
  have hsa : IsSelfAdjoint M := Matrix.isHermitian_iff_isSelfAdjoint.mp hherm
  have hnpos : (0 : ℝ) < n := by
    have : (1 : ℝ) ≤ n := by exact_mod_cast hn
    linarith
  have hn0 : (2 * (n : ℝ)) ≠ 0 := by positivity
  -- `qpow = cfc (·^{1/(2n)}) (gram) = cfc (·^{1/(2n)}) (M^{2n})`.
  rw [qpow, gram_const hM]
  -- Pull the `(2n)`-th power inside: `cfc f (M^{2n}) = cfc (fun t => f (t^{2n})) M`.
  have hcont : Continuous (fun t : ℝ => t ^ ((2 * (n : ℝ))⁻¹)) :=
    Real.continuous_rpow_const (by positivity)
  rw [← cfc_comp_pow (fun t : ℝ => t ^ ((2 * (n : ℝ))⁻¹)) (2 * n) M hcont.continuousOn hsa]
  -- The composite function equals `|·|` on all of `ℝ`, hence on the spectrum of `M`.
  rw [absMatrix]
  refine cfc_congr (fun t _ => ?_)
  -- Force the beta-reduced target so the `rpow` rewrites can fire.
  change (t ^ (2 * n)) ^ ((2 * (n : ℝ))⁻¹) = |t|
  -- `(t^{2n})^{1/(2n)} = |t|`.
  have heven : Even (2 * n) := ⟨n, two_mul n⟩
  rw [← heven.pow_abs, ← Real.rpow_natCast |t| (2 * n), ← Real.rpow_mul (abs_nonneg t)]
  rw [show ((2 * n : ℕ) : ℝ) * (2 * (n : ℝ))⁻¹ = 1 by
    push_cast; exact mul_inv_cancel₀ hn0]
  exact Real.rpow_one _

/-! ## The Oseledets limit of a symmetric constant cocycle is `|M|` -/

/-- For a **symmetric** generator `M`, the Oseledets limit of the constant cocycle is, for every
base point, the absolute value `oseledetsLimit (fun _ => M) T x = |M|`. The approximants
`qpow (fun _ => M) T n x` are equal to `|M|` for every `n ≥ 1` (`qpow_const`), so each entry of the
limit (`limUnder` of an eventually-constant sequence) is the corresponding entry of `|M|`. -/
theorem oseledetsLimit_const {M : Matrix (Fin d) (Fin d) ℝ} (hM : Mᵀ = M) (T : X → X) (x : X) :
    oseledetsLimit (fun _ => M) T x = absMatrix M := by
  refine Matrix.ext fun i j => ?_
  simp only [oseledetsLimit, Matrix.of_apply]
  -- The entry sequence is eventually the constant `|M| i j`.
  have hev : (fun _ : ℕ => absMatrix M i j)
      =ᶠ[atTop] fun n : ℕ => qpow (fun _ => M) T n x i j := by
    filter_upwards [eventually_ge_atTop 1] with n hn
    rw [qpow_const hM T hn x]
  exact (tendsto_const_nhds.congr' hev).limUnder_eq

/-! ## The Lyapunov spectrum of a symmetric constant cocycle

We now fix an ergodic, probability-preserving system `(X, μ, T)` and an **invertible symmetric**
generator `M`, and discharge the standing spectrum hypotheses for the constant cocycle
`A := fun _ => M`. -/

section Spectrum

variable {μ : Measure X}

set_option linter.unusedSectionVars false in
/-- The invertibility hypothesis `∀ x, (A x).det ≠ 0` for the constant cocycle, from `M.det ≠ 0`. -/
theorem const_det_ne_zero {M : Matrix (Fin d) (Fin d) ℝ} (hdet : M.det ≠ 0) :
    ∀ x : X, ((fun _ : X => M) x).det ≠ 0 := fun _ => hdet

/-- The measurability hypothesis for the constant cocycle: a constant map is measurable. -/
theorem const_measurable (M : Matrix (Fin d) (Fin d) ℝ) : Measurable (fun _ : X => M) :=
  measurable_const

/-- The log-integrability hypothesis `IntegrableLogNorm A μ` for the constant cocycle: `log⁺‖M‖`
is a constant, integrable over a finite (probability) measure. -/
theorem const_integrableLogNorm [IsFiniteMeasure μ] (M : Matrix (Fin d) (Fin d) ℝ) :
    IntegrableLogNorm (fun _ : X => M) μ :=
  integrable_const _

/-- The inverse log-integrability hypothesis for the constant cocycle: `log⁺‖M⁻¹‖` is a constant,
integrable over a finite (probability) measure. -/
theorem const_integrableLogNorm_inv [IsFiniteMeasure μ] (M : Matrix (Fin d) (Fin d) ℝ) :
    IntegrableLogNorm (fun x => ((fun _ : X => M) x)⁻¹) μ :=
  integrable_const _

variable {T : X → X} [IsProbabilityMeasure μ] (hT : Ergodic T μ)
    {M : Matrix (Fin d) (Fin d) ℝ} (hM : Mᵀ = M) (hdet : M.det ≠ 0) [NeZero d]

include hM hdet in
/-- **The eigenvalue tie for a symmetric constant cocycle.** For symmetric invertible `M`, the
exponential of the `i`-th Lyapunov exponent of the constant cocycle is the `i`-th sorted eigenvalue
of the absolute value `|M|`: `exp (exponents (fun _ => M) … i) = |M|.eigenvalues₀ i`.

This specializes `exp_exponents_eq_eigenvalues₀_oseledetsLimit` using
`oseledetsLimit (fun _ => M) T x = |M|`. Both sides are independent of the base point, so the a.e.
statement is upgraded to a genuine `∀ i` by extracting a single point (the probability measure has
a nonempty a.e.-filter). -/
theorem exp_exponents_const_eq_eigenvalues₀_absMatrix
    (i : Fin (Fintype.card (Fin d))) :
    Real.exp (exponents hT (const_det_ne_zero hdet) (const_measurable M)
        (const_integrableLogNorm M) (const_integrableLogNorm_inv M)
        ⟨(i : ℕ), lt_of_lt_of_eq i.isLt (Fintype.card_fin d)⟩)
      = (absMatrix_isHermitian M).eigenvalues₀ i := by
  -- Extract a single point from the a.e. eigenvalue tie (the probability `ae`-filter is `NeBot`).
  obtain ⟨x, hx⟩ := (exp_exponents_eq_eigenvalues₀_oseledetsLimit hT (const_det_ne_zero hdet)
    (const_measurable M) (const_integrableLogNorm M) (const_integrableLogNorm_inv M)).exists
  -- At `x`, the Oseledets limit is `|M|`; rewrite it (under the binder) in the eigenvalue tie.
  have hΛ : oseledetsLimit (fun _ => M) T x = absMatrix M := oseledetsLimit_const hM T x
  simp only [hΛ] at hx
  -- Now `hx` is stated for the matrix `|M|`; apply it to our Hermitian witness.
  exact hx (absMatrix_isHermitian M) i

include hM hdet in
/-- **The Lyapunov spectrum of a symmetric constant cocycle.** For symmetric invertible `M`, the
`i`-th Lyapunov exponent of the constant cocycle is `log` of the `i`-th sorted eigenvalue of `|M|`,
i.e. the log of the `i`-th largest modulus `|λ(M)|` of an eigenvalue of `M`. Obtained by taking
`Real.log` of the positive eigenvalue tie `exp_exponents_const_eq_eigenvalues₀_absMatrix`. -/
theorem exponents_const (i : Fin (Fintype.card (Fin d))) :
    exponents hT (const_det_ne_zero hdet) (const_measurable M) (const_integrableLogNorm M)
        (const_integrableLogNorm_inv M)
        ⟨(i : ℕ), lt_of_lt_of_eq i.isLt (Fintype.card_fin d)⟩
      = Real.log ((absMatrix_isHermitian M).eigenvalues₀ i) := by
  rw [← exp_exponents_const_eq_eigenvalues₀_absMatrix hT hM hdet i, Real.log_exp]

end Spectrum

end Oseledets
