/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Entropy.KSEntropySystem

/-!
# Generating partitions and the supplied-generator entropy interface

A finite measurable partition `P` of a measure-preserving system `(α, T, μ)` is a **generator**
(or *generating partition*) when the dynamics, refined under the forward iterates of `T`, recovers
the whole measurable structure: the smallest `T`-pullback-stable σ-algebra containing the σ-algebra
`σ(P)` generated by the cells of `P` is the ambient σ-algebra `mα`.

The classical **Kolmogorov–Sinai theorem** then asserts the entropy reduction
`h(T) = h(P, T)` for any generator `P`: the supremum defining the entropy of the system is already
attained on a single generating partition. Proving that theorem is a substantial undertaking; this
file deliberately does **not** prove it. Following the verified design plan for the
Abramov–Rokhlin assembly (issue #13), the M6 conditional-entropy layer ships under *supplied*
generator-reduction equalities rather than a generator theorem. Accordingly this file provides the
`IsGenerating` **predicate**, stated in the honest exact-equality σ-algebra form, together with
cheap, true API (`σ(P) ≤ the generated σ-algebra`, refinement monotonicity). The generator-reduction
equality `h(T) = h(P, T)` itself is supplied by
`Oseledets.Entropy.ksEntropy_eq_ksEntropyPartition_of_generating`
(`Oseledets.Entropy.GeneratorTheorem`).

## Design note: which σ-algebra equation?

The generated invariant σ-algebra is taken as `⨆ n, comap (T^[n]) σ(P)`, the supremum over the
*forward* iterates `T^[n]` of the pulled-back generating σ-algebra `σ(P) = generateFrom (range
P.cells)`. This is the standard one-sided generator condition for a (possibly non-invertible)
endomorphism: a point's whole `μ`-essential coordinates are recovered from the observable `P` and
its forward time-translates. The exact equality with `mα` is clean to state and is the form used by
the Kolmogorov–Sinai theorem; a `≤ mα` direction always holds (`IsGenerating` is then the reverse
saturation), so the predicate is genuinely a hypothesis, not a triviality.

## Main definitions

* `Oseledets.Entropy.IsGenerating`: `P` generates the dynamics — the smallest forward-`T`-invariant
  σ-algebra containing `σ(P)` is the ambient σ-algebra.

## Main results

* `Oseledets.Entropy.generateFrom_cells_le_generated`: `σ(P) ≤ ⨆ n, comap (T^[n]) σ(P)`, the
  cheap inclusion of the static generating σ-algebra into the forward-saturated one.
* `Oseledets.Entropy.IsGenerating.le`: a generating partition's forward-saturated σ-algebra is the
  ambient σ-algebra (unfolded form).

## References

* François Le Maître, *Notes on the Kolmogorov–Sinai theorem* (2017), §2 (the Kolmogorov–Sinai
  generator theorem).
* Peter Walters, *An Introduction to Ergodic Theory*, GTM **79**, Springer (1982), Ch. 4.
-/

open MeasureTheory Function MeasurableSpace

namespace Oseledets.Entropy

variable {α : Type*} {ι : Type*} [mα : MeasurableSpace α] [Fintype ι]

/-- The σ-algebra `σ(P) = generateFrom (range P.cells)` generated by the cells of a finite
partition `P`. This is the static observable σ-algebra: the smallest σ-algebra making membership in
each cell of `P` measurable. Marked `@[reducible]` since its value is a `MeasurableSpace` (a class
type), so it must unfold for instance resolution and definitional rewriting. -/
@[reducible]
def generatedSigmaAlgebra (μ : Measure α) (P : MeasurePartition μ ι) : MeasurableSpace α :=
  MeasurableSpace.generateFrom (Set.range P.cells)

/-- **Reindexing leaves the generated σ-algebra unchanged.** The cell family is merely permuted, so
its range — and hence the σ-algebra it generates — is the same. -/
lemma generatedSigmaAlgebra_reindex {κ : Type*} [Fintype κ] {μ : Measure α}
    (P : MeasurePartition μ ι) (e : κ ≃ ι) :
    generatedSigmaAlgebra μ (P.reindex e) = generatedSigmaAlgebra μ P := by
  have hr : Set.range (P.reindex e).cells = Set.range P.cells :=
    e.surjective.range_comp P.cells
  unfold generatedSigmaAlgebra
  rw [hr]

/-- `P` is a **generating partition** (a *generator*) for the measure-preserving system `(α, T, μ)`
when the smallest forward-`T`-pullback-stable σ-algebra containing the generated σ-algebra `σ(P)`
is the ambient measurable structure `mα`:
`⨆ n, comap (T^[n]) σ(P) = mα`.

This is the standard one-sided generator condition for a (possibly non-invertible) endomorphism:
the whole measurable structure is recovered from the observable `P` together with its forward
time-translates `T^[n]`. The Kolmogorov–Sinai theorem then gives the entropy reduction
`h(T) = h(P, T)`; that theorem is *not* proved here — this predicate is the hypothesis the
supplied-generator entropy interface (issue #13, Abramov–Rokhlin) consumes. -/
def IsGenerating (μ : Measure α) (T : α → α) (P : MeasurePartition μ ι) : Prop :=
  (⨆ n : ℕ, MeasurableSpace.comap (T^[n]) (generatedSigmaAlgebra μ P)) = mα

/-- The static generating σ-algebra `σ(P)` sits inside the forward-saturated σ-algebra
`⨆ n, comap (T^[n]) σ(P)`: the `n = 0` term is `comap (T^[0]) σ(P) = comap id σ(P) = σ(P)`, which
is bounded above by the supremum. This is the always-available `≤` half; `IsGenerating` is the
nontrivial reverse saturation up to the full ambient σ-algebra. -/
lemma generateFrom_cells_le_generated (μ : Measure α) (T : α → α) (P : MeasurePartition μ ι) :
    generatedSigmaAlgebra μ P ≤
      ⨆ n : ℕ, MeasurableSpace.comap (T^[n]) (generatedSigmaAlgebra μ P) := by
  refine le_trans (le_of_eq ?_) (le_iSup _ 0)
  rw [Function.iterate_zero, MeasurableSpace.comap_id]

/-- Unfolded form of `IsGenerating`: a generating partition's forward-saturated σ-algebra equals
the ambient measurable structure. This is just the definition, named for convenient consumption by
the Abramov–Rokhlin assembly. -/
lemma IsGenerating.le {μ : Measure α} {T : α → α}
    {P : MeasurePartition μ ι} (h : IsGenerating μ T P) :
    (⨆ n : ℕ, MeasurableSpace.comap (T^[n]) (generatedSigmaAlgebra μ P)) = mα :=
  h

/-- **Refinement monotonicity of the generated σ-algebra.** If the cells of `P` all lie in the
σ-algebra generated by a finer partition `Q` (`σ(P) ≤ σ(Q)`), then `Q`'s forward-saturated
σ-algebra contains `P`'s. In particular, if `P` already generates the dynamics, so does any
refinement `Q` of `P`. The pullback `comap (T^[n])` is monotone in its σ-algebra argument, and
`iSup` is monotone, so the saturation is monotone in `σ(·)`. -/
lemma generated_mono {μ : Measure α} {T : α → α} {P Q : MeasurePartition μ ι}
    (hPQ : generatedSigmaAlgebra μ P ≤ generatedSigmaAlgebra μ Q) :
    (⨆ n : ℕ, MeasurableSpace.comap (T^[n]) (generatedSigmaAlgebra μ P)) ≤
      ⨆ n : ℕ, MeasurableSpace.comap (T^[n]) (generatedSigmaAlgebra μ Q) :=
  iSup_mono fun _ => MeasurableSpace.comap_mono hPQ

/-- A refinement of a generator is a generator: if `σ(P) ≤ σ(Q)` and `P` generates, then `Q`
generates. The ambient σ-algebra `mα` always dominates `Q`'s forward saturation (each cell of `Q`
is measurable, so `σ(Q) ≤ mα`, hence every `comap (T^[n]) σ(Q) ≤ mα`); combined with the lower
bound from `P`'s saturation via `generated_mono`, antisymmetry pins it to `mα`. -/
lemma IsGenerating.mono_refine {μ : Measure α} {T : α → α}
    (hT : Measurable T) {P Q : MeasurePartition μ ι}
    (hPQ : generatedSigmaAlgebra μ P ≤ generatedSigmaAlgebra μ Q)
    (hP : IsGenerating μ T P) :
    IsGenerating μ T Q := by
  -- The generated σ-algebra of `Q` is below `mα`: each cell of `Q` is measurable.
  have hQ_le : generatedSigmaAlgebra μ Q ≤ mα := by
    refine MeasurableSpace.generateFrom_le ?_
    rintro s ⟨i, rfl⟩
    exact Q.measurable i
  -- Hence every forward pullback `comap (T^[n]) σ(Q) ≤ mα`, so the supremum is `≤ mα`.
  have hsup_le : (⨆ n : ℕ, MeasurableSpace.comap (T^[n]) (generatedSigmaAlgebra μ Q)) ≤ mα := by
    refine iSup_le fun n => ?_
    exact le_trans (MeasurableSpace.comap_mono hQ_le) (hT.iterate n).comap_le
  -- The reverse direction: `mα = ⨆ comap σ(P) ≤ ⨆ comap σ(Q)` via `generated_mono`.
  -- Use `hP.ge : mα ≤ ⨆ comap σ(P)` directly (rewriting `mα` would break the `Measure α` type
  -- dependency, since `μ : @Measure α mα`).
  exact le_antisymm hsup_le (le_trans hP.ge (generated_mono hPQ))

end Oseledets.Entropy
