/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Entropy.KSEntropyMono
import Oseledets.Entropy.CondChainRule
import Oseledets.Entropy.CondGivenPartitionBridge
import Oseledets.Entropy.CondMono
import Oseledets.Entropy.CondJointPullback
import Oseledets.Entropy.CondBlockSubadditive
import Oseledets.Entropy.JoinSigmaAlgebra

/-!
# Le Maître's inequality (7): the static-conditional-entropy correction

For a measure-preserving transformation `T` and two finite measurable partitions `α = P` and
`β = P'`, the Kolmogorov–Sinai entropies obey the **Le Maître inequality (7)**
`h(α, T) ≤ h(β, T) + H(α | σ(β))`,
where `H(α | σ(β))` is the *static* conditional Shannon entropy of `α` given the σ-algebra `σ(β)`
generated by the cells of `β`. This is the first half of the Kolmogorov–Sinai theorem (the bound
that drives `h(T) = h(β, T)` when `β` is generating) and a building block for the
product-entropy upper bound `h(T × id) ≤ h(T)` (Walters, Theorem 4.23).

The dynamical statement reduces to a per-`n` bound. Writing `A_n = ⋁ₖ₌₀ⁿ⁻¹ T⁻ᵏ α` and
`B_n = ⋁ₖ₌₀ⁿ⁻¹ T⁻ᵏ β` for the flat `Fin n`-indexed iterated joins:

* **refinement + chain rule** (`entropy_le_entropy_join`, the chain rule, and the σ-algebra
  bridge `condEntropyGivenPartition_eq_condEntropy_generated`):
  `H(A_n) ≤ H(A_n ∨ B_n) = H(B_n) + H(A_n | σ(B_n))`;
* **finite conditional subadditivity** (`condEntropy_ksJoin_le_sum`):
  `H(A_n | σ(B_n)) ≤ ∑ₖ<ₙ H(T⁻ᵏα | σ(B_n))`;
* **moving-conditioning collapse** (`condEntropy_mono_of_le`, then the invariance
  `condEntropy_comap_pullback`): each summand is at most `H(α | σ(β))`, because
  `σ(T⁻ᵏβ) = comap (T^[k]) σ(β) ⊆ σ(B_n)` (for `k < n`) and conditioning on the bigger σ-algebra
  decreases entropy, while `H(T⁻ᵏα | comap (T^[k]) σ(β)) = H(α | σ(β))`.

Together these give `H(A_n) ≤ H(B_n) + n · H(α | σ(β))`; dividing by `n` and passing both Fekete
limits (`tendsto_ksEntropySeq`) yields the dynamical inequality.

## Main results

* `Oseledets.Entropy.condEntropy_reindex`: invariance of `condEntropy` under reindexing the cell
  family by an equivalence of finite index types.
* `Oseledets.Entropy.entropy_joinCells_comm`: symmetry `H(α ∨ β) = H(β ∨ α)` of the static join
  entropy.
* `Oseledets.Entropy.condEntropy_ksJoin_le_sum`: finite conditional subadditivity of the
  iterated-join entropy, `H(A_n | 𝒞) ≤ ∑ₖ<ₙ H(T⁻ᵏα | 𝒞)`, for an arbitrary fixed sub-σ-algebra `𝒞`.
* `Oseledets.Entropy.ksEntropySeq_le_add_condEntropy`: the per-`n` bound
  `H(A_n) ≤ H(B_n) + n · H(α | σ(β))`.
* `Oseledets.Entropy.ksEntropyPartition_le_add_condEntropy`: Le Maître's inequality (7),
  `h(α, T) ≤ h(β, T) + H(α | σ(β))`.

## References

* François Le Maître, *Notes on the Kolmogorov–Sinai theorem* (2017), §1–2, inequality (7).
* Peter Walters, *An Introduction to Ergodic Theory*, Springer GTM 79, Chapter 4.
-/

open MeasureTheory Function Filter Topology ProbabilityTheory
open scoped ENNReal

namespace Oseledets.Entropy

variable {α : Type*} {ι κ : Type*} {𝒞 : MeasurableSpace α} [mα : MeasurableSpace α]
  [StandardBorelSpace α]

/-- **Reindexing invariance of conditional Shannon entropy.** Precomposing the cell family with an
equivalence `e : β ≃ γ` of finite index types leaves the conditional entropy unchanged, since it
merely permutes the summands of the pointwise entropy integrand. -/
lemma condEntropy_reindex {β γ : Type*} [Fintype β] [Fintype γ] {μ : Measure α}
    [IsFiniteMeasure μ] (𝒜 : MeasurableSpace α) (e : β ≃ γ) (s : γ → Set α) :
    condEntropy μ 𝒜 (fun i => s (e i)) = condEntropy μ 𝒜 s := by
  rw [condEntropy_def, condEntropy_def]
  refine integral_congr_ae (Eventually.of_forall fun ω => ?_)
  exact Equiv.sum_comp e
    (fun j => Real.negMulLog (@condExpKernel α mα _ μ _ 𝒜 ω (s j)).toReal)

omit [StandardBorelSpace α] in
/-- **Symmetry of the static join entropy:** `H(α ∨ β) = H(β ∨ α)`. The join cell families
`(i, j) ↦ sᵢ ∩ tⱼ` and `(j, i) ↦ tⱼ ∩ sᵢ` agree after swapping the product index and using
commutativity of intersection, so they have equal Shannon entropy. -/
lemma entropy_joinCells_comm {β γ : Type*} [Fintype β] [Fintype γ] {μ : Measure α}
    (s : β → Set α) (t : γ → Set α) :
    entropy μ (joinCells s t) = entropy μ (joinCells t s) := by
  rw [entropy_def, entropy_def, Fintype.sum_prod_type, Fintype.sum_prod_type, Finset.sum_comm]
  refine Finset.sum_congr rfl fun j _ => Finset.sum_congr rfl fun i _ => ?_
  rw [joinCells_apply, joinCells_apply, Set.inter_comm]

/-- **Finite conditional subadditivity of the iterated-join entropy.** For an *arbitrary* fixed
sub-σ-algebra `𝒞 ≤ mα`, the conditional entropy of the `n`-fold join is at most the sum of the
conditional entropies of the `n` single coordinates:
`H(⋁ₖ₌₀ⁿ⁻¹ T⁻ᵏ α | 𝒞) ≤ ∑ₖ<ₙ H(T⁻ᵏ α | 𝒞)`.

Induction on `n`: the `n = 0` join is trivial (entropy `0`), and the inductive step front-peels the
last coordinate via `condEntropy_ksJoin_append_le` (with block lengths `n` and `1`), identifying the
length-`1` block `T⁻ⁿ(⋁ₖ₌₀⁰ T⁻ᵏα)` with the single pullback `T⁻ⁿα` (reindexing `(Fin 1 → ι) ≃ ι`
via `condEntropy_reindex`); the induction hypothesis bounds the remaining `n`-fold join. -/
lemma condEntropy_ksJoin_le_sum [Fintype ι] {μ : Measure α} [IsProbabilityMeasure μ] {T : α → α}
    (h𝒞 : 𝒞 ≤ mα) (hT : MeasurePreserving T μ μ) (P : MeasurePartition μ ι) (n : ℕ) :
    condEntropy μ 𝒞 (ksJoin hT P n).cells
      ≤ ∑ k : Fin n, condEntropy μ 𝒞 (P.pullback (hT.iterate (k : ℕ))).cells := by
  induction n with
  | zero =>
    rw [Fin.sum_univ_zero]
    refine le_of_eq ?_
    rw [condEntropy_def]
    refine integral_eq_zero_of_ae (Eventually.of_forall fun ω => ?_)
    refine Finset.sum_eq_zero fun f _ => ?_
    have : IsProbabilityMeasure (@condExpKernel α mα _ μ _ 𝒞 ω) :=
      IsMarkovKernel.isProbabilityMeasure ω
    rw [ksJoin_cells, ksJoinCells_apply, Set.iInter_of_empty, measure_univ, ENNReal.toReal_one,
      Real.negMulLog_one]
  | succ n IH =>
    have happ := condEntropy_ksJoin_append_le h𝒞 hT P n 1
    -- Identify the length-`1` final block `T⁻ⁿ(⋁ₖ₌₀⁰ T⁻ᵏα)` with the single pullback `T⁻ⁿα`.
    have hblock : condEntropy μ 𝒞 ((ksJoin hT P 1).pullback (hT.iterate n)).cells
        = condEntropy μ 𝒞 (P.pullback (hT.iterate n)).cells := by
      have hfam : ((ksJoin hT P 1).pullback (hT.iterate n)).cells
          = fun f => (P.pullback (hT.iterate n)).cells (Equiv.funUnique (Fin 1) ι f) := by
        funext f
        simp only [MeasurePartition.pullback_cells, ksJoin_cells, ksJoinCells_apply]
        congr 1
        have hstep : ∀ k : Fin 1,
            (T^[(k : ℕ)]) ⁻¹' P.cells (f k) = P.cells (Equiv.funUnique (Fin 1) ι f) := by
          intro k
          rw [show (k : ℕ) = 0 by omega, Function.iterate_zero, Set.preimage_id,
            Equiv.funUnique_apply, Subsingleton.elim k default]
        rw [Set.iInter_congr hstep, Set.iInter_const]
      rw [hfam]
      exact condEntropy_reindex 𝒞 (Equiv.funUnique (Fin 1) ι) (P.pullback (hT.iterate n)).cells
    rw [hblock] at happ
    calc condEntropy μ 𝒞 (ksJoin hT P (n + 1)).cells
        ≤ condEntropy μ 𝒞 (ksJoin hT P n).cells
            + condEntropy μ 𝒞 (P.pullback (hT.iterate n)).cells := happ
      _ ≤ (∑ k : Fin n, condEntropy μ 𝒞 (P.pullback (hT.iterate (k : ℕ))).cells)
            + condEntropy μ 𝒞 (P.pullback (hT.iterate n)).cells := by gcongr
      _ = ∑ k : Fin (n + 1), condEntropy μ 𝒞 (P.pullback (hT.iterate (k : ℕ))).cells := by
          rw [Fin.sum_univ_castSucc]
          simp only [Fin.val_castSucc, Fin.val_last]

/-- **Per-`n` Le Maître bound.** For finite measurable partitions `α = P` and `β = P'`,
`H(⋁ₖ₌₀ⁿ⁻¹ T⁻ᵏ α) ≤ H(⋁ₖ₌₀ⁿ⁻¹ T⁻ᵏ β) + n · H(α | σ(β))`,
where `H(α | σ(β)) = condEntropy μ (generatedSigmaAlgebra μ β) α`.

Refinement (`entropy_le_entropy_join`), the entropy chain rule
and the σ-algebra bridge (`condEntropyGivenPartition_eq_condEntropy_generated`) give
`H(A_n) ≤ H(B_n) + H(A_n | σ(B_n))`; finite conditional subadditivity (`condEntropy_ksJoin_le_sum`)
splits the last term into `n` single-coordinate conditional entropies, each of which collapses to
`H(α | σ(β))` by conditioning monotonicity (`condEntropy_mono_of_le`) against
`comap (T^[k]) σ(β) ⊆ σ(B_n)` (for `k < n`) followed by the joint-pullback invariance
(`condEntropy_comap_pullback`). -/
lemma ksEntropySeq_le_add_condEntropy [Fintype ι] [Fintype κ] {μ : Measure α}
    [IsProbabilityMeasure μ] {T : α → α} (hT : MeasurePreserving T μ μ)
    (P : MeasurePartition μ ι) (P' : MeasurePartition μ κ) (n : ℕ) :
    ksEntropySeq hT P n
      ≤ ksEntropySeq hT P' n
        + (n : ℝ) * condEntropy μ (generatedSigmaAlgebra μ P') P.cells := by
  have hCnle : generatedSigmaAlgebra μ (ksJoin hT P' n) ≤ mα := generatedSigmaAlgebra_le _
  set C : ℝ := condEntropy μ (generatedSigmaAlgebra μ P') P.cells with hC
  -- σ-algebra bridge: the static conditional entropy of `A_n` given `B_n` is `H(A_n | σ(B_n))`.
  have hbridge : condEntropyGivenPartition μ (ksJoin hT P' n).cells (ksJoin hT P n).cells
      = condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT P' n)) (ksJoin hT P n).cells :=
    condEntropyGivenPartition_eq_condEntropy_generated (ksJoin hT P' n)
      (ksJoin hT P n).cells (fun f => (ksJoin hT P n).measurable f)
  -- Finite conditional subadditivity.
  have hsub : condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT P' n)) (ksJoin hT P n).cells
      ≤ ∑ k : Fin n, condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT P' n))
          (P.pullback (hT.iterate (k : ℕ))).cells :=
    condEntropy_ksJoin_le_sum hCnle hT P n
  -- Each single-coordinate conditional entropy collapses to `C = H(α | σ(β))`.
  have hterm : ∀ k : Fin n,
      condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT P' n))
        (P.pullback (hT.iterate (k : ℕ))).cells ≤ C := by
    intro k
    have hle : MeasurableSpace.comap (T^[(k : ℕ)]) (generatedSigmaAlgebra μ P')
        ≤ generatedSigmaAlgebra μ (ksJoin hT P' n) := by
      have hk1 := comap_iterate_generatedSigmaAlgebra_ksJoin_le hT P' (k : ℕ) 1
      rw [generatedSigmaAlgebra_ksJoin_one hT P'] at hk1
      refine hk1.trans (generatedSigmaAlgebra_ksJoin_mono hT P' ?_)
      have := k.isLt; omega
    calc condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT P' n))
            (P.pullback (hT.iterate (k : ℕ))).cells
        ≤ condEntropy μ (MeasurableSpace.comap (T^[(k : ℕ)]) (generatedSigmaAlgebra μ P'))
            (P.pullback (hT.iterate (k : ℕ))).cells :=
          condEntropy_mono_of_le hle hCnle (P.pullback (hT.iterate (k : ℕ)))
      _ = C := by
          rw [hC, MeasurePartition.pullback_cells]
          exact condEntropy_comap_pullback (generatedSigmaAlgebra_le P') hT (k : ℕ) P
  -- Sum the per-coordinate bounds.
  have hsum : (∑ k : Fin n, condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT P' n))
        (P.pullback (hT.iterate (k : ℕ))).cells) ≤ (n : ℝ) * C := by
    calc (∑ k : Fin n, condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT P' n))
            (P.pullback (hT.iterate (k : ℕ))).cells)
        ≤ ∑ _k : Fin n, C := Finset.sum_le_sum fun k _ => hterm k
      _ = (n : ℝ) * C := by
          rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
  calc ksEntropySeq hT P n
      = entropy μ (ksJoin hT P n).cells := rfl
    _ ≤ entropy μ (joinCells (ksJoin hT P n).cells (ksJoin hT P' n).cells) :=
        entropy_le_entropy_join (ksJoin hT P n) (ksJoin hT P' n)
    _ = entropy μ (joinCells (ksJoin hT P' n).cells (ksJoin hT P n).cells) :=
        entropy_joinCells_comm _ _
    _ = entropy μ (ksJoin hT P' n).cells
          + condEntropyGivenPartition μ (ksJoin hT P' n).cells (ksJoin hT P n).cells :=
        entropy_join_eq_add_condEntropyGivenPartition (ksJoin hT P' n) (ksJoin hT P n)
    _ = ksEntropySeq hT P' n
          + condEntropy μ (generatedSigmaAlgebra μ (ksJoin hT P' n)) (ksJoin hT P n).cells := by
        rw [hbridge]; simp only [ksEntropySeq]
    _ ≤ ksEntropySeq hT P' n + (n : ℝ) * C := by
        have h := hsub.trans hsum
        gcongr

/-- **Le Maître's inequality (7) (static-conditional-entropy correction).** For a measure-preserving
transformation `T` and finite measurable partitions `α = P` and `β = P'`, the Kolmogorov–Sinai
entropy of `α` is bounded by that of `β` plus the *static* conditional Shannon entropy of `α` given
the σ-algebra `σ(β)` generated by `β`:
`h(α, T) ≤ h(β, T) + H(α | σ(β))`.

Divide the per-`n` bound `ksEntropySeq_le_add_condEntropy` by `n`, reading
`H(A_n)/n ≤ H(B_n)/n + H(α | σ(β))`, then pass both averaged iterated-join entropies to their Fekete
limits (`tendsto_ksEntropySeq`); `le_of_tendsto_of_tendsto'` transfers the inequality to the
limits. -/
theorem ksEntropyPartition_le_add_condEntropy [Fintype ι] [Fintype κ] {μ : Measure α}
    [IsProbabilityMeasure μ] {T : α → α} (hT : MeasurePreserving T μ μ)
    (P : MeasurePartition μ ι) (P' : MeasurePartition μ κ) :
    ksEntropyPartition hT P
      ≤ ksEntropyPartition hT P' + condEntropy μ (generatedSigmaAlgebra μ P') P.cells := by
  set C : ℝ := condEntropy μ (generatedSigmaAlgebra μ P') P.cells with hC
  refine le_of_tendsto_of_tendsto' (tendsto_ksEntropySeq hT P)
    ((tendsto_ksEntropySeq hT P').add tendsto_const_nhds) ?_
  intro n
  rcases Nat.eq_zero_or_pos n with hn | hn
  · subst hn
    simp only [Nat.cast_zero, div_zero, zero_add]
    rw [hC]
    exact condEntropy_nonneg
  · have hn0 : (0 : ℝ) < n := by exact_mod_cast hn
    have hperN := ksEntropySeq_le_add_condEntropy hT P P' n
    rw [← hC] at hperN
    calc ksEntropySeq hT P n / (n : ℝ)
        ≤ (ksEntropySeq hT P' n + (n : ℝ) * C) / (n : ℝ) :=
          div_le_div_of_nonneg_right hperN hn0.le
      _ = ksEntropySeq hT P' n / (n : ℝ) + C := by
          rw [add_div, mul_comm (n : ℝ) C, mul_div_assoc, div_self hn0.ne', mul_one]

end Oseledets.Entropy
