/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Lyapunov.Extensions.ConstantCocycle
import Oseledets.Lyapunov.Extensions.ConstantCocycleSpectralRadius
import Oseledets.Lyapunov.ExteriorNorm.Plucker
import Mathlib.LinearAlgebra.Matrix.Charpoly.Eigs
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# The full Lyapunov spectrum of a general constant cocycle (Yamamoto's theorem)

For a **constant** (non-symmetric) generator `A ≡ M` the iterated cocycle is the matrix power
`Mⁿ` (`Oseledets.cocycle_const`), so the `i`-th Lyapunov exponent of the cocycle is the
deterministic limit `lim_n (1/n) log σᵢ(Mⁿ)` of the normalized log singular values of the powers.

**Yamamoto's theorem** (Yamamoto, 1967; sharpened by Huang–Tam and others) identifies this limit:
for every matrix `M` and every sorted index `i`,
```
  lim_n (σᵢ(Mⁿ))^{1/n} = |λᵢ(M)|,
```
where `|λᵢ(M)|` is the `i`-th largest *eigenvalue modulus* of `M`, counted with (algebraic)
multiplicity. Equivalently, in logarithmic form,
```
  lim_n (1/n) log σᵢ(Mⁿ) = log |λᵢ(M)|.
```
Hence the `i`-th Lyapunov exponent of the constant cocycle generated by `M` is `log |λᵢ(M)|`. This
is the natural common generalization of two facts already in the library:
* the **symmetric** case `Oseledets.exponents_const`, where `|λᵢ(M)|` is the `i`-th sorted
  eigenvalue of `|M|` (and the singular values of `Mⁿ` are literally `|λ|ⁿ`); and
* the **top** exponent `= log (spectral radius)`, which is Yamamoto at `i = 0` (`s₁ = ‖·‖`).

## Status of this module

The arithmetic content **above** Yamamoto's limit — that the cocycle's `exponents … i` equals
`log |λᵢ(M)|` *given* the limit — is proved here **sorry-free** by uniqueness of limits, since
`exponents … i` is *defined* (in `Oseledets.Lyapunov.Extensions.Spectrum`) as the deterministic
limit of exactly the sequence `(1/n) log σᵢ(cocycle …) = (1/n) log σᵢ(Mⁿ)`.

Yamamoto's limit itself (`yamamoto_singularValues_tendsto`) is the **one** `BLOCKED` leaf. This
module pursues the **exterior-power / Gelfand route** (Strategy C of the feasibility report), which
*sidesteps* the polar decomposition, the multiplicative Jordan–Chevalley decomposition, and Weyl
perturbation that the trace-moment route (Dowla–Mukherjee/Nayak) needs, reducing the entire leaf to
a **single** residual matrix-analysis fact:

> the spectral radius of the `(i+1)`-st compound (exterior power) `C_{i+1}(M)` equals the product
> of the top `i+1` eigenvalue moduli of `M`, `∏_{k≤i} |λₖ(M)|`.

The reduction works because the repository already provides the two non-trivial ingredients:

* **`σ-product = compound norm`** (`Oseledets.ExteriorNorm.prod_singularValues_eq_l2_opNorm_compound`):
  `∏_{k<j} σₖ(Mⁿ) = ‖C_j(Mⁿ)‖`, and `C_j(Mⁿ) = (C_j M)ⁿ` (`compoundMatrix_pow` below, an immediate
  consequence of Cauchy–Binet `compoundMatrix_mul`); and
* **Gelfand for a real matrix** (`Oseledets.tendsto_pow_norm_one_div_spectralRadius`):
  `‖Bⁿ‖^{1/n} → (spectralRadius ℂ B_ℂ).toReal`, applied to `B = C_j(M)`.

Chaining these gives `(σ₀⋯σ_{j-1}(Mⁿ))^{1/n} → ρ(C_j(M))`; with the residual spectral fact
`ρ(C_{i+1}(M)) = ∏_{k≤i}|λₖ|` this is the product form of Yamamoto, and the single-index statement
follows by telescoping `j = i+1` against `j = i` in `(1/n) log`. The telescoping/`log`-of-zero
bookkeeping (`yamamoto_prod_to_index`) and the eventual-vanishing bridge (`hvanish`, from
nilpotency of the compound when `|λᵢ| = 0`) are now **sorry-free**. The **single residual leaf**
that Mathlib/this repository do not yet provide is stated as a sharp, individually-typed `sorry`
below: `spectralRadius_compound_eq_prod_eigenvalueModuli` (the eigenvalues of an exterior power are
the `(i+1)`-fold products of the base eigenvalues, so the spectral radius is the product of the top
moduli). All the analytic plumbing around it is discharged sorry-free.

## Main definitions

* `Oseledets.eigenvalueModuli M` — the moduli `|λ(M)|` of the (complex) eigenvalues of a real
  matrix `M`, counted with algebraic multiplicity and **sorted in non-increasing order** as a
  `List ℝ` of length `d`. The `i`-th largest modulus is `(eigenvalueModuli M).getD i 0`.

## Main results

* `Oseledets.eigenvalueModuli_length` — the list has length `d` (so `getD i 0` is the genuine
  `i`-th entry for `i < d`).
* `Oseledets.yamamoto_singularValues_tendsto` — **Yamamoto's theorem** (the only `BLOCKED` leaf):
  `(1/n) log σᵢ(Mⁿ) → log |λᵢ(M)|`.
* `Oseledets.exponents_const_general` — **the full spectrum of a general constant cocycle**
  (sorry-free *given* Yamamoto): `exponents (fun _ => M) … i = log |λᵢ(M)|`.

## References

* T. Yamamoto, *On the extreme values of the roots of matrices*, J. Math. Soc. Japan **19** (1967).
* H. Huang, T.-Y. Tam, *An extension of Yamamoto's theorem on the eigenvalues and singular values
  of a matrix*, J. Math. Soc. Japan **58** (2006).
* P. N. Dowla, S. Mukherjee, et al., *A stronger form of Yamamoto's theorem on singular values*,
  arXiv:2303.01252 (2023). (Theorem 3.8 / Corollary 3.9.)
-/

open MeasureTheory Filter Topology
open scoped Matrix

namespace Oseledets

variable {X : Type*} [MeasurableSpace X] {d : ℕ}

/-! ## The sorted eigenvalue moduli of a real matrix -/

/-- **The sorted eigenvalue moduli of a real matrix.** Mapping `M` into `Matrix _ _ ℂ` and taking
the roots of its characteristic polynomial gives the complex eigenvalues of `M` counted with
algebraic multiplicity; their moduli, sorted in non-increasing order, form the list
`eigenvalueModuli M : List ℝ`. The `i`-th largest eigenvalue modulus is
`(eigenvalueModuli M).getD i 0`. -/
noncomputable def eigenvalueModuli (M : Matrix (Fin d) (Fin d) ℝ) : List ℝ :=
  (((M.map (algebraMap ℝ ℂ)).charpoly.roots).map (fun z => ‖z‖)).sort (· ≥ ·)

/-- The sorted eigenvalue-moduli list has length `d`: the characteristic polynomial of the `d × d`
matrix `M` (over the algebraically closed field `ℂ`) is monic of degree `d` and therefore splits
with exactly `d` roots counted with multiplicity. -/
theorem eigenvalueModuli_length (M : Matrix (Fin d) (Fin d) ℝ) :
    (eigenvalueModuli M).length = d := by
  rw [eigenvalueModuli, Multiset.length_sort, Multiset.card_map]
  -- Over the algebraically closed field `ℂ` the charpoly splits, so its root multiset has
  -- cardinality equal to its degree `d`.
  have hsplits : ((M.map (algebraMap ℝ ℂ)).charpoly).Splits := IsAlgClosed.splits _
  rw [Polynomial.splits_iff_card_roots.mp hsplits, Matrix.charpoly_natDegree_eq_dim,
    Fintype.card_fin]

/-! ## Strategy C: exterior-power / Gelfand reduction

The whole leaf reduces, through reusable repository infrastructure, to a single residual spectral
fact about the compound (exterior power) matrix. We first record the multiplicative ingredients,
then the two sharp residual `sorry`s, then the sorry-free assembly. -/

open scoped Matrix.Norms.L2Operator ENNReal

/-- **The compound (exterior power) of a matrix power is the power of the compound.**
`C_k(Mⁿ) = (C_k M)ⁿ`. This is Cauchy–Binet (`ExteriorNorm.compoundMatrix_mul`) iterated, with
`ExteriorNorm.compoundMatrix_one` for the base case; it is the multiplicativity that lets Gelfand's
formula act on `C_k(M)` rather than on each `C_k(Mⁿ)` separately. Sorry-free. -/
theorem compoundMatrix_pow (k : ℕ) (M : Matrix (Fin d) (Fin d) ℝ) (n : ℕ) :
    ExteriorNorm.compoundMatrix k (M ^ n) = (ExteriorNorm.compoundMatrix k M) ^ n := by
  induction n with
  | zero => simpa using ExteriorNorm.compoundMatrix_one k
  | succ m ih => rw [pow_succ, pow_succ, ExteriorNorm.compoundMatrix_mul, ih]

/-- **Residual leaf 1 (the eigenvalues of an exterior power).** For every `j`, the spectral radius
of the `j`-th compound (exterior power) `C_j(M)` over `ℂ` equals the product of the top `j`
eigenvalue moduli of `M`:
```
  ρ(C_j(M)_ℂ)  =  ∏_{k < j} |λₖ(M)|.
```
This is the classical fact that the eigenvalues of `⋀^j A` are exactly the `j`-fold products
`λ_{i₀}⋯λ_{i_{j-1}}` over strictly increasing index tuples; the largest modulus among these products
is attained at the top `j` eigenvalues (the list `eigenvalueModuli M` is sorted non-increasingly), so
the spectral radius — the maximal modulus of a spectral value — is `∏_{k<j}|λₖ|`. (For `j = 0` both
sides are `1`: `C_0(M)` is the `1×1` identity and the empty product is `1`. For `j > d` both sides
are `0`.)

`SHARP SORRY` (Strategy-C residual). Mathlib has `exteriorPower.map` but **no** lemma identifying its
characteristic polynomial / spectrum with the `j`-fold products of the base eigenvalues, and this
repository's `ExteriorNorm.compoundMatrix` carries only the *norm/singular-value* side, not the
*eigenvalue* side. Closing this requires either (i) a charpoly-of-compound lemma
`(C_j M).charpoly = ∏_{S ∈ powersetCard j} (X - ∏_{k∈S} λₖ)` built from the wedge-basis action of
`⋀^j(toLin M)` on products of eigenvectors, or (ii) the `det`/`trace`-coefficient route via the
elementary symmetric polynomials of the eigenvalues. Either is a self-contained matrix-analysis
contribution; it is the *only* genuinely missing mathematical content of Strategy C, the polar /
Jordan–Chevalley / Weyl machinery of the trace-moment route being entirely sidestepped. -/
theorem spectralRadius_compound_eq_prod_eigenvalueModuli [NeZero d]
    (M : Matrix (Fin d) (Fin d) ℝ) (j : ℕ) :
    (spectralRadius ℂ ((ExteriorNorm.compoundMatrix j M).map (algebraMap ℝ ℂ))).toReal
      = ∏ k ∈ Finset.range j, (eigenvalueModuli M).getD k 0 :=
  sorry

/-- **A complex matrix of spectral radius `0` is nilpotent.** If `spectralRadius ℂ A = 0` then every
spectral value (= every root of `A.charpoly`) has norm `0`, hence is `0`; the (monic, split)
characteristic polynomial is therefore `X ^ N`, and Cayley–Hamilton gives `A ^ N = 0`. -/
theorem isNilpotent_of_spectralRadius_eq_zero {N : ℕ} (A : Matrix (Fin N) (Fin N) ℂ)
    (h : spectralRadius ℂ A = 0) : IsNilpotent A := by
  -- Every spectral value is `0`.
  have hspec : ∀ μ ∈ spectrum ℂ A, μ = 0 := by
    intro μ hμ
    have : (‖μ‖₊ : ENNReal) ≤ spectralRadius ℂ A := le_iSup₂ (f := fun k _ => (‖k‖₊ : ENNReal)) μ hμ
    rw [h, nonpos_iff_eq_zero] at this
    simpa using this
  -- Every charpoly root is `0`.
  have hroots : ∀ μ ∈ A.charpoly.roots, μ = 0 := by
    intro μ hμ
    refine hspec μ ?_
    rw [Matrix.mem_spectrum_iff_isRoot_charpoly]
    exact (Polynomial.mem_roots'.mp hμ).2
  -- The charpoly splits and is monic, so it is the product over its roots of `(X - root)`.
  have hsplits : A.charpoly.Splits := IsAlgClosed.splits _
  have hmonic : A.charpoly.Monic := A.charpoly_monic
  have hprod : A.charpoly = (A.charpoly.roots.map fun a => Polynomial.X - Polynomial.C a).prod := by
    have := hsplits.eq_prod_roots_of_monic hmonic
    simpa using this
  -- All roots are `0`, so the product is `X ^ (card roots) = X ^ N`.
  have hcard : A.charpoly.roots.card = N := by
    rw [(Polynomial.splits_iff_card_roots).mp hsplits, Matrix.charpoly_natDegree_eq_dim,
      Fintype.card_fin]
  have hXpow : A.charpoly = Polynomial.X ^ N := by
    rw [hprod]
    have hmap : (A.charpoly.roots.map fun a => Polynomial.X - Polynomial.C a)
        = A.charpoly.roots.map fun _ => (Polynomial.X : Polynomial ℂ) := by
      refine Multiset.map_congr rfl ?_
      intro a ha
      rw [hroots a ha, map_zero, sub_zero]
    rw [hmap, Multiset.map_const', Multiset.prod_replicate, hcard]
  -- Cayley–Hamilton.
  refine ⟨N, ?_⟩
  have := A.aeval_self_charpoly
  rwa [hXpow, map_pow, Polynomial.aeval_X] at this

/-- The compound index `finrank ℝ (⋀^j (EuclideanSpace ℝ (Fin d)))` is nonzero exactly when
`j ≤ d`, since it equals `Nat.choose d j` (`exteriorPower.finrank_eq`,
`finrank (EuclideanSpace ℝ (Fin d)) = d`). Packaged as a `NeZero` instance under `j ≤ d` so that
Gelfand's formula (which needs a nonempty matrix index) applies to `C_j(M)`. -/
theorem neZero_finrank_exteriorPower_of_le {j : ℕ} (hj : j ≤ d) :
    NeZero (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d)))) := by
  refine ⟨?_⟩
  rw [exteriorPower.finrank_eq, finrank_euclideanSpace, Fintype.card_fin]
  exact (Nat.choose_pos hj).ne'

/-- **The Gelfand limit for the compound, in product form.** For every `j ≥ 1`,
```
  (∏_{k<j} σₖ(Mⁿ))^{1/n}  →  ρ(C_j(M)_ℂ)   as n → ∞,
```
because `∏_{k<j} σₖ(Mⁿ) = ‖C_j(Mⁿ)‖ = ‖(C_j M)ⁿ‖`
(`ExteriorNorm.prod_singularValues_eq_l2_opNorm_compound` + `compoundMatrix_pow`) and Gelfand's
formula `‖Bⁿ‖^{1/n} → ρ(B_ℂ)` (`tendsto_pow_norm_one_div_spectralRadius`) applies to `B = C_j(M)`.
Sorry-free. -/
theorem tendsto_prod_singularValues_pow (M : Matrix (Fin d) (Fin d) ℝ) (j : ℕ)
    [NeZero (Module.finrank ℝ (⋀[ℝ]^j (EuclideanSpace ℝ (Fin d))))] :
    Tendsto (fun n : ℕ =>
        (∏ k ∈ Finset.range j, (Matrix.toEuclideanLin (M ^ n)).singularValues k) ^ (1 / n : ℝ))
      atTop (𝓝 (spectralRadius ℂ
        ((ExteriorNorm.compoundMatrix j M).map (algebraMap ℝ ℂ))).toReal) := by
  -- Gelfand for the compound matrix `C_j(M)`.
  have hg := tendsto_pow_norm_one_div_spectralRadius (ExteriorNorm.compoundMatrix j M)
  refine hg.congr fun n => ?_
  -- `∏_{k<j} σₖ(Mⁿ) = ‖C_j(Mⁿ)‖ = ‖(C_j M)ⁿ‖`.
  rw [ExteriorNorm.prod_singularValues_eq_l2_opNorm_compound, compoundMatrix_pow]

/-- **Monotonicity of the sorted eigenvalue moduli.** Because `eigenvalueModuli M` is the
non-increasing (`· ≥ ·`) sort of the modulus multiset, the `i`-th entry never exceeds an earlier
entry: for `k ≤ i` with `i` inside the list, `(eigenvalueModuli M).getD k 0 ≥ (eigenvalueModuli
M).getD i 0`. Pure list bookkeeping (no matrix content). -/
theorem eigenvalueModuli_getD_antitone (M : Matrix (Fin d) (Fin d) ℝ) {k i : ℕ}
    (hki : k ≤ i) (hi : i < (eigenvalueModuli M).length) :
    (eigenvalueModuli M).getD i 0 ≤ (eigenvalueModuli M).getD k 0 := by
  have hk : k < (eigenvalueModuli M).length := lt_of_le_of_lt hki hi
  have hsorted : (eigenvalueModuli M).Pairwise (· ≥ ·) := by
    rw [eigenvalueModuli]; exact Multiset.pairwise_sort _ _
  have hrel : (eigenvalueModuli M).get ⟨k, hk⟩ ≥ (eigenvalueModuli M).get ⟨i, hi⟩ :=
    hsorted.rel_get_of_le (by exact_mod_cast hki)
  rw [List.getD_eq_getElem?_getD, List.getD_eq_getElem?_getD,
    List.getElem?_eq_getElem hk, List.getElem?_eq_getElem hi, Option.getD_some, Option.getD_some]
  simpa [List.get_eq_getElem] using hrel

/-- **Residual leaf 2 (telescoping / `log`-of-zero bookkeeping).** Given the product-form Gelfand
limits — `(∏_{k<j} σₖ(Mⁿ))^{1/n} → ∏_{k<j}|λₖ|` for `j = i` and `j = i+1`, packaged via residual
leaf 1 — together with the eventual vanishing of `σᵢ(Mⁿ)` when `|λᵢ| = 0` (the honest hypothesis
`hvanish`, discharged at the call site from the nilpotency of the compound), the single-index
Yamamoto limit `(1/n) log σᵢ(Mⁿ) → log|λᵢ|` follows by telescoping
`log(∏_{k<i+1}) − log(∏_{k<i}) = log σᵢ`.

This is the "elementary but voluminous" repackaging flagged as sub-lemma S15 in the feasibility
report: it passes from the multiplicative (`^{1/n}`) form to the additive (`(1/n)·log`) form,
divides out the lower product, and handles the junk-value branch where `|λᵢ|` vanishes
(`Real.log 0 = 0`). Sorry-free; uses only `Real`-analysis plumbing (`Real.log_rpow`,
`Real.log_prod`, `Filter.Tendsto.log`) plus the sortedness of `eigenvalueModuli` and the
honest `hvanish` hypothesis. -/
theorem yamamoto_prod_to_index [NeZero d] (M : Matrix (Fin d) (Fin d) ℝ) (i : ℕ)
    (hi : Tendsto (fun n : ℕ =>
        (∏ k ∈ Finset.range (i + 1), (Matrix.toEuclideanLin (M ^ n)).singularValues k) ^ (1 / n : ℝ))
      atTop (𝓝 (∏ k ∈ Finset.range (i + 1), (eigenvalueModuli M).getD k 0)))
    (hi' : Tendsto (fun n : ℕ =>
        (∏ k ∈ Finset.range i, (Matrix.toEuclideanLin (M ^ n)).singularValues k) ^ (1 / n : ℝ))
      atTop (𝓝 (∏ k ∈ Finset.range i, (eigenvalueModuli M).getD k 0)))
    (hvanish : (eigenvalueModuli M).getD i 0 = 0 →
        ∀ᶠ n : ℕ in atTop, (Matrix.toEuclideanLin (M ^ n)).singularValues i = 0) :
    Tendsto (fun n : ℕ => (n : ℝ)⁻¹ *
        Real.log ((Matrix.toEuclideanLin (M ^ n)).singularValues i))
      atTop (𝓝 (Real.log ((eigenvalueModuli M).getD i 0))) := by
  -- Abbreviations.
  set lami : ℝ := (eigenvalueModuli M).getD i 0 with hlami_def
  -- Both eigenvalue moduli are nonnegative (they are norms of complex numbers).
  have hmem_nonneg : ∀ x ∈ eigenvalueModuli M, 0 ≤ x := by
    intro x hx
    simp only [eigenvalueModuli, Multiset.mem_sort, Multiset.mem_map] at hx
    obtain ⟨z, _, rfl⟩ := hx
    exact norm_nonneg z
  have hmod_nonneg : ∀ k, 0 ≤ (eigenvalueModuli M).getD k 0 := by
    intro k
    rcases lt_or_ge k (eigenvalueModuli M).length with hk | hk
    · rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem hk, Option.getD_some]
      exact hmem_nonneg _ (List.getElem_mem hk)
    · rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none hk, Option.getD_none]
  rcases eq_or_lt_of_le (hmod_nonneg i) with hlami_zero | hlami_pos
  · -- **Zero case**: `λᵢ = 0`, so the target limit is `Real.log 0 = 0`, and the `i`-th singular
    -- value vanishes eventually (`hvanish`), making the sequence eventually constant `0`.
    have hlami0 : lami = 0 := hlami_zero.symm
    rw [hlami0, Real.log_zero]
    apply Tendsto.congr' (f₁ := fun _ : ℕ => (0 : ℝ))
    · filter_upwards [hvanish hlami0] with n hn
      rw [hn, Real.log_zero, mul_zero]
    · exact tendsto_const_nhds
  · -- **Positive case**: `λᵢ > 0`, hence (by sortedness) every earlier modulus is `> 0`, so both
    -- product limits are positive; take `log` of both `Tendsto`s and subtract.
    have hi_lt_len : i < (eigenvalueModuli M).length := by
      by_contra h
      push_neg at h
      rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none h, Option.getD_none] at hlami_pos
      exact lt_irrefl _ hlami_pos
    -- Each factor of the top product is positive.
    have hfac_pos : ∀ k ∈ Finset.range (i + 1), 0 < (eigenvalueModuli M).getD k 0 := by
      intro k hk
      rw [Finset.mem_range, Nat.lt_succ_iff] at hk
      exact lt_of_lt_of_le hlami_pos (eigenvalueModuli_getD_antitone M hk hi_lt_len)
    -- The two product limits are positive.
    have hP1_pos : 0 < ∏ k ∈ Finset.range (i + 1), (eigenvalueModuli M).getD k 0 :=
      Finset.prod_pos hfac_pos
    have hP0_pos : 0 < ∏ k ∈ Finset.range i, (eigenvalueModuli M).getD k 0 :=
      Finset.prod_pos fun k hk => hfac_pos k (by
        rw [Finset.mem_range] at hk ⊢; omega)
    -- Take `log` of both convergences.
    have hlog1 := hi.log hP1_pos.ne'
    have hlog0 := hi'.log hP0_pos.ne'
    -- The difference of the two log-sequences is `(1/n) log σᵢ(Mⁿ)`, eventually.
    -- First, `log` of the product limits telescopes to `log λᵢ`.
    have hlami_eq : Real.log (∏ k ∈ Finset.range (i + 1), (eigenvalueModuli M).getD k 0)
        - Real.log (∏ k ∈ Finset.range i, (eigenvalueModuli M).getD k 0) = Real.log lami := by
      rw [hlami_def, Real.log_prod (fun k hk => (hfac_pos k hk).ne'),
        Real.log_prod (fun k hk => (hfac_pos k (by rw [Finset.mem_range] at hk ⊢; omega)).ne'),
        Finset.sum_range_succ]
      ring
    -- Combine: `hlog1 - hlog0 → log λᵢ`.
    have hcomb := hlog1.sub hlog0
    rw [hlami_eq] at hcomb
    -- Match the combined sequence to the goal sequence, eventually.
    refine hcomb.congr' ?_
    filter_upwards [hi.eventually (eventually_gt_nhds hP1_pos),
      hi'.eventually (eventually_gt_nhds hP0_pos),
      eventually_ge_atTop 1] with n hn1 hn0 hn_ge
    have hn_ne : (1 / n : ℝ) ≠ 0 := by
      have : (0 : ℝ) < n := by exact_mod_cast Nat.lt_of_lt_of_le Nat.zero_lt_one hn_ge
      positivity
    -- At such `n`, all singular values in the top product are positive.
    -- `(∏σ)^{1/n} > 0` forces `∏σ > 0`.
    have hPn1_pos : 0 < ∏ k ∈ Finset.range (i + 1),
        (Matrix.toEuclideanLin (M ^ n)).singularValues k := by
      by_contra h
      push_neg at h
      have hge : 0 ≤ ∏ k ∈ Finset.range (i + 1),
          (Matrix.toEuclideanLin (M ^ n)).singularValues k :=
        Finset.prod_nonneg fun k _ => (Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg k
      have : ∏ k ∈ Finset.range (i + 1),
          (Matrix.toEuclideanLin (M ^ n)).singularValues k = 0 := le_antisymm h hge
      rw [this, Real.zero_rpow hn_ne] at hn1
      exact lt_irrefl _ hn1
    have hPn0_pos : 0 < ∏ k ∈ Finset.range i,
        (Matrix.toEuclideanLin (M ^ n)).singularValues k := by
      by_contra h
      push_neg at h
      have hge : 0 ≤ ∏ k ∈ Finset.range i,
          (Matrix.toEuclideanLin (M ^ n)).singularValues k :=
        Finset.prod_nonneg fun k _ => (Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg k
      have : ∏ k ∈ Finset.range i,
          (Matrix.toEuclideanLin (M ^ n)).singularValues k = 0 := le_antisymm h hge
      rw [this, Real.zero_rpow hn_ne] at hn0
      exact lt_irrefl _ hn0
    -- `σᵢ(Mⁿ) > 0` since the top product is positive and it is one of the factors.
    have hσi_pos : 0 < (Matrix.toEuclideanLin (M ^ n)).singularValues i := by
      rw [Finset.prod_range_succ] at hPn1_pos
      nlinarith [Finset.prod_nonneg (fun k (_ : k ∈ Finset.range i) =>
        (Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg k),
        (Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg i]
    -- Now compute the difference of logs of `rpow`s.
    rw [Real.log_rpow hPn1_pos, Real.log_rpow hPn0_pos,
      Finset.prod_range_succ, Real.log_mul hPn0_pos.ne' hσi_pos.ne']
    ring

/-! ## Yamamoto's theorem (assembled from the two residual leaves, sorry-free glue) -/

/-- **Yamamoto's theorem (the singular-value / eigenvalue-modulus limit).**
For every real `d × d` matrix `M` and every sorted index `i`, the normalized log of the `i`-th
singular value of the power `Mⁿ` converges to `log` of the `i`-th largest eigenvalue modulus of
`M`:
```
  (1/n) · log σᵢ(Mⁿ)  →  log |λᵢ(M)|   as n → ∞.
```
Equivalently `(σᵢ(Mⁿ))^{1/n} → |λᵢ(M)|`. This is the classical theorem of Yamamoto (1967), in the
logarithmic form consumed by the Oseledets spectrum.

This is assembled by **Strategy C** (exterior-power / Gelfand): the product-form Gelfand limits
`(∏_{k<j} σₖ(Mⁿ))^{1/n} → ρ(C_j(M))` (`tendsto_prod_singularValues_pow`, sorry-free) are rewritten
through the residual spectral fact (`spectralRadius_compound_eq_prod_eigenvalueModuli`,
`ρ(C_{i+1}(M)) = ∏_{k≤i}|λₖ|`) and telescoped through `yamamoto_prod_to_index` (now sorry-free) to
the single index `i`. The glue here is sorry-free; the only remaining `sorry` in the module is the
single residual matrix-analysis fact `spectralRadius_compound_eq_prod_eigenvalueModuli` (see its
docstring).

For the degenerate `d = 0` case (no `NeZero d`) the statement is handled by the constant-cocycle
consumer directly, which always supplies `[NeZero d]`. -/
theorem yamamoto_singularValues_tendsto [NeZero d] (M : Matrix (Fin d) (Fin d) ℝ) (i : ℕ) :
    Tendsto (fun n : ℕ => (n : ℝ)⁻¹ *
        Real.log ((Matrix.toEuclideanLin (M ^ n)).singularValues i))
      atTop (𝓝 (Real.log ((eigenvalueModuli M).getD i 0))) := by
  rcases lt_or_ge i d with hid | hid
  · -- Main range `i < d`: both compound dimensions `C_{i+1}`, `C_i` are nonempty, so the two
    -- product-form Gelfand limits apply; rewrite each spectral radius via residual leaf 1 and
    -- telescope via residual leaf 2.
    haveI : NeZero (Module.finrank ℝ (⋀[ℝ]^(i + 1) (EuclideanSpace ℝ (Fin d)))) :=
      neZero_finrank_exteriorPower_of_le hid
    haveI : NeZero (Module.finrank ℝ (⋀[ℝ]^i (EuclideanSpace ℝ (Fin d)))) :=
      neZero_finrank_exteriorPower_of_le hid.le
    have hi := tendsto_prod_singularValues_pow M (i + 1)
    rw [spectralRadius_compound_eq_prod_eigenvalueModuli M (i + 1)] at hi
    have hi' := tendsto_prod_singularValues_pow M i
    rw [spectralRadius_compound_eq_prod_eigenvalueModuli M i] at hi'
    have hvanish : (eigenvalueModuli M).getD i 0 = 0 →
        ∀ᶠ n : ℕ in atTop, (Matrix.toEuclideanLin (M ^ n)).singularValues i = 0 := by
      intro hzero
      -- With `|λᵢ| = 0`, the spectral radius of the `(i+1)`-st compound vanishes, so the compound
      -- is nilpotent; its powers vanish eventually, forcing the top `σ`-product (= the compound
      -- norm) and hence `σᵢ(Mⁿ)` to vanish eventually.
      set B := ExteriorNorm.compoundMatrix (i + 1) M with hB
      -- spectral radius of the compound = `∏_{k<i+1} |λₖ| = 0`.
      have hrho0 : (spectralRadius ℂ (B.map (algebraMap ℝ ℂ))).toReal = 0 := by
        rw [hB, spectralRadius_compound_eq_prod_eigenvalueModuli M (i + 1)]
        apply Finset.prod_eq_zero (Finset.self_mem_range_succ i)
        exact hzero
      -- The spectral radius is finite (bounded by the operator norm), so `toReal = 0 ⇒ = 0`.
      have hfin : spectralRadius ℂ (B.map (algebraMap ℝ ℂ)) ≠ ⊤ :=
        ne_top_of_le_ne_top (by simp) (spectrum.spectralRadius_le_nnnorm _)
      have hrho : spectralRadius ℂ (B.map (algebraMap ℝ ℂ)) = 0 := by
        rwa [ENNReal.toReal_eq_zero_iff, or_iff_left hfin] at hrho0
      -- Hence the complexified compound is nilpotent, and so is `B` itself.
      have hnilℂ : IsNilpotent (B.map (algebraMap ℝ ℂ)) :=
        isNilpotent_of_spectralRadius_eq_zero _ hrho
      obtain ⟨N, hN⟩ := hnilℂ
      have hBN : B ^ N = 0 := by
        have hmap : (B ^ N).map (algebraMap ℝ ℂ) = 0 := by
          rw [Matrix.map_pow, hN]
        ext a b
        have hab := congrArg (fun Z => Z a b) hmap
        simp only [Matrix.map_apply, Matrix.zero_apply] at hab
        exact (algebraMap ℝ ℂ).injective (by simpa using hab)
      -- For `n ≥ N`, `Bⁿ = 0`, so the top `σ`-product vanishes, hence `σᵢ(Mⁿ) = 0`.
      filter_upwards [eventually_ge_atTop N] with n hn
      have hBn0 : B ^ n = 0 := by
        obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le hn
        rw [pow_add, hBN, zero_mul]
      have hprod0 : ∏ k ∈ Finset.range (i + 1),
          (Matrix.toEuclideanLin (M ^ n)).singularValues k = 0 := by
        rw [ExteriorNorm.prod_singularValues_eq_l2_opNorm_compound, compoundMatrix_pow, ← hB, hBn0,
          norm_zero]
      -- The top product is `(∏_{k<i} σₖ) * σᵢ`; since `σᵢ` is the smallest factor (antitone) and
      -- the product is `0`, in fact `σᵢ(Mⁿ) = 0`.
      rw [Finset.prod_range_succ] at hprod0
      by_contra hne
      have hσi : 0 < (Matrix.toEuclideanLin (M ^ n)).singularValues i :=
        lt_of_le_of_ne ((Matrix.toEuclideanLin (M ^ n)).singularValues_nonneg i) (Ne.symm hne)
      have hlow : 0 < ∏ k ∈ Finset.range i,
          (Matrix.toEuclideanLin (M ^ n)).singularValues k :=
        Finset.prod_pos fun k hk => lt_of_lt_of_le hσi
          ((Matrix.toEuclideanLin (M ^ n)).singularValues_antitone
            (by rw [Finset.mem_range] at hk; omega))
      exact (mul_pos hlow hσi).ne' hprod0
    exact yamamoto_prod_to_index M i hi hi' hvanish
  · -- Tail `i ≥ d`: the `i`-th singular value is `0` (`singularValues_of_finrank_le`) and the
    -- `i`-th eigenvalue modulus is `0` (`getD` past the length-`d` list); both sides are the
    -- constant `Real.log 0 = 0`. Sorry-free.
    have hσ : ∀ n : ℕ, (Matrix.toEuclideanLin (M ^ n)).singularValues i = 0 := by
      intro n
      exact (Matrix.toEuclideanLin (M ^ n)).singularValues_of_finrank_le
        (by rw [finrank_euclideanSpace, Fintype.card_fin]; exact hid)
    have hlam : (eigenvalueModuli M).getD i 0 = 0 := by
      rw [List.getD_eq_getElem?_getD, List.getElem?_eq_none, Option.getD_none]
      rw [eigenvalueModuli_length]; exact hid
    simp only [hσ, hlam, Real.log_zero, mul_zero]
    exact tendsto_const_nhds

/-! ## The full Lyapunov spectrum of a general constant cocycle (given Yamamoto) -/

section Spectrum

variable {μ : Measure X} {T : X → X} [IsProbabilityMeasure μ] (hT : Ergodic T μ)
    {M : Matrix (Fin d) (Fin d) ℝ} (hdet : M.det ≠ 0) [NeZero d]

include hdet in
/-- **The full Lyapunov spectrum of a general (non-symmetric) constant cocycle.**
For an invertible real generator `M` (no symmetry assumed) and every sorted index `i`, the `i`-th
Lyapunov exponent of the constant cocycle `x ↦ M` is `log` of the `i`-th largest eigenvalue
modulus of `M`:
```
  exponents (fun _ => M) … i = log |λᵢ(M)|.
```

This is the **general** spectrum statement, of which the symmetric `Oseledets.exponents_const`
(where `|λᵢ(M)| = |M|.eigenvalues₀ i`) and the top-exponent (`i = 0`, the spectral radius) facts
are special cases.

The proof is by **uniqueness of limits**, given Yamamoto's theorem
(`yamamoto_singularValues_tendsto`): `exponents (fun _ => M) … i` is, by construction
(`Oseledets.exponents_tendsto_log_singularValue`), the limit of the sequence
`(1/n) log σᵢ(cocycle (fun _ => M) T n x)`, and the constant cocycle is the matrix power
(`Oseledets.cocycle_const`), so that sequence is exactly `(1/n) log σᵢ(Mⁿ)`, whose limit is
`log |λᵢ(M)|` by Yamamoto. As both sides are base-point independent, a single point extracted from
the (`NeBot`) a.e.-filter of the probability measure suffices. -/
theorem exponents_const_general (i : Fin d) :
    exponents hT (const_det_ne_zero hdet) (const_measurable M) (const_integrableLogNorm M)
        (const_integrableLogNorm_inv M) i
      = Real.log ((eigenvalueModuli M).getD (i : ℕ) 0) := by
  -- Extract a single point at which the σ-limit defining `exponents … i` holds.
  obtain ⟨x, hx⟩ := (exponents_tendsto_log_singularValue hT (const_det_ne_zero hdet)
    (const_measurable M) (const_integrableLogNorm M) (const_integrableLogNorm_inv M) i).exists
  -- Rewrite the constant cocycle as the matrix power inside the σ-sequence.
  have hcoc : ∀ n : ℕ,
      (Matrix.toEuclideanLin (cocycle (fun _ => M) T n x)).singularValues (i : ℕ)
        = (Matrix.toEuclideanLin (M ^ n)).singularValues (i : ℕ) := by
    intro n; rw [cocycle_const]
  -- Both `exponents … i` and `log |λᵢ(M)|` are the limit of the SAME sequence.
  have hx' : Tendsto (fun n : ℕ => (n : ℝ)⁻¹ *
      Real.log ((Matrix.toEuclideanLin (M ^ n)).singularValues (i : ℕ)))
      atTop (𝓝 (exponents hT (const_det_ne_zero hdet) (const_measurable M)
        (const_integrableLogNorm M) (const_integrableLogNorm_inv M) i)) := by
    refine hx.congr (fun n => ?_)
    rw [hcoc n]
  exact tendsto_nhds_unique hx' (yamamoto_singularValues_tendsto M (i : ℕ))

end Spectrum

end Oseledets
