/-
Copyright (c) 2026 Marcel Morgenstern. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marcel Morgenstern
-/
import Oseledets.Cocycle.Basic

/-!
# Measure-preserving flows and continuous-time linear cocycles

This file lays the foundation for a **continuous-flow** version of the Oseledets
multiplicative ergodic theorem (MET). The discrete-time MET is stated over a single
measure-preserving self-map `T : X → X`; the continuous-time version replaces `T` by a
measure-preserving one-parameter flow `φ : ℝ → X → X` and the iterated matrix cocycle by a
continuous-time linear cocycle `A : ℝ → X → Matrix (Fin d) (Fin d) ℝ`.

No topology on `X` is assumed: the flow is only required to be a measurable group action of
`(ℝ, +)` that preserves the measure `μ`, and the cocycle is only required to be measurable in
the state for each fixed time.

## Main definitions

* `Oseledets.MeasurePreservingFlow`: a measure-preserving one-parameter flow.
* `Oseledets.FlowCocycle`: a continuous-time linear cocycle over such a flow, valued in
  `d × d` real matrices with the newest factor on the left (matching `Oseledets.cocycle`).

## Main results

* `Oseledets.MeasurePreservingFlow.natCast_eq_iterate`: at integer times the flow is the
  iterate of its time-`1` map, `φ (n : ℝ) = (φ 1)^[n]`.
* `Oseledets.FlowCocycle.toCocycle_eq`: **the key reduction identity**. At integer times the
  continuous-time cocycle agrees with the discrete iterated cocycle generated by its time-`1`
  map over the time-`1` flow, `A (n : ℝ) x = cocycle (A 1 ·) (φ 1) n x`. This reduces the
  continuous MET at integer times to the already-proved discrete MET.
-/

open MeasureTheory

namespace Oseledets

variable {X : Type*} [MeasurableSpace X] {d : ℕ}

/-- A **measure-preserving one-parameter flow** on the measurable space `X` for the measure
`μ`: a measurable action of the additive group `(ℝ, +)` that preserves `μ`. No topology on
`X` is assumed.

The fields encode `φ 0 = id`, `φ (s + t) = φ s ∘ φ t`, and that each time-`t` map is
measure-preserving. -/
structure MeasurePreservingFlow (μ : Measure X) where
  /-- The underlying time-indexed family of self-maps `t ↦ φ t`. -/
  toFun : ℝ → X → X
  /-- The time-zero map is the identity. -/
  map_zero' : toFun 0 = id
  /-- The flow is additive: `φ (s + t) = φ s ∘ φ t`. -/
  map_add' : ∀ s t : ℝ, toFun (s + t) = toFun s ∘ toFun t
  /-- Every time-`t` map preserves the measure `μ`. -/
  measurePreserving' : ∀ t : ℝ, MeasurePreserving (toFun t) μ μ

namespace MeasurePreservingFlow

variable {μ : Measure X}

instance : CoeFun (MeasurePreservingFlow μ) (fun _ => ℝ → X → X) :=
  ⟨MeasurePreservingFlow.toFun⟩

/-- The time-zero map of the flow is the identity. -/
@[simp] theorem map_zero (φ : MeasurePreservingFlow μ) : φ 0 = id := φ.map_zero'

/-- The time-zero map of the flow fixes every point. -/
@[simp] theorem apply_zero (φ : MeasurePreservingFlow μ) (x : X) : φ 0 x = x := by
  rw [map_zero]; rfl

/-- The flow is additive in time: `φ (s + t) = φ s ∘ φ t`. -/
theorem map_add (φ : MeasurePreservingFlow μ) (s t : ℝ) : φ (s + t) = φ s ∘ φ t :=
  φ.map_add' s t

/-- Pointwise additivity in time: `φ (s + t) x = φ s (φ t x)`. -/
theorem apply_add (φ : MeasurePreservingFlow μ) (s t : ℝ) (x : X) :
    φ (s + t) x = φ s (φ t x) := by
  rw [map_add]; rfl

/-- Every time-`t` map of the flow preserves the measure `μ`. -/
theorem measurePreserving (φ : MeasurePreservingFlow μ) (t : ℝ) :
    MeasurePreserving (φ t) μ μ :=
  φ.measurePreserving' t

/-- Every time-`t` map of the flow is measurable. -/
theorem measurable (φ : MeasurePreservingFlow μ) (t : ℝ) : Measurable (φ t) :=
  (φ.measurePreserving t).measurable

/-- At integer times the flow is the iterate of its time-`1` map: `φ (n : ℝ) = (φ 1)^[n]`. -/
theorem natCast_eq_iterate (φ : MeasurePreservingFlow μ) (n : ℕ) :
    φ (n : ℝ) = (φ 1)^[n] := by
  induction n with
  | zero => simp
  | succ n ih =>
    have hcast : ((n + 1 : ℕ) : ℝ) = (n : ℝ) + 1 := by push_cast; ring
    rw [hcast, map_add, ih, Function.iterate_succ]

end MeasurePreservingFlow

/-- A **continuous-time linear cocycle** over a measure-preserving flow `φ`, valued in `d × d`
real matrices, with the newest factor on the left (matching `Oseledets.cocycle`).

The fields encode `A 0 x = 1`, the cocycle identity `A (t + s) x = A t (φ s x) * A s x`,
invertibility of each `A t x`, and measurability of each time-`t` map `A t`. -/
structure FlowCocycle {μ : Measure X} (φ : MeasurePreservingFlow μ) (d : ℕ) where
  /-- The underlying time-indexed family of matrix-valued maps `t ↦ A t`. -/
  toFun : ℝ → X → Matrix (Fin d) (Fin d) ℝ
  /-- The time-zero cocycle is the identity matrix. -/
  map_zero' : ∀ x, toFun 0 x = 1
  /-- The cocycle identity, newest factor on the left:
  `A (t + s) x = A t (φ s x) * A s x`. -/
  cocycle' : ∀ (s t : ℝ) (x : X), toFun (t + s) x = toFun t (φ s x) * toFun s x
  /-- Each cocycle matrix is invertible. -/
  det_ne_zero' : ∀ (t : ℝ) (x : X), (toFun t x).det ≠ 0
  /-- Each time-`t` map of the cocycle is measurable. -/
  measurable' : ∀ t : ℝ, Measurable (toFun t)

namespace FlowCocycle

variable {μ : Measure X} {φ : MeasurePreservingFlow μ}

instance : CoeFun (FlowCocycle φ d) (fun _ => ℝ → X → Matrix (Fin d) (Fin d) ℝ) :=
  ⟨FlowCocycle.toFun⟩

/-- The time-zero cocycle is the identity matrix. -/
@[simp] theorem map_zero (A : FlowCocycle φ d) (x : X) : A 0 x = 1 := A.map_zero' x

/-- The cocycle identity, newest factor on the left:
`A (t + s) x = A t (φ s x) * A s x`. -/
theorem cocycle_apply (A : FlowCocycle φ d) (s t : ℝ) (x : X) :
    A (t + s) x = A t (φ s x) * A s x := A.cocycle' s t x

/-- Each cocycle matrix is invertible (nonzero determinant). -/
theorem det_ne_zero (A : FlowCocycle φ d) (t : ℝ) (x : X) : (A t x).det ≠ 0 :=
  A.det_ne_zero' t x

/-- Each time-`t` map of the cocycle is measurable. -/
theorem measurable (A : FlowCocycle φ d) (t : ℝ) : Measurable (A t) := A.measurable' t

/-- **The key reduction identity.** At integer times the continuous-time cocycle agrees with
the discrete iterated cocycle generated by its time-`1` map `A 1 (·)` over the time-`1` flow
map `φ 1`:
`A (n : ℝ) x = cocycle (A 1 ·) (φ 1) n x`.

This lets the continuous-flow MET at integer times be read off from the already-proved
discrete MET applied to the generator `A 1` and the dynamics `φ 1`. -/
theorem toCocycle_eq (A : FlowCocycle φ d) (n : ℕ) (x : X) :
    A (n : ℝ) x = cocycle (fun y => A 1 y) (φ 1) n x := by
  induction n generalizing x with
  | zero => simp
  | succ n ih =>
    have hcast : ((n + 1 : ℕ) : ℝ) = (n : ℝ) + 1 := by push_cast; ring
    rw [hcast, A.cocycle_apply 1 (n : ℝ) x, cocycle_succ, ih (φ 1 x)]

end FlowCocycle

end Oseledets
